### ISSUE TITLE
SignedJwtAssertionCredentials Support for Python3

### ISSUE THREAD

**Issue by msaniscalchi** [google/oauth2client#106]
I may be missing something here, but this doesn't appear to support Python3 currently. In order to initialize the credentials, you are expected to pass in the private key file's contents as a string, so this would work for Python2:

```
  with open(KEY_FILE) as f:
    private_key = f.read()

  oauth2credentials = oauth2client.client.SignedJwtAssertionCredentials(
        SERVICE_ACCOUNT_EMAIL, private_key, SCOPE, sub=None)
```

Doing the same for Python3 would result in a UnicodeDecodeError, as it should be read in binary. Ideally, it would work as follows:

```
  with open(KEY_FILE, 'rb') as f:
    private_key = f.read()

  oauth2credentials = oauth2client.client.SignedJwtAssertionCredentials(
        SERVICE_ACCOUNT_EMAIL, private_key, SCOPE, sub=None)
```

However, while it will make it past the initialization step (it probably shouldn't), it will throw a TypeError later when you attempt to do a refresh because crypto.load_pkcs12(key, password) is expecting the key to be a string.

The easiest solution that comes to mind is to handle the private key differently depending on whether it is a str or bytes.

**Comment by craigcitro** [comment]
@msaniscalchi yep, this probably just hasn't been well-tested (or tried?) in python3 yet. 

i agree with the point about reading as `'rb'` -- at that point, it seems like the pyopenssl code would [do the right thing](https://github.com/pyca/pyopenssl/blob/27398343217703c5261e67d6c19dda89ba559f1b/OpenSSL/crypto.py#L2377-L2378), yeah?

any chance you'd have time to send a PR?

**Comment by johnaft** [comment]
+1 ran into same issue with SignedJwtAssertionCredentials

**Comment by felagund** [comment]
Still happening:-(.

**Comment by dhermes** [comment]
This has been working in Python3 for several months and we have a [system test][1] making sure it continues to work.

Here is the crucial part you may be missing in Python 3: open the file as binary

```python
    with open(P12_KEY_PATH, 'rb') as file_object:
        private_key_contents = file_object.read()
```

See the mode above is `'rb'` (read and binary) instead of just `'r'` (read).

[1]: https://github.com/google/oauth2client/blob/d1af8f3e80e4c050432c1be1d76772a3bfe19cdd/scripts/run_system_tests.py#L68-L78

**Comment by dhermes** [comment]
Sorry I closed out, can anyone give a code snippet that is failing still? It seems to me this is fully addressed but am not 100% sure of all the things reported here.

**Comment by felagund** [comment]
Yes, please close, it indeed needs to be in bytes/binary.

**Comment by wsw70** [comment]
The issue is still there -- not related to the `rb` mode, but to `crypto.load_pkcs12(key, password)` as mentioned by OP. The code to reproduce:

    import oauth2client.client
    import httplib2
    import platform
    import apiclient
    
    print(platform.python_version())
    print((oauth2client.__version__, httplib2.__version__, apiclient.__version__))
    
    with open('galarmclock.p12', 'rb') as f:
        private_key = f.read()
    
    credentials = oauth2client.client.SignedJwtAssertionCredentials(
        'mail-from-api-console@developer.gserviceaccount.com',
        private_key,
        'https://www.googleapis.com/auth/calendar.readonly',
        sub='a-sub@example.com'
    )
    http_auth = credentials.authorize(httplib2.Http())
    service = apiclient.discovery.build('calendar', 'v3', http=http_auth)
    print(service)

Output:

    3.4.3+
    ('1.5.1', '0.9.2', '1.4.2')
    Traceback (most recent call last):
      File "testauthgoogle.py", line 19, in <module>
        service = apiclient.discovery.build('calendar', 'v3', http=http_auth)
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/util.py", line 142, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 196, in build
        cache)
      File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 242, in _retrieve_discovery_doc
        resp, content = http.request(actual_url)
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 565, in new_request
        self._refresh(request_orig)
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 835, in _refresh
        self._do_refresh_request(http_request)
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 862, in _do_refresh_request
        body = self._generate_refresh_request_body()
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 1541, in _generate_refresh_request_body
        assertion = self._generate_assertion()
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 1670, in _generate_assertion
        private_key, self.private_key_password), payload)
      File "/usr/local/lib/python3.4/dist-packages/oauth2client/_openssl_crypt.py", line 120, in from_string
        pkey = crypto.load_pkcs12(key, password).get_privatekey()
    TypeError: must be str, not bytes

**Comment by dhermes** [comment]
@wsw70 I just ran your code on my machine with freshly installed versions of all the libraries in Python 3.4 and it works just fine.

Can you try

```python
import OpenSSL
print(OpenSSL.__version__)
```

**Comment by wsw70** [comment]
That was it. `OpenSSL` was 0.15 on Windows and 0.13 on Linux. Upgrading it to 0.15 fixed the issue. Thanks a lot.

**Comment by dhermes** [comment]
Good deal! Thanks for taking the time to file!
