### ISSUE TITLE
Proxies should never be used when querying GCE metadata server

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#114]
Similar changes to https://codereview.appspot.com/187380044/ should be made.

**Comment by dhermes** [comment]
I filed GoogleCloudPlatform/gcloud-python#757 to make sure we are also doing the right thing.

AFAICT we get around autodetected proxies (and `urllib` magic overhead) by directly using the `httplib` library:

```python
from six.moves.http_client import HTTPConnection
import socket

host = '169.254.169.254'
uri_path = '/computeMetadata/v1/project/project-id'
headers = {'Metadata-Flavor': 'Google'}
connection = HTTPConnection(host, timeout=0.1)

try:
    connection.request('GET', uri_path, headers=headers)
    response = connection.getresponse()
    if response.status == 200:
        return response.read()
except socket.error:  # socket.timeout or socket.error(64, 'Host is down')
    pass
finally:
    connection.close()
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/d34a15ed8cefe722233cd183866bcd9eb325439e/gcloud/_helpers.py#L146-L159
