### ISSUE TITLE
Add regression / integration tests for merges to master

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#127]
This is to prevent issues like #125 where unit tests give false sense of working code.

ISTM we'd want the following

- [ ] Python2 / Python3 - Mint a P12 Service Account access token and make a simple request
- [ ] Python2 / Python3 - Mint a JSON Key Service Account access token and make a simple request
- [ ] Python2 / Python3 - Refresh a user OAuth 2.0 token and make a simple request
- [ ] Python2 / Python3 - Mint a user OAuth 2.0 token (not possible on Travis / without human interaction)
- [ ] Python2 / Python3 - Mint a GAE / GCE Service Account access token (not possible on Travis)

**Comment by dhermes** [comment]
@anthmgoogle I'm happy to contribute this but would like to chat briefly. It will require putting a few [Travis encrypted files][1] in the repo. (See [`key.json.enc`][2] for example.)

Doing the actual encryption will require a project owner (and I am not a project owner).

[1]: http://docs.travis-ci.com/user/encrypting-files/
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/regression/key.json.enc

**Comment by anthmgoogle** [comment]
I would expect that @nathanielmanistaatgoogle should be the primary owner of questions like this.

**Comment by nathanielmanistaatgoogle** [comment]
I think there's likely to be plenty here that I don't understand at the moment but I'm perfectly happy to chat about the changes you'd like to make.

**Comment by dhermes** [comment]
Great. I'll email you to set up a VC.
