### ISSUE TITLE
Enable BYO http library

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#128]
If this is a duplicate I apologize.

ISTM this requires
- [x] Move all uses of `httplib2` into a module (call it `transport` probably) (#554, #559, #561, #577)
- [ ] Determine what assumed interface of `httplib2.Http` is needed
- [ ] Optional. Try to reduce the interface needed
- [x] Factor out the hard dependencies on `httplib2` and just use these interfaces
- [ ] Document the interface and allow credentials constructors to optionally take a custom `Http` object from any old library, e.g. `twisted` or `requests`.
- [ ] Revisit all changes and ensure consistency
- [ ] Revisit query string update hackery in #622

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle I think as a first start, using a first-class `Http` object (owned by `oauth2client`) as the output of `Credentials.authorize`. Right now, the wrapped `http` object just gets [monkey patched][1] and has a tenuous relationship with the original `Http` object and the original `Credentials` object.

[1]: https://github.com/google/oauth2client/blob/6e3c0c58f5a3ba18dc69bce9c49a975738c46c74/oauth2client/client.py#L609-L610

**Comment by dhermes** [comment]
Here are all places an `httplib2.Http` object is created:

```bash
$ git log --pretty=%H -1  # current HEAD
6e3c0c58f5a3ba18dc69bce9c49a975738c46c74
$ git grep 'Http('
oauth2client/appengine.py:        return self.credentials.authorize(httplib2.Http(*args, **kwargs))
oauth2client/client.py:            h = httplib2.Http()
oauth2client/client.py:                http = httplib2.Http()
oauth2client/client.py:        http = httplib2.Http()
oauth2client/client.py:_cached_http = httplib2.Http(MemoryCache())
oauth2client/client.py:            http = httplib2.Http()
oauth2client/client.py:            http = httplib2.Http()
oauth2client/flask_util.py:        return self.credentials.authorize(httplib2.Http(*args, **kwargs))
samples/oauth2_for_devices.py:youtube = build("youtube", "v3", http=credentials.authorize(httplib2.Http()))
scripts/run_system_tests.py:    http = credentials.authorize(httplib2.Http())
tests/test_appengine.py:        http = httplib2.Http()
tests/test_appengine.py:        http = httplib2.Http()
tests/test_appengine.py:        http = httplib2.Http()
tests/test_appengine.py:            http = httplib2.Http()
```

I also searched for `.Http` (to make sure `Http(` wasn't missing anything, e.g. aliasing a class name. It doesn't appear to be an issue (only real different results are in `tests/test_flask_util.py`). I also did `git grep 'httplib2' | grep import` to make sure that the standalone `Http` wasn't imported `as` some other name.

**Comment by jonparrott** [comment]
To summarize from GoogleCloudPlatform/gcloud-python#1346:

* We want to use `urllib3` as our official http client library. `urllib3` now supports app engine, so there shouldn't be any issues there.
* We will implement a `PoolManager` wrapper to implement the retry and auth logic that's currently monkey-patched into `httplib2.Http`.

**Comment by shazow** [comment]
> We will implement a PoolManager wrapper to implement the retry and auth logic that's currently monkey-patched into httplib2.Http.

urllib3's modern retry logic is fairly configurable, please let us know if there's anything missing that you'd need. Maybe for auth too.

**Comment by jonparrott** [comment]
> urllib3's modern retry logic is fairly configurable,

Will do. Mostly this logic handles this case:

1. User makes a request to an authentication-required resource with expired credentials.
2. The API says `403: Unauthorized`, indicating that the credentials have expired.
3. The credentials get refreshed and the entire request is retried.

Not sure if this should be the responsibility of the http library.

**Comment by shazow** [comment]
Take a look at our Retry object, worst case our goal is that you should be able to extend it and provide your own with a matching interface (might need to replace type-checking with duck-typing where we forgot).

**Comment by jonparrott** [comment]
Awesome. Even more fuel to this fire I'm setting to httplib2. :+1:

**Comment by dhermes** [comment]
Ha. It's going to be a **long** road to excise it. It's also tied too deeply into `google-api-python-client`.

**Comment by shazow** [comment]
Wish we did this when I was still at Google, I would have jumped on to help. :)

**Comment by jonparrott** [comment]
@dhermes oh, fair point about `google-api-python-client`. That library is in maintenance-only mode. We should consider some sort of fallback for `httplib2` here for that. But for `gcloud-python` we can leave httplib2 firmly behind.

**Comment by jonparrott** [comment]
Okay, so I'm on board with @dhermes' original plan. We'll leave httplib2 as the default library here, but have a well-defined interface so that `gcloud-python` can move to a different library.

We're about 6% away from full coverage, so this isn't far off.

**Comment by bjmc** [comment]
Any idea how soon this is happening? [SNI support](https://github.com/jcgregorio/httplib2/issues/233) is a must-have feature for us, and even aside from that, we'd much prefer to use `requests` over `httplib2`.

**Comment by dhermes** [comment]
Currently working on finding all the places where the `httplib2` surface area is assumed:

- `http.request` attribute / method is present
- particular signature of `httplib2.Http.request` is assumed
- response is an `httplib2.Response` object
- ... more to come

Then I will factor out the access into functions in `oauth2client.transport`.

@jonparrott @nathanielmanistaatgoogle Any suggestions for a systematic way of checking this? I am going to introduce a mock `httplib2` module and then just raise `AttributeError` and other so I can trace code paths and figure out what they assume.

**Comment by jonparrott** [comment]
> introduce a mock httplib2 module and then just raise AttributeError and other so I can trace code paths and figure out what they assume.

Considering we have 100% coverage that's a great idea.

Keep in mind that for BYO the only *essential* point is `Credentials.authorize`. What we use internally for refreshing doesn't matter. I'd love to see those to concerns separated.

**Comment by dhermes** [comment]
Well methods like `_refresh` won't matter but some public ones it will?

**Comment by jonparrott** [comment]
I've always thought it was a bit wonky that you have to pass in an http object to like every method on `Credentials`. I wonder how @nathanielmanistaatgoogle feels about that.

**Comment by dhermes** [comment]
We could make it optional or break it, but leave it optional for a generation?

**Comment by bjmc** [comment]
We have a working (for our uses, at least) implementation of this [using requests in place of httplib2.](https://github.com/google/oauth2client/compare/master...sirosen:master)

**Comment by dhermes** [comment]
Thanks!

**Comment by dhermes** [comment]
This is a comprehensive list as of cd825cc561170be36509d32f5fc23fcbeb4c0f12 of methods / functions that assume something from `httplib2`. Only one of them involves a non-http object, and it's a method that assumes the input is bytes (content from the request).

- `oauth2client.tools.run_flow(..., http=...)`
- `oauth2client.contrib.flask_util.UserOAuth2.http(...)`
- `oauth2client.contrib.django_util.UserOAuth2.http(...)`
- `oauth2client.contrib.appengine.AppAssertionCredentials._refresh(http_request)` -- unused
- `oauth2client.contrib.appengine.AppAssertionCredentials.http(...)`
- `oauth2client.contrib._metadata.get(http_request, ...)`
- `oauth2client.contrib._metadata.get_service_account_info(http_request, ...)`
- `oauth2client.contrib._metadata.get_token(http_request, ...)`
- `oauth2client.contrib.gce.AppAssertionCredentials.retrieve_scopes(http)`
- `oauth2client.contrib.gce.AppAssertionCredentials._retrieve_info(http_request)`
- `oauth2client.contrib.gce.AppAssertionCredentials._refresh(http_request)`
- `oauth2client.service_account._JWTAccessCredentials.authorize(http)`
- `oauth2client.service_account._JWTAccessCredentials.get_access_token(http=..., ...)` -- unused
- `oauth2client.service_account._JWTAccessCredentials.revoke(http)` -- unused
- `oauth2client.service_account._JWTAccessCredentials.refresh(http)` -- unused
- `oauth2client.service_account._JWTAccessCredentials._refresh(http_request)` -- unused
- `oauth2client.client.Credentials.authorize(http)` -- unused
- `oauth2client.client.Credentials.refresh(http)` -- unused
- `oauth2client.client.Credentials.revoke(http)` -- unused
- `oauth2client.client.OAuth2Credentials.authorize(http)`
- `oauth2client.client.OAuth2Credentials.refresh(http)`
- `oauth2client.client.OAuth2Credentials.revoke(http)`
- `oauth2client.client.OAuth2Credentials.retrieve_scopes(http)`
- `oauth2client.client.OAuth2Credentials.get_access_token(http)`
- `oauth2client.client.OAuth2Credentials._refresh(http_request)`
- `oauth2client.client.OAuth2Credentials._do_refresh_request(http_request)`
- `oauth2client.client.OAuth2Credentials._revoke(http_request)`
- `oauth2client.client.OAuth2Credentials._do_revoke(http_request, ...)`
- `oauth2client.client.OAuth2Credentials._retrieve_scopes(http_request)`
- `oauth2client.client.OAuth2Credentials._do_retrieve_scopes(http_request, ...)`
- `oauth2client.client.AccessTokenCredentials._refresh(http_request)` -- unused
- `oauth2client.client.AccessTokenCredentials._revoke(http_request)`
- `oauth2client.client.AssertionCredentials._revoke(http_request)`
- `oauth2client.client.verify_id_token(..., http=...)`
- `oauth2client.client._parse_exchange_token_response(content)` -- assumes bytes from HTTP client
- `oauth2client.client.credentials_from_code(..., http=...)`
- `oauth2client.client.OAuth2WebServerFlow.step1_get_device_and_user_codes(http)`
- `oauth2client.client.OAuth2WebServerFlow.step2_exchange(..., http=...)`

**Comment by jonparrott** [comment]
Carrying over from #601:

Presently, several methods on `Credentials` takes `http` as parameter:

* `authorize()`
* `get_access_token()`
* `refresh()`
* `retrieve_scopes()`
* `revoke()`

I'm proposing we go ahead and remove the `http` parameter from everything but authorize. The necessary methods should just call `transport.request(uri, method, ...)`. Transport should handle getting an appropriate http object to make the request.

`authorize()`'s http argument should eventually be changed to support other http libraries, but can just work with httplib2 for now. 

@dhermes raised concerns that users should be able to switch the transport under the covers. I absolutely agree. It's part of what I've had in mind.

As I mentioned before, `authorize` and everything else that uses `httplib2` are actually *separate* concerns. What we use for one isn't necessary what should be used for the others. In another thread, I said it should be possible for the user to use multiple http clients at the same time without issue:

```python
# urllib3
http = urllib3.PoolManager()
http = oauth2client.authorize(http, credentials)
# httplib2
http = httplib2.Http()
http = oauth2client.authorize(http, credentials)
# requests
http = requests.Session()
http = oauth2client.authorize(http, credentials)
```

All the while never configuring oauth2client itself. We could use urllib3 for all internal calls in all three cases - but we can also allow the user to change oauth2client's internal transport:


```python
import oauth2client.transport

oauth2client.transport.set_transport(oauth2client.transport.httplib2_transport)
# Or
oauth2client.transport.set_transport(oauth2client.transport.urllib3_transport)
# Or
def custom_transport():
    http = make_some_transport_object()
    return http

oauth2client.transport.set_transport(custom_transport)
```

So to draw the line even sharper - `transport` should only concern itself it library-internal http calls. Perhaps we should write a separate module to handle BYO to `authorize()` - and we should do that after we're done with the internal transport.

Does this make any sense? I tend to speak mostly nonsense so please do let me know.

**Comment by dhermes** [comment]
Can you define internal calls / library-internal http calls?

**Comment by jonparrott** [comment]
Anything that's not `authorize()`.

So http calls made (or transitively made) by:

* get_access_token()
* refresh()
* retrieve_scopes()
* revoke()

**Comment by dhermes** [comment]
Why would that be good? Those calls are made as part of the application.

**Comment by dhermes** [comment]
Example:

-   An authorized `http` object is used to get an API resource

    ```python
    uri = ('https://www.googleapis.com/urlshortener/v1/url?'
           'shortUrl=http%3A%2F%2Fgoo.gl%2FP6iqaV')
    transport.request(http, uri)
    ```

-   A `GET` is sent to the original `${URL}` (using user's transport)
-   The service rejects the request with a 401
-   A `refresh()` is made to `oauth2client.GOOGLE_TOKEN_URI` (using our transport)
-   Another `GET` is sent to the original `${URL}`, now with the token header (using user's transport)

**Comment by jonparrott** [comment]
Yep. That's the idea. Except the first example isn't what I'm thinking of. They wouldn't use our transport to initiate the request, they'd use their own.

**Comment by dhermes** [comment]
> first example

I only gave one example

> They wouldn't use our transport to initiate the request, they'd use their own.

How do you mean initiate? The original `GET` (the one that fails) is the one the user initiates (via `transport.request`) and the "internal call" is the ensuing `refresh()` that automatically occurs for an `authorize()`-d `http` object.

**Comment by jonparrott** [comment]
So - full usage example:

```python
http = urllib3.PoolManager()
credentials = GoogleCredentials.get_application_default()

credentials.authorize(http)

# http is still a urllib3.PoolManager instance.

uri = ('https://www.googleapis.com/urlshortener/v1/url?'
       'shortUrl=http%3A%2F%2Fgoo.gl%2FP6iqaV')

response = http.request('GET', uri)
```

`credentials.authorize` finds the right 'adapter' (or whatever) for `urllib3`. It attaches this 'adapter' to the http instance.

The 'adapter' will handle injecting the credentials' auth header and adding a urllib3 Retry that will refresh the credentials on 403.

So, when you call `http.request`:

1.The `GET` request is sent to `uri` with `http` (the user's http object).
2. The response is a 401. The 'adapter' catches this and calls `credentials.refresh`
3. `credentials.refresh` calls `transport.request` to refresh.
4. The request is retried with `http` (the user's http object).

So yeah, what http library oauth2client uses to refresh isn't necessary the same as the one used to make the request to the API. Of course I could make it so by doing this:

```python
oauth2client.transport.set_transport(http)
# or simiar
```

So, here's some cons of this approach:
1. It may not be immediately obvious that oauth2client is using a different transport to refresh credentials.
2. Users that need proxies and special configuration will have to configure the transport for oauth2client (this is already the case, but they may have to do it twice now).
3. This doesn't provide a way to change the transport on a per-credential basis. Though we could add a `transport` argument to the credentials' constructor - but that would *still need to be separate from the http passed to `authorize`*.

The pros of this approach:
1. There's a clear, defined separation between the user's transport and our transport.
2. This makes it far easier to add new BYO libraries for people who just want to use a different client in *their* code - we'd only need to add a new `adapter`. They wouldn't need to worry about satisfying the http contract for all of oauth2client.
3. It makes it easier for use to choose urllib3 as the default transport while preserving httplib2 compatibility forever. We can use urllib3 (yay threadsafety and sanity) internally and all downstream clients that are behind can continue to use httplib2.

Thoughts? Or is this totally crazy?

The alternative is continuing to allow http arguments to all of these methods and somehow making transport deal with internal usage as well as adapting whatever is thrown into `authorize`.

**Comment by dhermes** [comment]
> It attaches this 'adapter' to the http instance.

This is a messy idea, monkey patching is very hard to "get right". For example, some `http` instances may have `__slots__` defined and we won't even be able to "attach" something.

----

The approach is essentially the same: mix their transport with our own.

We could instead define a `transport.Http` class and provide documentation on how to define subclasses of it. This way `authorize()` would return an `Http` object and then that object could just use whatever has been wrapped:

```python
>>> transport_http = credentials.authorize(http)
>>> transport_http
<oauth2client.transport.Http at 0x7f41a5313850>
>>> transport_http._transport is http
True
```

Then `transport_http._transport` can just be used for every request that `transport_http` makes. (This may break down when `http` is a module, i.e. `requests` instead of a standalone object.)

**Comment by jonparrott** [comment]
>  monkey patching is very hard to "get right"

We'd only have to do monkey patching for httplib2. urllib3 and requests have [better mechanisms](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.retry.Retry) for this.

> would return an Http object and then that object could just use whatever has been wrapped

If I understand correctly, this would return a `oauth2client.transport` object instead of their transport. They'd then have to use our interface instead of the familiar interface of their http library. I'm not cool with that.

**Comment by dhermes** [comment]
@jonparrott Maybe a good path forward would be to add retry hooks into `httplib2` and then require a minimum version.

**Comment by dhermes** [comment]
> They'd then have to use our interface instead of the familiar interface of their http library. I'm not cool with that.

Good point

**Comment by jonparrott** [comment]
>  Maybe a good path forward would be to add retry hooks into httplib2 and then require a minimum version.

Long-term, sure. But I'd rather not waste any more time with httplib2. Adding proper retry hooks to that library is lipstick on a pig at this point.

**Comment by dhermes** [comment]
Ha good point. The monkey patching is just gross.

**Comment by jonparrott** [comment]
I agree, which is why we should warn users about httplib2 and make urllib3 the prefered "user transport". There are so many problems with it (ssl being the biggest glaring issue).

**Comment by bjmc** [comment]
Why `urllib3` and not `requests`? Are you just trying to stick with a lower-level library? requests gives you lots of nice stuff for free.

**Comment by jonparrott** [comment]
@bjmc requests is sugar on top of urllib3. For the internal use of this library, urllib3 is the way to go. We'd still support requests as an option to `credentials.authorize`.

**Comment by bjmc** [comment]
> requests is sugar on top of urllib3.

Sure, that's what I mean when I say "lower-level". It just seems like you're doing a fair amount of fiddling with URL/HTTP-related things ([e.g.](https://github.com/google/oauth2client/pull/622/files#diff-f752155b1078f859b6c1ce32715d39ddR300)) and maybe requests would spare you from doing that yourself? But maybe not.

**Comment by jonparrott** [comment]
Probably not much moreso than urllib3 would.

**Comment by jonparrott** [comment]
@dhermes my thoughts and ideas for moving this forward are the same as my previous comments [here](https://github.com/google/oauth2client/issues/128#issuecomment-239216324) and [here](https://github.com/google/oauth2client/issues/128#issuecomment-239249176).

In summary we should strictly separate the concepts of "transport" (internal http client used to refresh credentials/etc.) and the "adapter" (the means by which we provide the auth token to the user's http client). As I mentioned before, the biggest drawback is that it will be *possible* for the http client that this library uses and the http client that the user's code uses can be different. I am personally okay with this situation - it's actually more common than you think for a single application to use multiple http clients because of dependent libraries.

I'm happy to hear yours and @nathanielmanistaatgoogle's thoughts on this before we move forward.

If we do move forward the work items would look like this:
- [ ] make transport self-contained - it can construct its own http client instead of needing it passed in.
- [ ] expose a way to set the transport, e.g. `oauth2client.transport.set_transport()`
- [ ] remove all http arguments from `Credentials` methods.
- [ ] add the new adapters module and move the existing httplib2 authorize code there.
- [ ] switch transport to use urllib3 instead of httplib2.
- [ ] add an adapter for urllib3.
- [ ] add an adapter for requests.

I can start on this myself later this month once I get a few other things off my plate, or, if someone beats me to it I'm happy to review.

**Comment by nathanielmanistaatgoogle** [comment]
Two reactions right now:

1. Are we forecasting kind of an [ad hoc polymorphism](https://en.wikipedia.org/wiki/Ad_hoc_polymorphism) in which the user can only choose among certain HTTP libraries, a parametric polymorphism in which the user can supply any implementation of an HTTP library interface that we define, or a best-of-both-worlds in which we still provide an interface _and_ we provide implementations of it for the HTTP libraries toward which we'd want to steer users? If the second or third, what's the interface?
2. Do we have to use global state? Doesn't that introduce a diamond problem in which library B tells `oauth2client` to use transport b, library C tells `oauth2client` to use transport c, and library A wants to use library B and library C at the same time but can't?

**Comment by jonparrott** [comment]
For 1, leaning towards the far latter: we'll provide an interface and provide implementations based on urllib3 (the new default) and httplib2 (for legacy reasons). As far as the interface - I'm not sure yet, but once we get the two in place I'll codify the interface in whichever way you feel is most appropriate.

For 2, I thought about this a bit and I can think of two ways forward:

A. Global state (e.g. `oauth2client.transport.set_transport(...)`) which sets the background transport for the entire app. I don't believe there would ever be a *library* making this call - this is a call that should be made by the final consuming application. Any libraries built on top of oauth2client should be oblivious to the background transport (libraries should only care about the authentication transport, which will be handled by `Credentials.authorize` and the adapter classes).
B. Make `transport` or `background_transport` a constructor argument to `Credentials`. I'm not a huge fan of this because it complicates our serialization/deserialization story.

I'm open to arguments for/against either or alternatives.

**Comment by jonparrott** [comment]
bump, now that I have gotten a few things off my plate I can actually continue some of this work if I can get agreement between @nathanielmanistaatgoogle and @dhermes on the direction.

**Comment by dhermes** [comment]
I am still in disagreement on having a separate internal transport. It sames the main (only?) reason for this is to allow auto-magic method calls that don't require an `http` argument. But this is a stark trade-off for making users chase around different transports, especially if their application requires very detailed instrumenting.

**Comment by jonparrott** [comment]
> It sames the main (only?) reason for this is to allow auto-magic method calls that don't require an http argument. 

Definitely isn't the only reason. Some reasons:
* Isolate this library from having to support every http transport for its internal purposes. 
* Give users who want to use oauth2client with new http libraries a smaller interface to implement.
* Allow usage with legacy libraries without having to use a legacy transport(e.g. google-api-python-client).

> users chase around different transports

It's not verify difficult for a user to do:

```python
>>> oauth2client.transport.set_transport(oauth2client.transport.urllib3)
>>> ...
>>> http = urllib3.PoolManager()
>>> http = credentials.authorize(http)
```

which means the background transport and their http client library are one and the same. In fact, this is a much better situation than a lot of Python libraries which more or less force you to use one transport. For some libraries this transport is requests and that's okay, but some libraries (like us right now) force users to use httplib2 with no clean way to change it.

I'm interested to see @nathanielmanistaatgoogle's thoughts, but as a way to move forward how would you feel I went forward with the separation plan but left the door open to unifying it later?

**Comment by dhermes** [comment]
> Isolate this library from having to support every http transport for its internal purposes.

But if we define a common interface, then the people trying to use a novel http transport just need to consult our handy-dandy documentation for adding a new transport. Then they can adhere to the interface we define and none of our keep needs to care what kind of duck it is.

To make this easier, we could define `HTTP` and `Response` base classes so that everyone can subclass them, but that wouldn't be necessary.

**Comment by dhermes** [comment]
> Allow usage with legacy libraries without having to use a legacy transport

I'm not sure how that would be possible. Seems like it'll be a lot of work to make the 'external calls" be not-`httplib2`, even if the internal calls use something else by default.

**Comment by jonparrott** [comment]
> I'm not sure how that would be possible. Seems like it'll be a lot of work to make the 'external calls" be not-httplib2, even if the internal calls use something else by default.

Not sure what you mean, but ideally the situation would work exactly as it does today - just with `refresh` using the internal transport instead of whatever http object is passed to `authorize`.

**Comment by dhermes** [comment]
I see. The only entry point into `google-api-python-client` is passing an authorized `credentials` object, so the transport isn't really encoded in that library (other than the signature).

**Comment by jonparrott** [comment]
true.

**Comment by jonparrott** [comment]
Chatted with @dhermes, I'm going to go forward without separation. We can resume the discussion if needed later.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!

**Comment by dhermes** [comment]
Some great memories with this issue @theacodes!

**Comment by shazow** [comment]
Turns out the real issues were the friends we made along the way.

**Comment by theacodes** [comment]
Hahahaha
