### ISSUE TITLE
Revoking with the access token throws a TokenRevokeError

### ISSUE THREAD

**Issue by gzog** [google/oauth2client#132]
The program tries to revoke the access and refresh tokens of a Google Analytics service.
The error occurs in credentials.revoke(), in the following snippet of code:
```py
@require_GET
def logout(request):
    if request.app_user:
        from oauth2client.client import Credentials
        credentials = Credentials.new_from_json(request.app_user['credentials_json'])
        if not credentials.refresh_token:
            try:
                credentials.revoke(httplib2.Http())
            except Exception:
                # If credentials.revoke() doesn't work for some reason
                # use a plain http request as a fallback
                import requests
                response = requests.get(
                    credentials.revoke_uri + '?token=' + credentials.access_token)
        auth.logout(request)
        return HttpResponse()
    else:
        return HttpResponse(status=401)
```

The credentials.access_token is set and valid and the credentials.refresh_token is set to None. 
The credentials.revoke() causes an TokenRevokeError but when I want to do the same thing using the requests library, it works perfectly. 
```py
requests.get(credentials.revoke_uri + '?token=' + credentials.access_token)
``` 

To better understand what I'm saying, here is a screenshot of when the above snippet gets executed:
![oauth2client-revoke-error](https://cloud.githubusercontent.com/assets/1487006/6204497/1e8b4f9c-b556-11e4-8d1c-863ee8f55028.png)

**Comment by craigcitro** [comment]
yep, it looks like the code only uses the refresh token for revocation -- we need to fall back to the access token if the refresh token isn't available.
