### ISSUE TITLE
PEP8-conformity

### ISSUE THREAD

**Issue by dkkline** [google/oauth2client#137]
Is there any reason why oauth2client is using two spaces for indentation instead of four, as recommended by [PEP 8](https://www.python.org/dev/peps/pep-0008/#indentation)?

Would people be opposed to switching to PEP8-friendly code?

**Comment by anthmgoogle** [comment]
It might be related to keeping the lines to 80 characters, which would cause more wrapping with 4 characters. Certainly a disruptive change that should not be done lightly or not while there was a lot of work in progress.

**Comment by dhermes** [comment]
There is a very simple reason, the Google internal style guide.

Though looking at the [current][1] style guide, maybe Google has moved back to using 4 spaces internally? (I left in 2013.)

[1]: https://google-styleguide.googlecode.com/svn/trunk/pyguide.html

**Comment by craigcitro** [comment]
@dhermes is right -- this code was originally written to (mostly) follow the internal google python style guide. it's still 2 spaces.

i think everyone would be amenable to switching to full pep8, but as @anthmgoogle points out we'd cause a lot of churn for outstanding PRs. @nathanielmanistaatgoogle might be able to pick a good point to decree "we heretofore will use pep8".

**Comment by dhermes** [comment]
We did this in `gcloud-python`. I used `pep8ify` to change the indents and made sure that `git diff --ignore-all-space` was empty.

After that I had to use a [custom script][1] to indent the docstrings.

From there, getting `pylint` compliance took careful tweaking of our config and submitting PRs by hand.

[1]: https://gist.github.com/dhermes/85c3a3a464d2cff312ea

**Comment by nathanielmanistaatgoogle** [comment]
I'm not opposed to it, but spell out the benefit of switching?

**Comment by craigcitro** [comment]
external users don't see our code and think "why does this all look funny"?

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle WDYT about doing this?

**Comment by nathanielmanistaatgoogle** [comment]
I think very highly of it happening. You've made most of the changes in the recent past and would be in the best position to judge the right time to do it. I'm personally sweet on [pyformat](https://pypi.python.org/pypi/pyformat) and hope it is up to the task.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Looking at https://github.com/google/oauth2client/pulls I think now is as good a time as any to make this happen.

How do we want to usher it in?

Then I dream of moving on to #212 and then to #128.

**Comment by nathanielmanistaatgoogle** [comment]
Run autopep8 and see how it looks? Run pyformat and see how it looks? Decide which one you like more? Decide which one you trust more? Have you any experience with either tool?

"Manually" is the last manner in which I would like to usher in such a change.

**Comment by dhermes** [comment]
I've been down this road once before: GoogleCloudPlatform/gcloud-python#179

**Comment by dhermes** [comment]
Here I go...
