### ISSUE TITLE
higher level get_credentials utility function

### ISSUE THREAD

**Issue by ptone** [google/oauth2client#141]
It would be great to have a higher level wrapper like get_credentials:

https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/credentials.py#L33

directly in this library

**Comment by anthmgoogle** [comment]
My understanding of the plan of record was that gcloud-ptyon can depend on
the existing implementation in oauth2client and the type it returns should
also work as an input to gcloud. I believe this is already enabled, so we
should not need to duplicate such functionality in gcloud-python.

**Comment by ptone** [comment]
This is basically now addressed in my mind with:
https://developers.google.com/identity/protocols/application-default-credentials
