### ISSUE TITLE
Well known file is created with inapproriate permission 

### ISSUE THREAD

**Issue by anthmgoogle** [google/oauth2client#144]
When I run "gcloud auth login", the file ${HOME}/.config/gcloud/application_default_credentials.json is created with a permission 0644, which seems inappropriate in my opinion. I think it should be 0600 or something stricter.

**Comment by dhermes** [comment]
This should be filed against the `gcloud` command line tool, not this library.

Though maybe this library is responsible for the auth bits of `gcloud`, so then it wraps around :)

**Comment by anthmgoogle** [comment]
I believe that gcloud calls into oauth2client to write out this file.

**Comment by dhermes** [comment]
Following the trail (via `git grep`),

- `'application_default_credentials.json'` is only used once as `WELL_KNOWN_CREDENTIALS_FILE`
- `WELL_KNOWN_CREDENTIALS_FILE` is only used when defined and in `_get_well_known_file()`
- `_get_well_known_file()` is only called when reading and in `save_to_well_known_file()`

Finally, the culprit `save_to_well_known_file()` is never used in `oauth2client`, it is simply defined to be used elsewhere:

```
$ git grep save_to_well_known_file | egrep -v '^test'
oauth2client/client.py:def save_to_well_known_file(credentials, well_known_file=None):
$ git log -1 --pretty=%H  # HEAD at the time of the check
fd054dcdcc5f6a4d3a0b7a29f410f415f342044c
```

------------

After running `gcloud components update` to get the latest (as of March 24, 2015):

```
$ grep -r save_to_well_known_file ~/google-cloud-sdk/
```

the caller seems to be

```
google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/auth/login.py
```

in `Login.LoginAs` where it actually calls

```python
client.save_to_well_known_file(google_creds)
```

**Comment by dhermes** [comment]
@anthmgoogle Anyhow I'll submit a PR to fix this.
