### ISSUE TITLE
ClientSecrets JSON file from AppEngine does not have redirect_urls property

### ISSUE THREAD

**Issue by byuksel** [google/oauth2client#16]
I downloaded the clientsecrets JSON file from a standard AppEngine instance and when I try to do oauth with 

from oauth2client.client import flow_from_clientsecrets
flow = flow_from_clientsecrets(secrets_file, scope=scope,
                                 message=MISSING_CLIENT_SECRETS_MESSAGE)

I get the following error:
Error:Missing property "redirect_uris" in a client type of "web". 

We may need to remove the "redirect_uris" from required tags list.

**Comment by Copper-Head** [comment]
I have also run into this issue. Have there been any developments on this?

**Comment by acolange** [comment]
Old question but I didn't see the answer that solved my issue anywhere.  Make sure you had the Authorized redirect URIs and Authorized JavaScript origins set before you download the client secrets JSON file.  If they are not populated in the console they will be missing from the JSON file.

**Comment by scotpfleghaar** [comment]
I also ran into this issue today. in the JSON file (client_Secrets.JSON) you have to have the property "redirect_uris" before the property "javascript_origins"

Before:
`{
    "web": {
        "client_id": "Blahblahblah.apps.googleusercontent.com",
        "project_id": "restaurant-menu-app-172315",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "Blahblahblah",
        "javascript_origins": ["http://localhost:5000", "http://localhost:8000"]
    }
}`

After:
`{
    "web": {
        "client_id": "Blahblahblah.apps.googleusercontent.com",
        "project_id": "restaurant-menu-app-172315",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "Blahblahblah",
        "redirect_uris": ["http://localhost:8000/restaurant"],
        "javascript_origins": ["http://localhost:5000", "http://localhost:8000"]
    }
}
`
As you can see we have added the appropiate redirect after we have been authenticated from google.

**Comment by fivejjs** [comment]
must change the JsonModel class, which is near line 265 in 'model.py'
```
class JsonModel(BaseModel):
  """Model class for JSON.

  Serializes and de-serializes between JSON and the Python
  object representation of HTTP request and response bodies.
  """
  accept = 'application/json'
  content_type = 'application/json'
  alt_param = 'json'

  def __init__(self, data_wrapper=False):
    """Construct a JsonModel.

    Args:
      data_wrapper: boolean, wrap requests and responses in a data wrapper
    """
    self._data_wrapper = data_wrapper

  def serialize(self, body_value):
    if (isinstance(body_value, dict) and 'data' not in body_value and
        self._data_wrapper):  
      body_value = {'data': body_value}
    if 'data' in body_value:
      body_value['data'] = body_value['data'].decode('utf-8')
    #pdb.set_trace()
    tmp = []
    **for k, v in body_value.items():
      if isinstance(v, bytes):
        tmp.append((k, v.decode('utf-8')))**
      else:
        tmp.append((k, v))
    body_value = dict(tmp)
    return json.dumps(body_value) ###

  def deserialize(self, content):
    try:
        content = content.decode('utf-8')
    except AttributeError:
        pass
    body = json.loads(content)
    if self._data_wrapper and isinstance(body, dict) and 'data' in body:
      body = body['data']
    return body

  @property
  def no_content_response(self):
    return {}
```

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
