### ISSUE TITLE
Suggest supporting `proxy_rdns` setting while constructing Httplib2.Http in client.py

### ISSUE THREAD

**Issue by kygx-legend** [google/oauth2client#172]
Such as class `OAuth2WebServerFlow` in client.py, when call `step*()` functions, it would construct `Httplib2.Http` objects. If using proxy, `Httplib2.Http` would use proxy from environment. However, if the proxy needs _reverse DNS(rdns)_, all requests of `Httplib2.Http` are blocked and there're no methods to set `proxy_rdns` to `True`. The best way is to construct `Httplib2.ProxyInfo` object which has all proxy settings including `proxy_rdns`. Then make this as a parameter to construct `Httplib2.Http`.

**Comment by legendlee1314** [comment]
A customer, `depot_tools` in Chromium would be blocked by this issue when running ` depot-tools-auth.py login codereview.chromium.org --auth-no-local-webserver`. It occurs:
```
  File "/workspace/project/depot_tools/third_party/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/workspace/project/depot_tools/third_party/oauth2client/client.py", line 1282, in step2_exchange
    headers=headers)
  File "/workspace/project/depot_tools/third_party/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/workspace/project/depot_tools/third_party/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/workspace/project/depot_tools/third_party/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
third_party.httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com
```

**Comment by dhermes** [comment]
This is somewhat related to #128, "Determine what assumed interface of `httplib2.Http` is needed" requires finding every creation and use of an `httplib2.Http` object.

**Comment by legendlee1314** [comment]
Thanks for reply! :)

BTW, would you guys start to solve this issue by wrapping a configurable `httplib2.Http` object?

**Comment by dhermes** [comment]
I'd like to implement a `transport` module and just have our own custom `Http` class (or have a set of our own `Http` classes) and then allow people to define extensions e.g. `oauth2client-requests` which allowed using a different transport.

**Comment by legendlee1314** [comment]
Got it. Looking forward to! :)

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
