### ISSUE TITLE
OpenSSL detection fails if OpenSSL is available, but OpenSSL.crypto is missing.

### ISSUE THREAD

**Issue by craigcitro** [google/oauth2client#190]
in the case that someone has installed `OpenSSL` without including the `crypto` module, our `OpenSSL` detection now detects `OpenSSL`, but fails when trying to use it. this wouldn't happen in the case of using `pip`, but could be possible if someone's customized their install (say to remove C extensions in a case like Google App Engine).

@dhermes will surely get a chuckle out of this one. :smile:

**Comment by dhermes** [comment]
Oh joy!
