### ISSUE TITLE
CryptoUnavailableError thrown since PyCrypto/PyOpenSSL is optional dependency

### ISSUE THREAD

**Issue by parthibanloganathan** [google/oauth2client#194]
`CryptoUnavailableError` was raised from running the code snippet below.

```
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open('some_private_key.json'))
scope = ['https://spreadsheets.google.com/feeds']
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
```

On closer inspection, it seems it's being raised [here](https://github.com/google/oauth2client/blob/103c354eb6506415961fced0c08f701f95362627/oauth2client/client.py#L1453) because this library requires PyCrypto or PyOpenSSL. Perhaps this dependency should be made clear?

`pip install PyOpenSSL` resolved the issue.

**Comment by dhermes** [comment]
They are optional for users that don't need to use service accounts and there are cases (e.g. Google App Engine) where users can't actually have them installed.

However, the error message could likely be extended.

**Comment by dhermes** [comment]
Closing this since #160 already handles improving the error message.
