### ISSUE TITLE
Python 3 + PyCrypto: crypt.verify_signed_jwt_with_certs raises "Invalid token signature" due to string/bytes bug

### ISSUE THREAD

**Issue by thomasboyt** [google/oauth2client#201]
I was getting a mysterious "Invalid token signature" error trying to validate Google Sign-In-generated tokens using this method on Python 3.4.0 with PyCrypto. After confirming with jwt.io and the `tokeninfo` endpoint that the token was, indeed, valid, I dove into the method source. [After realizing that all exceptions were swallowed in the PyCrypto wrapper's `verify` method](https://github.com/google/oauth2client/blob/c5eb9f14d46d89fb33c4409a0d32fad4b919e136/oauth2client/crypt.py#L231-L235), I found out that the call:

```python
SHA256.new(message)
```

was raising:

```python
TypeError: Unicode-objects must be encoded before hashing
```

This is because `message` is a string, and not bytes. This isn't surprising when you see where `message` is initially set: 
https://github.com/google/oauth2client/blob/c5eb9f14d46d89fb33c4409a0d32fad4b919e136/oauth2client/crypt.py#L413.

I applied a quick fix to that line:

```python
signed = ('%s.%s' % (segments[0], segments[1])).encode('utf-8')
```

And the method validated my token correctly.

In addition to this fix, I'd recommend removing that `try/except` block - I'm not sure why you'd want to swallow exceptions there, other than to make it harder for poor developers like me to debug issues ;)

**Comment by dhermes** [comment]
@thomasboyt Can you send a code snippet that invoked this failure? Also, what version of the library are you using:

```python
import oauth2client
print oauth2client.__version__
```

**Comment by thomasboyt** [comment]
```
>>> print(oauth2client.__version__)
1.4.11
```

The code snippet invoking this failure was essentially identical to the one on https://developers.google.com/identity/sign-in/web/backend-auth#using-a-google-api-client-library

**Comment by dhermes** [comment]
It seems the relevant bits here then are:

```python
from oauth2client import client, crypt
idinfo = client.verify_id_token(token, CLIENT_ID)
```

along with the fact that you are using `PyCrypto` (instead of `pyOpenSSL`) and Python 3.

**Comment by dhermes** [comment]
I am verifiying the failure in https://gist.github.com/dhermes/f77b972cbd5934b5f403 (with an expired token for my personal GMail account). My hunch is that the problem is with `'%s.%s'` when signing the first two segments of the JWT.

**Comment by dhermes** [comment]
I tested on Py2.7 and Py3.4 with OpenSSL and PyCrypto. Of the four possible cases, it **only** fails on Python 3.4 with PyCrypto.

**Comment by dhermes** [comment]
With the most recent [revision][1] of the gist (making sure `signed` part was bytes, as suggested), all four scenarios are [working][2].

[1]: https://gist.github.com/dhermes/f77b972cbd5934b5f403/revisions
[2]: https://gist.github.com/dhermes/f77b972cbd5934b5f403/3bab27f19cf169985e445b1d795cd2a21efe6bea

**Comment by dhermes** [comment]
@thomasboyt Thanks a lot for this. I saw your tweets and tried to help out a little bit.

Question, why are you using the special combination of PyCrypto and Python 3.4? Typically we see people using PyCrypto without OpenSSL when they are on App Engine. But Python 3.4 means this isn't the case.

**Comment by dhermes** [comment]
@thomasboyt Sorry it took so long to get this fixed. I'm not sure when the next release will be cut.

Care to offer why you are using the special combination of PyCrypto and Python 3.4?

**Comment by thomasboyt** [comment]
Thanks for this PR; I've got a hotfixed fork I'm using but will switch back once the next release is cut :)

As for why PyCrypto: I'm using http://www.paramiko.org/ in my codebase and that depends on PyCrypto, so it's what I had installed by default. I could use PyOpenSSL if it were a requirement, but I figured that since it supported either, I'd just stick with PyCrypto.

**Comment by dhermes** [comment]
Thanks for the info! We certainly want to support all code-paths, Py3.4+PyCrypto just seemed to be a rare one.

**Comment by PAStheLoD** [comment]
It could be rare, but we also happened to spend quite a few hours figuring this out on Py3.4 with PyCrypto. :)

**Comment by dhermes** [comment]
Sorry for the trouble. Thanks for the report!
