### ISSUE TITLE
support for pyasn1 0.1.8

### ISSUE THREAD

**Issue by maemigh** [google/oauth2client#202]
New version of pyasn1 was just released

**Comment by dhermes** [comment]
Thanks. @maemigh are you a part of the `pyasn1` project or just an enthusiastic user?

https://github.com/google/oauth2client/blob/c5eb9f14d46d89fb33c4409a0d32fad4b919e136/setup.py#L39

shows that we have a pinned dependency.

@craigcitro do you know why this is the case historically?

**Comment by craigcitro** [comment]
i think we were just being conservative -- we didn't originally want to depend on a library at `0.1.x` or `0.0.x` (`pyasn1_modules`), so pinning to a known-working version seemed safer than accidentally picking up breaking changes.

is there something we need in the new version?

**Comment by maemigh** [comment]
I'm just a user. Nothing I needed it for in particular--I ended up with the newer version after upgrading some other modules and noticed that oath2client wouldn't work with the new version without hacking the requires file. 

I suppose downgrading or just leaving the hack in place works fine if you are reluctant to remove the pin.

**Comment by craigcitro** [comment]
using `>=` is probably better for the outside world. the real issue is that internally, we pin to a particular version, which means pinning externally keeps the two in sync. :grinning:

**Comment by dhermes** [comment]
BigCorp should learn how to play nice with Open Source. Isn't there same way to pin internally or just have a custom `setup.py` internally?

**Comment by craigcitro** [comment]
we're pinned internally. so pinning outside keeps things consistent; i don't think it's a big issue to switch to `>=`.

**Comment by dhermes** [comment]
Thanks @maemigh for filing and thanks @craigcitro for coming out of retirement to take my snark :smiling_imp:
