### ISSUE TITLE
Existence of GAE SDK prevents use of GCE credentials

### ISSUE THREAD

**Issue by pcostell** [google/oauth2client#205]
This is a problem if you are using something like remote API (or just have the app engine SDK in your python path) while running on GCE. You are able to import `google.appengine`, but you aren't running inside of appengine.

I think it may just be a matter of changing this line: https://github.com/google/oauth2client/blob/58f1c56e992851040d1ce3a3cf29d1b1c59e2834/oauth2client/client.py#L1006 to be willing to set the GCE environment even if the GAE SDK is on the python path.

**Comment by dhermes** [comment]
@pcostell If running the remote API, all the App Engine APIs will work (remotely).

I'm not sure how I feel about this. If users know they want GCE credentials, the fastest way will always be

```python
from oauth2client.gce import AppAssertionCredentials
credentials = AppAssertionCredentials([])
```

The Google Default Credentials (implicit) way requires an HTTP request to the metadata server, which is an unnecessary overhead.

**Comment by pcostell** [comment]
Hey Danny -- I believe it depends on how you get the credentials to use for remote API. In particular, I'd like the user to be able to use GCE credentials if it is running on GCE, but use gcloud credentials if running locally. It seems this is what get_application_default is designed for.

More specifically, I want to support users running `ndb` on top of gcloud/Cloud Datastore. In order to support this with application defaults, they need to not assume they are in App Engine just because they see the App Engine SDK.

**Comment by dhermes** [comment]
Yeah I'm totally with you on seeing the App Engine SDK. I'm curious how common it is?

The only reason I blanch here is because on GCE

```python
client.GoogleCredentials.get_application_default()
```

already takes longer than it should and addressing this use-case would require checking for an exception. (If the App Engine imports work, would need to check that the modules don't work by executing them).

The reason we defer the GCE check until the end is because of that HTTP request. Timing on my local machine

```
from gcloud._helpers import _compute_engine_id
print _compute_engine_id()
```

the average is **0.195 seconds** (**0.085** on GCE) while

```python
from oauth2client.client import _detect_gce_environment
print _detect_gce_environment()
```

the average is **1.042 seconds** (**0.079** on GCE, seems to be same as other) .

----

I'm sure there is a way to do it, I just wanted to let you know how we've made the decisions leading up to this.

**Comment by dhermes** [comment]
@pcostell WDYT of this as a check for live App Engine vs. just the SDK being present:
http://stackoverflow.com/questions/1916579/in-python-how-can-i-test-if-im-in-google-app-engine-sdk

**Comment by pcostell** [comment]
That seems reasonable -- From my reading of the Java application defaults, it thinks it is in GAE if It has the App Engine SDK and SERVER_SOFTWARE is set. Maybe we can just set `has_gae_sdk = 'SERVER_SOFTWARE' in os.environ` [here](https://github.com/google/oauth2client/blob/58f1c56e992851040d1ce3a3cf29d1b1c59e2834/oauth2client/client.py#L996)

Basically only assume that we are in App Engine if it has the SDK **and** the environment variable is set.

**Comment by dhermes** [comment]
Yup. That would allow us to continue the hierarchy of `GAE -> Files -> GCE` (and avoid the performance hit). Do you think it's worth distinguishing between production (`Google App Engine/X.Y.Z`) and the dev server (`Development/X.Y`)?

----

Also, thanks for helping me forcing me to time the metadata server failures and surface the 0.8 second penalty in `oauth2client` (that we don't have in `gcloud-python` with raw `httplib`).

**Comment by pcostell** [comment]
Distinguishing is probably worthwhile. In particular, I don't think GAE local development servers care what oauth credentials you use. Although I don't know if we would do anything differently (since the local one won't bother trying to validate, so invalid credentials work fine). 

Ya, that's a rough penalty. Good thing we cache the environment :-)

**Comment by anthmgoogle** [comment]
I agree with the plan to keep being able to probe for files or GCE if the GAE is loadable but the settings indicate you are not in the actual runtime. We hit an analog of this problem in the Java implementation and fixed already in a simlar way, by making an explicit check in addition to type loading. For people that have code targetting multiple environments it is not crazy to have GAE components that get moved around with code that runs in non-GAE scenarios.

The failure case timing of the GCE is a known issue that has been debated much elsewhere. In the short term it can be mitigated by ensuring that this is only a failure case. There is an a way we can stop the 1s delay by launching a second thread to do the IP and DNS checks in parallel but it has not been implemented yet.
