### ISSUE TITLE
Implement Decorator 3LO pattern for Bottle

### ISSUE THREAD

**Issue by anthmgoogle** [google/oauth2client#225]
The OAuth2Decorator pattern has been implemented for the WebApp2Framework. See the class OAuth2Decorator here:
https://github.com/google/oauth2client/blob/master/oauth2client/appengine.py

This pattern if very effective for usability of 3LO and should be extended to other frameworks. This item tracks implementing this pattern for Bottle.

**Comment by jonparrott** [comment]
There is not sufficient demand to add this feature. I'm closing this issue, but open to having an external contributor do this.
