### ISSUE TITLE
Credentials should keep track of which scopes are authorized

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#228]
This will allow us to support [incremental auth](https://developers.google.com/+/web/api/rest/oauth#incremental-auth).

I propose:

1. We add a new property ``scopes`` to ``OAuth2Credentials``.
2. We add a new function ``has_scopes`` to ``OAuth2Credentials`` that determines if the provided scopes are a subset of the authorized scopes.
3. We modify ``OAuth2WebFlow`` to store the scopes when constructing the credentials.
4. We add a function ``refresh_scopes`` (or similar) to ``OAuth2Credentials`` that can get the canonical list of scopes from the [tokeninfo endpoint](https://www.googleapis.com/oauth2/v2/tokeninfo).

I'm willing to submit the PR for this, just want to validate my approach.

@anthmgoogle

**Comment by dhermes** [comment]
:+1:

**Comment by anthmgoogle** [comment]
This plan sounds good to me.
