### ISSUE TITLE
faulty requirements pyasn1_modules

### ISSUE THREAD

**Issue by benoitpointet** [google/oauth2client#229]
Hey there,

I'm trying to `conda build oauth2client` but it doesn't work since the requirements in `oauth2client/setup.py` specifies `pyasn1_modules` while on pypi etco the module is known as `pyasn1-modules` (dash and not underscore).
> Error: No packages found in current osx-64 channels matching: pyasn1_modules >=0.0.5

No idea how to solve it?

**Comment by dhermes** [comment]
Thanks. We've never noticed becaused `pip` resolves it with no issues.

Here is the PyPI project:
https://pypi.python.org/pypi/pyasn1-modules

**Comment by benoitpointet** [comment]
Thanks, I could bypass the thing by modifying the conda recipe to build towards the underscore variant.

**Comment by dhermes** [comment]
No need to close, it's easy for us to change, I was just trying to figure out why we had never noticed.
