### ISSUE TITLE
Remove gh-pages (defer to readthedocs.org)

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#240]
Current gh-pages branch is serving at, but it doesn't need to be: http://google.github.io/oauth2client/

We could put a redirect there to go to readthedocs.org

Also, I was under the impression that `gh-pages` was automatically updated by Travis, but it turns out that it was a manual process, so the docs are out of date.

From [`gh-pages` log][1]  it looks like @craigcitro was doing it by hand, with July 8 the [most recent][2].

PS See #237 for context.

[1]: https://github.com/google/oauth2client/commits/gh-pages
[2]: https://github.com/google/oauth2client/commit/8efa3f76893f8bc381fd96ad283f885a97d2176d

**Comment by craigcitro** [comment]
+1 on moving to readthedocs -- i was going to, but never got around to it. once you do, i fully intend to steal that code for other repos.

**Comment by dhermes** [comment]
It's already done.

**Comment by dhermes** [comment]
Should also note that `tox -e docs` should fail Travis builds if newly generated sources (generated by `sphinx-apidoc`) are not committed in the repo. For example #234.
