### ISSUE TITLE
Make Sphinx understand Google docstring style

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#241]
Currently, certain things don't get build as expected:
![screen_shot_008](https://cloud.githubusercontent.com/assets/520669/9141722/a85dbf54-3cef-11e5-9776-2973039eab67.png)

The other option is just to convert the docstrings to Sphinx/ReST style (maybe could go nicely with #137).

**Comment by nathanielmanistaatgoogle** [comment]
The right thing to do here is for our code to conform to whatever the Python-language-wide accepted standard is rather than teach the standard tools to understand our code. :-)

**Comment by dhermes** [comment]
I don't know if Sphinx is "Python-language-wide accepted", but python.org is built with it, so that's good.

Also, Google style docstrings are pretty well known, so there may be a Sphinx plug-in. I should've made it clear that no code should be written / kittens harmed in the resolving of this issue.

**Comment by dhermes** [comment]
And here's your sign: https://pypi.python.org/pypi/sphinxcontrib-napoleon

**Comment by dhermes** [comment]
Even better it's already in `docs/conf.py`: https://github.com/google/oauth2client/blob/62b7f26d5852100221f59a88d6bcf2da6e218fc9/docs/conf.py#L21

Somehow it's missing that image I posted though.

**Comment by dhermes** [comment]
Culprit, `Exceptions` is not one of the accepted section headers. Should be `Raises`.

From the napolean docs:

![screen_shot_009](https://cloud.githubusercontent.com/assets/520669/9142538/2b969cc4-3cf5-11e5-90ec-93a6d89f0bd8.png)

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle It seems the webhook to auto-build isn't set up.

When I view webhooks for a project I am an admin for, I see:

![screen_shot_010](https://cloud.githubusercontent.com/assets/520669/9143048/9e8f534e-3cf8-11e5-86e3-fcf946a2798d.png)

Can you check out

https://github.com/google/oauth2client/settings/hooks

and see if the hook is set up? If not, we'll need to figure out a way to do it (may involve you creating an account on readthedocs.org).

**Comment by dhermes** [comment]
FWIW I manually forced a rebuild and the rendering issue is [resolved][1]:

![screen_shot_011](https://cloud.githubusercontent.com/assets/520669/9143091/f8ce5468-3cf8-11e5-93db-d678d45c3719.png)

[1]: http://oauth2client.readthedocs.org/en/latest/source/oauth2client.html#oauth2client.client.AccessTokenCredentials

**Comment by nathanielmanistaatgoogle** [comment]
Your suspicion is correct; ReadTheDocs does not appear under "Services" at this time.

**Comment by dhermes** [comment]
(For postery:) Added easily via: https://read-the-docs.readthedocs.org/en/latest/webhooks.html
