### ISSUE TITLE
Suggested additional documentation at the head of flask_utils.py

### ISSUE THREAD

**Issue by bshaffer** [google/oauth2client#255]
It would be beneficial to add a section in the docs at the top of [`flask_utils.py`](https://github.com/google/oauth2client/blob/master/oauth2client/flask_util.py) explaining the blueprints  of `/oauth2authorize` and `/oauth2callback` ([here][1])

Something saying those routes are available via blueprints, how to use them (aka declaring an `authorize_callback` function, setting `scope`) and how to override them would be extremely helpful, as well as how to reference them in jinja ( i.e. `{{url_for('oauth2.authorize')}}`)

[1]: https://github.com/google/oauth2client/blob/487161239fc85d1e6c61addda08bd89456bbbf8d/oauth2client/flask_util.py#L234

**Comment by bshaffer** [comment]
cc-ing @jonparrott as I do not have permission to assign

**Comment by jonparrott** [comment]
Acknowledged. Will tackle tomorrow.
