### ISSUE TITLE
test_appengine.py should get run on Travis

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#270]
[Current][1] approach is:

```
commands = nosetests --ignore-files=test_appengine\.py {posargs}
```

----

We could just make a custom `tox` environ for that test only and run

```
nosetests test_appengine\.py {posargs}
```

and then on Travis use the caching feature to make sure we don't grab the GAE SDK too often. Though I'd image enough other people on Travis grab the SDK that they have it cached locally anyway. (We're already pulling it down to build `docs`.)

[1]: https://github.com/google/oauth2client/blob/891c8649d8a1f4f435e8007287df6313c036ecad/tox.ini#L18

**Comment by jonparrott** [comment]
We recently did this for GoogleCloudPlatform/python-docs-samples. Our config files might be helpful: [.travis.yml](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.travis.yml) and [tox.ini](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tox.init).

**Comment by jonparrott** [comment]
Actually if you want to assign this to me I can do it.
