### ISSUE TITLE
Get flask_util to 100% code coverage

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#277]
See #212

**Comment by jonparrott** [comment]
I think the only thing missing from coverage is the import check at the topic. Unsure on how to test that - any recommendations?

**Comment by dhermes** [comment]
Looking at the output from #212:

```
oauth2client.flask_util          170      9     42      7    92%   180-181, 383-384, 387, 394-397
```

The lines `180-181` are

```python
except ImportError:
    raise ImportError('The flask utilities require flask 0.9 or newer.')
```

which you could [mark][1] with `pragma: NO COVER`.

The rest are valid code paths that need to be traversed.

[1]: https://github.com/google/oauth2client/blob/b821f6ee88f472f8523525b049c42583d9182faa/.coveragerc#L5

**Comment by jonparrott** [comment]
Gotcha. Will do.
