### ISSUE TITLE
Incorporate `test_appengine.py` into coverage report

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#286]
See #212

**Comment by jonparrott** [comment]
Why are we using nosexcover instead of normal coverage?

**Comment by dhermes** [comment]
Not sure I know the difference `nosexcover` was added in 7dff2c14a0db6a909c8536b31208b3579d1eeb70 by @craigcitro and likely it was just copy-pasta from our `tox.ini` for `gcloud-python`.

@tseaver why do we use `nosexcover` instead of just `nosecover`?

**Comment by jonparrott** [comment]
Might have been before coveralls had direct support for coverage's output.

**Comment by dhermes** [comment]
@tseaver #287 is ready to go but we are holding off to hear from you if there is a reason we use `nosexcover` instead of just `nosecover`

**Comment by tseaver** [comment]
`nosexcover` was likely copied in from projects which use Jenkins for CI:  it arranges to have a Cobertura-compatible `coverage.xml` generated, FBO the Jenkins coverage visualization.

**Comment by dhermes** [comment]
SGTM. @jonparrott we are a go then
