### ISSUE TITLE
broken encoding with python 3.4 (fix inside)

### ISSUE THREAD

**Issue by richiverse** [google/oauth2client#294]
context:
```bash
.../site-packages/oauth2client/client.py", line 1515, in __init__
self.private_key = base64.b64encode(private_key) 
File ".../venv/lib/python3.4/base64.py", line 62, in b64encode
encoded = binascii.b2a_base64(s)[:-1]
TypeError: 'str' does not support the buffer interface
```

Changing line 1515 in oauth2client/client.py from this:
```python
self.private_key = base64.b64encode(private_key)
```
to this:
```python
self.private_key = base64.b64encode(private_key.encode('ascii'))
```
fixed my issue.

reference:
http://stackoverflow.com/questions/27160352/when-convert-to-base-64-typeerror-str-does-not-support-the-buffer-interface

**Comment by dhermes** [comment]
Can you do a `pip3 show oauth2client` to determine what version you have?

If this hasn't already been resolved in a release, it probably will be in `1.5.0` (#292)

**Comment by richiverse** [comment]
```shell
---
Metadata-Version: 1.1
Name: oauth2client
Version: 1.4.11
Summary: OAuth 2.0 client library
Home-page: http://github.com/google/oauth2client/
Author: Google Inc.
Author-email: UNKNOWN
License: Apache 2.0
Location: /home/rich/Projects/github/payrollscripts/venv/lib/python3.4/site-packages
Requires: httplib2, pyasn1, pyasn1-modules, rsa, six
```

**Comment by dhermes** [comment]
Thanks.

The latest version is 1.4.12: https://pypi.python.org/pypi/oauth2client/1.4.12

If you upgrade does the problem persist?

**Comment by dhermes** [comment]
Found the line in the 1.4.11 release: https://github.com/google/oauth2client/blob/c61bdf4565782db82172b450284fb969150dd32b/oauth2client/client.py#L1515

**Comment by dhermes** [comment]
Traced the line to the current head, still an "issue": https://github.com/google/oauth2client/blob/b66838e48da243a7fefa7275044f6b5833ec1476/oauth2client/client.py#L1632

@richiverse For now, use bytes, but your suggestion should make it into the codebase, so thanks!

Easiest way (if you're reading from a file) is opening in read binary (`'rb'`) mode.
