### ISSUE TITLE
Logo is out-of-date / obsolete

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#296]
Due to http://googleblog.blogspot.com/2015/09/google-update.html the images are out-of-date:
https://github.com/google/oauth2client/blob/19abb4d0fb3a49602e23f654cde284fb5b9c3ec3/docs/_static/google_logo.png
https://github.com/google/oauth2client/blob/19abb4d0fb3a49602e23f654cde284fb5b9c3ec3/docs/_static/favicon.ico

**Comment by royalharsh** [comment]
Can I work on this one ? Just as a starting point :smile:

**Comment by royalharsh** [comment]
https://github.com/google/oauth2client/pull/334

**Comment by dhermes** [comment]
Nice idea @royalharsh!

**Comment by royalharsh** [comment]
:smile:

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the contribution!
