### ISSUE TITLE
OAuth2Credentials access token refresh failures swallow HTTP status

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#309]
Refresh token exceptions raised by [OAuth2Credentials._do_refresh_request](https://github.com/google/oauth2client/blob/621c8e3904da0964901440f048717e19c656bdd2/oauth2client/client.py#L888) include only the error message and not the HTTP response code that cause the error.

This is fine if the [http_request](https://github.com/google/oauth2client/blob/621c8e3904da0964901440f048717e19c656bdd2/oauth2client/client.py#L867) supports automatic retrying of HTTP 5xx codes, but there are cases where retries cannot be handled at this layer.  For example, during session operations like resumable downloads and uploads, repeating the original request is not the correct retry behavior.

For errors that have HTTP status, I'd like to include the response code so that the caller can make the correct decision.  To that end, I propose creating a subclass of AccessTokenRefreshError that includes the HTTP status when one is available.

**Comment by dhermes** [comment]
:+1: 

@thobrla, I'm hoping at some point to use a `__call__`-able `AuthorizedHttp` class instead of monkey patching `httplib2.Http` instances. This way library devs (like you and I) can extend this class and handle special cases just like this issue refers to.
