### ISSUE TITLE
flask_util: Custom Scopes Causes Redirect Loops

### ISSUE THREAD

**Issue by waprin** [google/oauth2client#320]
I am experiencing redirect loops when passing additional scopes to the decorator that is not part of the `DEFAULT_SCOPES`. You can see a sample that reproduces it below.

I think this is because the flow is recreated in the callback but with just the default scopes, which causes the credentials saved to not have the additional scopes, which means the decorator's predicate is never satisfied.

@jonparrott 

```python
from oauth2client.flask_util import UserOAuth2

app.config['SECRET_KEY'] = 'your-secret-key'
app.config['GOOGLE_OAUTH2_CLIENT_ID'] = 'client-id'
app.config['GOOGLE_OAUTH2_CLIENT_SECRET'] = 'client-secret'
oauth2 = UserOAuth2(app)


@app.route('/hello/')
@oauth2.required
def hello():
    return 'Hello World'

@app.route('/calendar')
@oauth2.required(scopes=['https://www.googleapis.com/auth/calendar'])
def calendar():
    return 'got calendar'
```

**Comment by dhermes** [comment]
Sad face. @jonparrott This "justifies" our discussion about the naming of the additional scopes.

**Comment by waprin** [comment]
I think this can be fixed pretty easily just by adding scopes to the state object passed, then pulling it back out in the callback.

**Comment by jonparrott** [comment]
Arg. I'll look into this. My worry is that adding a bunch of additional scopes and passing them via the `state` parameter will cause some browsers to choke at the super long URI. Storing it in the session is also iffy because a user could technically start two separate oauth2 flows on the same site.

**Comment by jonparrott** [comment]
@dhermes you should be able to assign this to me.

**Comment by waprin** [comment]
There is another bug related to this one that's only uncovered once this one is fixed. Specifically, there is a line in the decorator:

    if scopes and not self.credentials.has_scopes(scopes):

That checks if we need incremental auth. But once the above bug is fixed, what happens is someone can auth with a specified scope (say, Google Drive), then they only have scope for Drive, but then they use the bare bones decorator with the default scopes, so scopes is None so incremental auth isn't done, even though the credentials only has the Drive scope and not the default scopes. In Django I changed it to:
    
    if (scopes and not credentials.has_scopes(scopes)) or \
                    (not scopes and not credentials.has_scopes(DEFAULT_SCOPES)):

But maybe there is a more elegant way to express what you want.

**Comment by jonparrott** [comment]
Noted, though, though that situation should only arise when the developer changes the base scopes and the user has credentials that were created before the change. Good edge case those, and easy fix.
