### ISSUE TITLE
Samples for App Engine don't work

### ISSUE THREAD

**Issue by MeLight** [google/oauth2client#321]
Sets dependencies hell loose. First I needed six, and then:
```
    from oauth2client.anyjson import simplejson
    ImportError: No module named anyjson
```
There's no `anyjson` in the folder of `oauth2client` I've cloned. Please advise.

**Comment by nathanielmanistaatgoogle** [comment]
Thank you for the report, and sorry for the trouble. In what file are you seeing the line `from oauth2client.anyjson import simplejson`?

**Comment by MeLight** [comment]
My bad, it was occurring because of googleapiclient import. So apologies, and I'm closing this,

**Comment by nathanielmanistaatgoogle** [comment]
Okay, but I also happen to be a maintainer of https://github.com/google/google-api-python-client so if there's a problem there I'm still keen to know about it.
