### ISSUE TITLE
Create oauth2client.contrib package for non-core modules.

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#326]
Similar to urllib3's contrib [[1](https://github.com/shazow/urllib3/tree/master/urllib3/contrib)] [[2](http://urllib3.readthedocs.org/en/latest/contrib.html)], we will move ``appengine``, ``flask_util``, ``django_orm``, and in incoming ``django_util`` into ``oauth2client.contrib``. This cleanly separates these framework/environment-specific modules away from the core library, and will make it easier to separate into a separate pypi package later if needed.

See #319 for initial discussion.

Should we have import aliases for backwards compatibility or should we explicitly break imports with this change?

**Comment by nathanielmanistaatgoogle** [comment]
If we have import aliases let's keep them no later than a 1.6.0 or later release.

**Comment by jonparrott** [comment]
SGTM, we can also put a deprecation warning in there.

**Comment by dhermes** [comment]
@jonparrott FWIW I had in mind something like a well-defined surface for packages to interact with and just endorse / list other plugins as PyPI packages (not as native part of `oauth2client` source code)

**Comment by jonparrott** [comment]
Not sure I follow, but imo this is a good starting point if we do want to spin these off separately.

**Comment by dhermes** [comment]
@jonparrott Sorry, code is easier than words sometimes:

```bash
$ pip install oauthclient
$ pip install oauthclient-flask-plugin
```

then

```python
from oauth2client import kitchen_sink
from flask_oauth2client import FancyFlow
```

----

Could "allow" `oauth2client` to be a namespace package, but I think that would muddle the lines between endorsed plugins and ones we've never heard of. I.E. if `oauth2client` was a namespace package then someone could have

```python
from oauth2client.endorsed_plugin import safe_gun_that_totally_wont_shoot_foot
from oauth2client.who_am_eye import mystery_meat
```

**Comment by jonparrott** [comment]
I see, okay, we want the same thing, I'm just doing baby steps.

First step is:

```
$ pip install oauth2client
```

```
from oauth2client.contrib import flask_util
```

Second step, if we want:

```
$ pip install oauth2client oauth2client-flask
```

```
from oauth2client.contrib import flask_util
```

---

``oauth2client.contrib`` would be the namespace package, not ``oauth2client``.

**Comment by dhermes** [comment]
That seems more reasonable in terms of `oauth2client` endorsement of something's validity. Not sure if it's possible to make a sub-package (`oauth2client.contrib`) be a namespace package unless the parent (`oauth2client`) is.

We shall see.

**Comment by jonparrott** [comment]
If we can't, we can steal a page from flask's playbook and use a [redirect package](http://flask.pocoo.org/docs/0.10/extensiondev/#extension-import-transition).
