### ISSUE TITLE
Support of cryptography lib

### ISSUE THREAD

**Issue by pmellier** [google/oauth2client#333]
Hi,
Have you targeted to support other python cryptography libs like https://cryptography.io or http://nacl.cr.yp.to/ ? as suggested in https://github.com/dlitz/pycrypto/issues/158.
Best regards,
Pierre

**Comment by dhermes** [comment]
@pmellier pyOpenSSL (which uses `cryptography`) and `rsa` (with helpers like `pyasn1_modules`) are also supported in our library.

Let us know if this doesn't cover your concern and we can re-open
