### ISSUE TITLE
storage class does not throw exceptions or errors when creds file is missing

### ISSUE THREAD

**Issue by pprmint** [google/oauth2client#338]
Calling `storage = Storage('a_credentials_file')` does not give any errors or warnings when the file passed does not exist. This should be helpful in debugging.

**Comment by pferate** [comment]
@jonparrott I'm assuming that this is referring to `oauth2client.file.Storage`.

In the work flow, the storage file doesn't need to exist initially, credentials could be put in after the storage object is initialized.  It would make more sense to warn when attempting to `get()` when no file exists, rather than on initialization.

Right now, if you use `get()` and the file doesn't exist, it just returns `None`; if the file exists, but is a symbolic link, a `CredentialsFileSymbolicLinkError` exception is raised.  Should we keep the current functionality and log a warning, or should we raise an exception.?

```python
s = file.Storage(FILENAME)

# No file, return None
credentials = s.get()
assert credentials is None

# File exists, return credentials
test_credentials = self._create_test_credentials()
s.put(test_credentials)
credentials = s.get()
assert credentials is not None
assert credentials == test_credentials

# File is symbolic link, raise exception
os.symlink(FILENAME, SYMFILENAME)
s = file.Storage(SYMFILENAME)
with self.assertRaises(file.CredentialsFileSymbolicLinkError):
    s.get()
```

**Comment by pprmint** [comment]
@pferate I think raising an exception makes more sense. Most developers expect to see a thrown error when something goes wrong. I relayed this information before to some of my friends using the library and as we discussed, we think having an exception raised is better.

Thoughts?

**Comment by jonparrott** [comment]
So is this actually an error state? If the file doesn't exist, what happens if you do `put()`? Does the file get created? If so, I think this is a non-issue.

**Comment by pferate** [comment]
The file gets created when you `put()`, but I think an exception should be raised if you `get()` and there is no file.

**Comment by jonparrott** [comment]
Hmm, I'm still not convinced. It's not an error state. `get()` behaves the same if there is no file or if the file is empty.

@nathanielmanistaatgoogle thoughts?

I'm also not sure how much this is even used and if it's worth modifying the behavior of it significantly.

**Comment by pferate** [comment]
If we don't change the behavior, we could still issue a `warnings.warn()` if the file is missing or empty.

Also, I see that `file.Storage` will raise an exception if the given file is a symbolic link; I'm curious as to the reason for that.  Reading the contents of a regular file or a symbolically linked file is the same, right?

**Comment by jonparrott** [comment]
> I'm curious as to the reason for that.

Your guess is as good as mine.

> we could still issue a warnings.warn() if the file is missing or empty.

I could concede to that.

**Comment by nathanielmanistaatgoogle** [comment]
(@nathanielmanistaatgoogle looks for guidance at [the specification of the `get` method](https://github.com/google/oauth2client/blob/ae73312942d3cf0e98f097dfbb40f136c2a7c463/oauth2client/client.py#L400) and finding none, [curses inheritance](https://www.youtube.com/watch?v=3MNVP9-hglc) once more.)

I agree that nothing should be done about the file not existing when instantiating the object.

I'd be fine with `get` called when the file does not exist either returning `None` or raising an exception. Neither one is legal today, so we'd have to adjust the specification of `get` to describe which one we chose and ensure that all the `Storage` subclasses implement it correctly. A `warnings.warn` would be totally fine and doesn't conflict with either choice of returning `None` or raising an exception.
