### ISSUE TITLE
tox config is broken

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#339]
Failures noticed in #336 and #337.

From http://tox.readthedocs.org/en/latest/changelog.html it looks like the 2.2.1 release notes explain the failure

> fix bug where `{envdir}` substitution could not be used in setenv if that env value is then used in `{basepython}`. Thanks Florian Bruhin.

Seems https://bitbucket.org/hpk42/tox/pull-requests/169/tries-to-fix-99/diff is the PR that fixed something but broke us

**Comment by dhermes** [comment]
I should add that the offending line is

https://github.com/google/oauth2client/blob/311a53fbcae550526a74057f27cb9df73a0af009/tox.ini#L86-L87

and the issue is a circular reference between `setenv` and the use of `env:KEY:DEFAULT`.

**Comment by dhermes** [comment]
@jonparrott Any idea on how to fix this? (I did the "cowardly" thing and downgraded `tox` temporarily.)

**Comment by dhermes** [comment]
I accidentally stumbled on something which I think/hope will solve this:
https://github.com/GoogleCloudPlatform/gcloud-python/pull/1237

**Comment by jonparrott** [comment]
All I've got is to just wait. We ended up pinning tox in [python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/141) as well.

Consider tox isn't a *direct* dependency of library, pinning it for a while doesn't seem too offensive.

**Comment by dhermes** [comment]
I don't think waiting will work. I think we are permanently broken. I tried making the change suggested by my other PR and get a circular dependency sort of error:

```python
...
  File "/usr/local/lib/python2.7/dist-packages/tox/config.py", line 959, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File "/usr/local/lib/python2.7/dist-packages/tox/config.py", line 944, in _substitute_from_other_section
    (section, item), self._subststack))
ValueError: ('testenv', 'gae_pythonpath') already in [('testenv:gae', 'setenv'), ('testenv', 'gae_pythonpath'), ('testenv:gae', 'setenv')]
```

It seems like it is getting a self-reference and it will "always" be impossible for `setenv` and `env` to coexist.

**Comment by jonparrott** [comment]
@waprin who's more involved in the testing side than me.

**Comment by dhermes** [comment]
@jonparrott By forcing me to articulate that 

> it will "always" be impossible for `setenv` and `env` to coexist.

I realized we could just ditch `setenv` in `testenv:gae`. w00t!

**Comment by dhermes** [comment]
Haha JK:

```
gae runtests: commands[0] | PYTHONPATH= nosetests --with-gae --gae-application=tests/data --logging-level=INFO tests/test_appengine.py
ERROR: InvocationError: could not find executable 'PYTHONPATH='
```

**Comment by waprin** [comment]
It's a bug a lot of people are experiencing, people already have PRs to fix it, they are just in the process of getting vetted/merged:

https://bitbucket.org/hpk42/tox/issues/285/tox-220-breaks-some-toxini-config-files

**Comment by dhermes** [comment]
w00t. Thanks @waprin

**Comment by dhermes** [comment]
This is no longer broken right?
