### ISSUE TITLE
not clear for how long is a token valid if not refreshed

### ISSUE THREAD

**Issue by FlorinAndrei** [google/oauth2client#342]
I've a Python script that edits a Google Docs spreadsheet using the gspread module. The script runs once every day.

The Oauth token is stored locally in a file. Every time the script runs, the JSON file with the Oauth token is refreshed. Here's a relevant code snippet:

```
from oauth2client.file import Storage
import gspread
import settings

storage = Storage(settings.CREDENTIALS_PATH)
creds = storage.get()
http = httplib2.Http()
http = creds.refresh(http)
http = httplib2.Http()
http = creds.authorize(http)
creds = http.request.credentials
storage.put(creds)
client = gspread.authorize(creds)
sheet = client.open_by_key(settings.SPREADSHEET_ID)
```

But if I look at the Oauth token, the time stamps and durations are clearly in the past:

```
    "token_expiry": "2015-11-19T11:24:26Z",
    "token_response": {
        "expires_in": 3600,
```

The token_expiry is in the past. The expires_in is only 1 hour. But when the cron job runs again tonight (in a few hours from now), it will authenticate successfully, as always.

What exactly controls the expiration time of the token?

The reason I'm asking is this: I want to grab a copy of the existing token and store it in a password vault. Then, when creating a new instance, I want to deploy the token from the vault and have the script running on the new instance. But let's say I've kept the token in the vault for a few months - would it not be expired by then?

Generating the token initially is pretty much a manual process. I need to bypass the manual steps and have an automated process for deploying the script to new instances. Hence the concern for how long I could store a token template before it expires and cannot be renewed again.

**Comment by dhermes** [comment]
You have an access token and a refresh token. The expiry is for the access token. However, your refresh token allows you to get a brand new access token and this library does that behind the scenes every time you get a 401 response (meaning your access token is no longer valid).

Your refresh token never expires. So putting it in a vault for a couple months won't have any effect.

If you want to know more you should read up on OAuth 2.0: https://developers.google.com/identity/protocols/OAuth2

**Comment by FlorinAndrei** [comment]
Awesome, thank you @dhermes , this is very helpful.

**Comment by dhermes** [comment]
Sure thing! Many people have spent lots of time trying to figure out OAuth 2.0. We hope this library makes it so that for most, OAuth 2.0 "just works".
