### ISSUE TITLE
Can't call SignedJwtAssertionCredentials.apply() without refresh()

### ISSUE THREAD

**Issue by dobesv** [google/oauth2client#343]
Currently if you authenticate an `Http` instance using `SignedJwtAssertionCredentials.authorize` it replaces the `request` method on the `http` instance with an implementation that adds the appropriate authorization header.  In that replacement, if there is no `access_token` set already, it uses `_refresh` to get one.  However, if you try to use `apply` to update headers without this `access_token` previously being set.

In the `google-api-python-client` I found that if you are trying to do a batch request, it uses `apply` to calculate the authorization header, and if `access_token` is `None` then it blows up, meaning you can't use the batch feature unless you have previously calculated the `access_token`.

See https://github.com/google/google-api-python-client/issues/137

It's not clear to me whether this is a problem with `google-api-python-client` or with `oauth2client`.  Perhaps the api client could replicate the `access_token is None` check and call `refresh()`.  However, for 
`SignedJwtAssertionCredentials` no http connection is needed to create credentials, so `SignedJwtAssertionCredentials` could easily override `apply` to set the `access_token` if it isn't already set which would fix it not just for the API client but others who come along and want to use `SignedJwtAssertionCredentials` without attaching it to an `Http` instance.

Food for thought.

**Comment by dobesv** [comment]
Steps to reproduce (using google-api-client):

```
import json
creds = json.load(open('dev/etc/google-service-accounts/enterprise.json'))
from httplib2 import Http
from oauth2client.client import SignedJwtAssertionCredentials

credentials = SignedJwtAssertionCredentials(
            creds['client_email'],
            creds['private_key'],
            'https://www.googleapis.com/auth/androidenterprise'
        )
http = credentials.authorize(Http())
from googleapiclient.discovery import build
service = build('androidenterprise', 'v1', http=http)
batch = service.new_batch_http_request()
batch.add(service.installs().update(userId='1', enterpriseId='2', deviceId='3', installId='4', body={}))
batch.add(service.installs().update(userId='2', enterpriseId='2', deviceId='4', installId='4', body={}))
batch.add(service.installs().update(userId='3', enterpriseId='2', deviceId='5', installId='4', body={}))
batch.execute()
```

Yields

```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/googleapiclient/http.py", line 1306, in execute
    self._execute(http, self._order, self._requests)
  File "build/bdist.linux-x86_64/egg/googleapiclient/http.py", line 1230, in _execute
    body = self._serialize_request(request)
  File "build/bdist.linux-x86_64/egg/googleapiclient/http.py", line 1101, in _serialize_request
    request.http.request.credentials.apply(headers)
  File "build/bdist.linux-x86_64/egg/oauth2client/client.py", line 643, in apply
    headers['Authorization'] = 'Bearer ' + self.access_token
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by ericbuehl** [comment]
I'm seeing the same issue (still?).  In my case I'm attempting to use GCE-provided service credentials.

```
>>> from oauth2client.client import GoogleCredentials
>>> c = GoogleCredentials.get_application_default()
>>> c.apply({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/local/lib/python2.7/site-packages/oauth2client/client.py", line 675, in apply
    headers['Authorization'] = 'Bearer ' + self.access_token
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I am able to make this work, however, if I use `c.get_access_token().access_token` and inject the Authorization header myself.

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle how would you feel about making `apply()` refresh the access token? At the very least, `apply()` should raise a useful exception, yeah?

**Comment by foodini** [comment]
It looks like I'm running into the same issue. @ericbuehl, can you recommend a way to apply your workaround?
`credentials = SignedJwtAssertionCredentials(STACKDRIVER_AUTH_GOOGLE_CLIENT_EMAIL,
                                            STACKDRIVER_AUTH_GOOGLE_PRIVATE_KEY,
                                            scope='https://www.googleapis.com/auth/trace.append')
#https://github.com/google/oauth2client/issues/343
http = httplib2.Http()
credentials = credentials.authorize(http)
service = build('cloudtrace', 'v1', http=http) # from googleapiclient.discovery
batch = service.new_batch_http_request()
batch.add(service.projects().patchTraces(body='{}', projectId=STACKDRIVER_AUTH_GOOGLE_PROJECT_ID))`

Of course, I'm getting:
`TypeError: cannot concatenate 'str' and 'NoneType' objects
`

**Comment by ericbuehl** [comment]
@foodini you may be able to explicitly call credentials.refresh(Http()) before calling authorize().  In my case, get_access_token() is doing this for me: https://github.com/google/oauth2client/blob/e54e28939cf985e4d25ef34f96162abd3ab65002/oauth2client/client.py#L776

**Comment by nathanielmanistaatgoogle** [comment]
@jonparrott: the specification of `apply` is ["Add the authorization to the headers."](https://github.com/google/oauth2client/blob/ac4385c9cc2d9094e1ab29748ed6cc62aa1b70a0/oauth2client/client.py#L247). If the `Credentials` object on which `apply` is called does not have the authorization but does have _the means to obtain the authorization_, then of course it should avail itself of those means, secure the authorization, and apply it to the headers. Is there some subtlety I'm missing?

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle just wanted a sanity check. I'll think on this and see what should be done.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
