### ISSUE TITLE
SQLAlchemy Storage

### ISSUE THREAD

**Issue by miedzinski** [google/oauth2client#345]
https://github.com/google/oauth2client/issues/319

I've started working on SQLAlchemy Storage class, based on AppEngine and Django ones. There is already functional class, without unit tests. I am not sure whether more docs than docstrings are needed.

Here is the fork:
https://github.com/miedzinski/oauth2client/tree/sqlalchemy-storage

**Comment by jonparrott** [comment]
We have two efforts in place to make this easier:

1. #326 to add `oauth2client.contrib` as a place to keep these items.
2. #319 to add a few storage classes for web applications.

I'm waiting on #344 to be reviewed and merged before creating the contrib package.

**Comment by miedzinski** [comment]
Sure, I don't see moving existing class to another file a problem. When I'll be ready to submit PR (a.k.a. write tests), I'll check if `contrib` package exists - and then move class to this file.
Just wanted to tell people that I'm already working on this class, because it's needed in my application.

**Comment by jonparrott** [comment]
No worries. I think it's very useful, especially if you/we can get it to work in conjunction with `flask_util`.

**Comment by miedzinski** [comment]
Well, my application uses Flask as well, but `flask_util` needs changes in order to support storage like this (or Django ORM). There should be a way to pass arguments to Storage constructor.
Anyway, I'm open to ideas regarding design of current `oauth2client.sqlalchemy.storage` design. Currently the user passes a session to it and has to flush/commit manually (assuming engine's auto-commit/flush is disabled).

**Comment by anthonymayer** [comment]
Any updates on this? I'd like to be able to use this and it'd be great if it were just part of the library. Thanks.

**Comment by jonparrott** [comment]
contrib is now available and I'm happy to review new modules to be added there.

**Comment by miedzinski** [comment]
I have rebased my branch to master, but it is lacking some tests. Maybe we could merge it to some kind of dev branch? If not, I need few days to write them, but until them you can try using my fork.

**Comment by jonparrott** [comment]
We don't have a dev branch, so just send a PR from your fork when you're ready for review. We do have a strict 100% code coverage requirement.

**Comment by miedzinski** [comment]
@anthonymayer, good news! I have submitted #527.

**Comment by miedzinski** [comment]
@anthonymayer, good news again. PR was merged -- 267bbc59caad625b3905eec29c040f61aab3b4f0.
