### ISSUE TITLE
Move modules into contrib

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#352]
The following modules should be moved into contrib:

* `django_orm`
* `flask_util`
* `keyring_storage`
* `locked_file`
* `multistore_file`
* `appengine`

@nathanielmanistaatgoogle @dhermes I'll be sending a PR shortly for this, but I wanted to make sure you two were comfortable with the list.

**Comment by dhermes** [comment]
SGTM :+1:

**Comment by dhermes** [comment]
I'm not so sure about the name `contrib`. What are some other choices? `third_party`? `optional`? `ext`? `extensions`?

**Comment by jonparrott** [comment]
I'd be fine with `ext`, but I actually like the idea of "contrib" as a concept. The concept of a community-driven but project-sponsored set of modules is something I think could be very valuable. So long as we don't lose that, I'm fine with whatever we call it.

**Comment by nathanielmanistaatgoogle** [comment]
I like `contrib` well enough. `third_party` is inappropriate as that name implies that the code is homed somewhere else and merely replicated in our repository.

Plan sounds good to me too.
