### ISSUE TITLE
Weird wording in readme

### ISSUE THREAD

**Issue by vivekseth** [google/oauth2client#366]
The read me currently has the following text:  "To install, simply say"  (line 10)

Its a small thing, but i think it would be more appropriate to use something like; "To install, simply run the following command in your terminal"

**Comment by nathanielmanistaatgoogle** [comment]
Good point; want to open a pull request with better wording?

**Comment by vivekseth** [comment]
Corrected the issue you mentioned with my last pull request and made a new one here: https://github.com/google/oauth2client/pull/369

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the fix!
