### ISSUE TITLE
_ServiceAccountCredentials: public access to _kwargs?

### ISSUE THREAD

**Issue by midnightlynx** [google/oauth2client#367]
If one gets their service account credentials through a `GoogleCredentials` object's `get_application_default()` or `from_stream(filename)` methods, there's no way to add kwargs to the credential creation process.

In the docs, it states:
"If you have delegated domain-wide access to the service account and you want to impersonate a user account, specify the email address of the user account in the `sub` parameter when you create the Credentials object."

I can add the `sub` after the fact, by adding `{'sub': 'foo@bar.com'}` to the credentials object's `_kwargs` dictionary, but accessing private attributes is not a good practice.

`SignedJwtAssertionCredentials` has a public `self.kwargs`, but creating one of those from default credentials or from a json keyfile is non-trivial.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Probably worth incorporating this into the factory constructors.

**Comment by jc0n** [comment]
+1

**Comment by jonparrott** [comment]
Is this considered obsolete now that we have the `create_delegated` method?

**Comment by jc0n** [comment]
Somehow I missed that method. That works for me, thanks :)

**Comment by jonparrott** [comment]
We just recently added it. Will wait on @dhermes to confirm before closing.

**Comment by midnightlynx** [comment]
The new `create_delegated` method is working for me. Thanks!

**Comment by dhermes** [comment]
Obsolete in a way. I'd like to re-purpose this or file a new one saying we should just get rid of `kwargs` since `sub` is the only one used AFAIK. Though [there are][1] other useful claims like `nbf` (not before) and `jti` (JWT ID).

[1]: https://tools.ietf.org/html/rfc7519#section-4.1

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
