### ISSUE TITLE
errno.EACCES can propagate fatally outside of multistore_file

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#386]
Report from a Windows gsutil user:

```
Encountered a problem: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\
.gsutil\\credstore.lock'
```

My best guess is that it is occurring `locked_file.py` [here](https://github.com/google/oauth2client/blob/41eb75578f81876a53f1707cf1daf1eb89ddfc0b/oauth2client/contrib/locked_file.py#L291).

I suspect we need to add `errno.EACCES` to the list of exceptions handled in `multistore_file.py` [here](https://github.com/google/oauth2client/blob/41eb75578f81876a53f1707cf1daf1eb89ddfc0b/oauth2client/contrib/multistore_file.py#L286), since in theory we should be able to proceed by acquiring new credentials.

**Comment by jonparrott** [comment]
I don't presently have a windows machine to reproduce this on, but it should be straightforward to write a test to cover this.

I'm not overly familiar with this module, but I'm willing to make this change. However, I'm unable to do so until sometime next week. @thobrla if you send a PR between now and then I'm happy to be the first reviewer.

**Comment by thobrla** [comment]
Thanks - probably won't get to this for at least a few weeks, but I can provide a PR eventually.
