### ISSUE TITLE
Last release was in November

### ISSUE THREAD

**Issue by adongy** [google/oauth2client#402]
Hi!

Seeing the new changes for services accounts and json keyfiles, I was wondering when the next release would happen, as the latest one on PyPi is v1.5.2.

https://github.com/google/oauth2client/commit/3042ad2554d20a8c02c0714b58adcba7ec842d88

Thanks!
Anthony

**Comment by dhermes** [comment]
Hopefully soon (i.e. later this week). We were trying to get one out last Friday but it lapsed.

**Comment by adongy** [comment]
Alright, thanks!

**Comment by adongy** [comment]
Alright, thanks!

**Comment by adongy** [comment]
Alright, thanks!
