### ISSUE TITLE
Make sure release only happens in one Travis env.

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#407]
See:
https://travis-ci.org/google/oauth2client/builds/109681347

It seems every environment pushed the release which [caused the second, third, etc.][1] job to push to give an error:

```
...
HTTPError: 400 Client Error: A file named "oauth2client-2.0.0.tar.gz" already exists for  oauth2client-2.0.0. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi
running upload_docs
creating build
creating build/docs
...
```

Also there are two warnings that may be worth dealing with:

```
warning: sdist: standard file not found: should have one of README, README.rst, README.txt
running check
warning: check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too
```

[1]:

**Comment by Manoj-nathwani** [comment]
@dhermes any updates on how you fixed this? I'm having the same `400 Client Error: A file named...` issue :(

**Comment by dhermes** [comment]
The fix for us may be different for you. We have 8 (I think? Maybe 7 or 9) Travis envs that all try to upload it but we should only have one. The fix will just to make upload conditional on one env.
