### ISSUE TITLE
ServiceAccountCredentials should support directly passing in key file contents

### ISSUE THREAD

**Issue by allenpc** [google/oauth2client#412]
(breaking out my comment from #401 as separate feature request)

Previously, `SignedJwtAssertionCredentials` allowed you to pass in the key file contents directly instead of passing in a file path (as shown [here](https://developers.google.com/api-client-library/python/auth/service-accounts)) It would be great if `ServiceAccountCredentials` also supported this, for both JSON and p12 keys.

In the meantime, this has prevented us from upgrading to v2.0.0, as our keys are pulled in dynamically at runtime and it's much easier for us to directly pass in the contents instead of having to first write to disk, pass in the path, and then do all the necessary cleanup.

**Comment by zhoufeng1989** [comment]
That's what I need, it will be easier to upgrade to version 2.0.0 if **SignedJwtAssertionCredentials** is used before.

**Comment by dhermes** [comment]
@allenpc I just peeked at the [old source][1] and it doesn't actually seem like a buffer was supported:

```python
self.private_key = base64.b64encode(_to_bytes(private_key))
```

Any thoughts here?

[1]: https://github.com/google/oauth2client/blob/v1.5.2/oauth2client/client.py#L1641

**Comment by allenpc** [comment]
@dhermes You are totally right, I was mistaken when I stated before that `SignedJwtAssertionCredentials` took in a buffer directly, looks like it just takes a string. For the purposes of easing every's migration to 2.0.0, I think we should keep the semantics consistent and just a string, as before.

**Comment by dhermes** [comment]
No worries. Adding this functionality didn't take away from the existing.

**Comment by harishpendela** [comment]
@dhermes Can you paste an example of ServiceAccountCredentials that takes a string for pkey as input

**Comment by dhermes** [comment]
```python
import io
file_buffer = io.BytesIO(pkey_as_str)
creds = ServiceAccountCredentials.from_p12_keyfile_buffer(
    service_account_email, file_buffer)
```
