### ISSUE TITLE
ServiceAccountCredentials needs a way to provide the 'sub' parameter

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#418]
'sub' is required to do domain-wide delegation of authority. The historical sample was:

```python
credentials = SignedJwtAssertionCredentials(client_email, private_key,
    'https://www.googleapis.com/auth/sqlservice.admin',
    sub='user@example.org')
```

Right now the only decent way to do this with the factory method is to do:

```python
credentials._kwargs['sub'] = 'user@example.org'
```

We should either extend the factory methods to accept `kwargs` or add a `create_delegated` method.

/cc @dhermes

**Comment by dhermes** [comment]
:+1: I struggled with the `**kwargs` --> `self.kwargs` design when making the upgrade.

**Comment by jonparrott** [comment]
Which do you recommend we do?

**Comment by dhermes** [comment]
I prefer just adding `sub=` to the factory constructors, rather than the `**kwargs` free-for-all.

**Comment by dhermes** [comment]
Also, we should start adding examples to docstrings to give the future humans motivation for why things exist the way they do.

**Comment by jonparrott** [comment]
I would personally prefer `create_delegated` - matching with `create_scoped`- as it conceptually creates a new set of credentials.

And yes, docstrings would be great.

Do you think you can make this change? I'm currently updating the docs.

**Comment by dhermes** [comment]
I'll make the change but am a bit nervous about the design, so we can discuss on the PR.

**Comment by jonparrott** [comment]
Thank you. It'll also give @nathanielmanistaatgoogle a chance to comment on the design.
