### ISSUE TITLE
Suspicious release to pypi 2.0.0.post1

### ISSUE THREAD

**Issue by dims** [google/oauth2client#427]
We (openstack) have a CI that pulls latest versions of packages and we found a release:
https://pypi.python.org/pypi/oauth2client/2.0.0.post1

Is this a "real" release?

**Comment by nathanielmanistaatgoogle** [comment]
Yes it's real; I actually just learned from the discussion [here](https://github.com/google/oauth2client/pull/411#issuecomment-186438829) that the way it is named comes from [PEP 440](https://www.python.org/dev/peps/pep-0440/#post-release-separators).
