### ISSUE TITLE
Fix out-of-date BigQuery docs

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#435]
See [comment][1] by @nad2000:

> Documentation and examples, eg, https://cloud.google.com/bigquery/authentication, still refer to **run** not **run_flow** :(

[1]: https://github.com/google/oauth2client/commit/98df500a29157ccaa3f6bdf4517d57a5be8e85f1#commitcomment-16260659

**Comment by dhermes** [comment]
@jonparrott I just assigned to you because you seemed to know what to poke to get developers.google.com updated. Feel free to unassign.

**Comment by dhermes** [comment]
Regarding the old `run` method, it was deprecated in 2013 and finally removed in the `1.5.0` release. We thought we'd heard the "last" of examples that were broken by the removal, but it seems we haven't.

[1]: https://github.com/google/oauth2client/issues/299#issuecomment-138339730

**Comment by jonparrott** [comment]
Feel free to always assign these to me, @waprin, or @jerjou. We own the Python samples on cloud.google.com, and we can update samples on developers.google.com.

**Comment by dhermes** [comment]
Thanks!
