### ISSUE TITLE
Devsite Docs Broken: OAuth2ServiceAccount page

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#444]
See [comment][1] from @lukwam.

Relevant page is https://developers.google.com/identity/protocols/OAuth2ServiceAccount

Fix is to use `scopes` as a kwarg rather than as a positional.

[1]: https://github.com/google/oauth2client/issues/401#issuecomment-189703541

**Comment by jonparrott** [comment]
Docs change created, should be updated today. Closing this issue.

**Comment by dhermes** [comment]
:+1: Lightning fast!
