### ISSUE TITLE
ServiceAccountCredentials cannot generate_signed_url in gcloud

### ISSUE THREAD

**Issue by paulharter** [google/oauth2client#448]
Hi,

gcloud/credentials/generate_signed_url still expects to find the private key in `_private_key_pkcs8_pem` but it has been wrapped by the signer now. I can set it myself as has been done in the classmethod constructors, but this seems the wrong place to be doing this. The default `__init__` should be setting this not classmethods as others, like me, may not be using them.

Should the key really  be in both` _private_key_pkcs8_pem` and `signer`? This looks fragile, and indeed has broken for me.

Thanks

**Comment by dhermes** [comment]
It seems this should be a bug in [GoogleCloudPlatform/gcloud-python][1] no? I've got a pending PR to make our usage of the private keys less brittle:
https://github.com/GoogleCloudPlatform/gcloud-python/pull/1518

It's just gated on a release of `oauth2client` holding

@nathanielmanistaatgoogle shall we cut a release of `oauth2client`?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python

**Comment by dhermes** [comment]
@paulharter Are you creating `credentials` manually and then passing them along? Are you using `ServiceAccountCredentials.__init__` directly? If yes, how are you constructing the signer?

**Comment by nathanielmanistaatgoogle** [comment]
@dhermes I want you to feel entitled and enabled to cut an `oauth2client` release any time you please.

If we're ever in a situation in which it's not safe to do so, or there are technical encumbrances to fix before we can do so, that's a process problem to be fixed.

So yeah: [if you want to release, release](https://www.youtube.com/watch?v=Hh-1Lag3BV8).

**Comment by dhermes** [comment]
Sounds good. Thanks.

**Comment by paulharter** [comment]
@dhermes yes I'm making the credentials something like this:

```
    private_key_pkcs8_pem = GOOGLE_PRIVATE_KEY
    signer = crypt.Signer.from_string(private_key_pkcs8_pem)

    credentials = service_account.ServiceAccountCredentials(
        GOOGLE_ACCOUNT_EMAIL,
        signer,
        scopes=[],
        private_key_id=GOOGLE_PRIVATE_KEY_ID,
        client_id=GOOGLE_SHORT_CLIENT_ID
    )
    # adding the key in for a second time
    credentials._private_key_pkcs8_pem = private_key_pkcs8_pem
```
cache them for a little while and use them to sign urls

```
    url = generate_signed_url(credentials,
                        resource,
                        expiration,
                        api_access_endpoint=GCLOUD_STORAGE_API_ACCESS_ENDPOINT,
                        method='GET')
```
You're right the main issue is probably in gcloud, but more an issue of coordination rather than bug fixing. If it was me I'd turn `_private_key_pkcs8_pem` into a property that read from the signer so as not to break gcloud til they catch up.

**Comment by dhermes** [comment]
Good to know. Thanks. I cut the `2.0.1` release today and merged https://github.com/GoogleCloudPlatform/gcloud-python/pull/1518 so the only hangup now is a release of `gcloud-python`

**Comment by dhermes** [comment]
OK that release came out too. All good!

**Comment by paulharter** [comment]
@dhermes Brilliant - thank you for sorting this out so quickly!

**Comment by dhermes** [comment]
Sure thing. Getting the crypto out of `gcloud-python` and into `oauth2client` had been bothering me for months
