### ISSUE TITLE
create_delegated, service accounts, and the sub param.

### ISSUE THREAD

**Issue by mburke05** [google/oauth2client#455]
Thanks for all the hard work on 2.0.0; I had a question concerning the utilisation of service accounts and the new `create_delegated` method. 

See the below post for details; I had figured raising an issue here might be a better way of getting an answer. I appreciate your time in advance!

http://stackoverflow.com/questions/35961676/python-google-analytics-oauth-service-account-and-2lo-sub-parameter-and-domai

**Comment by dhermes** [comment]
@mburke05 I am out of my depth here. Sorry.

**Comment by jonparrott** [comment]
Maybe @mcohoon can help?

**Comment by mcohoon** [comment]
[Ansered the question on StackOverflow](http://stackoverflow.com/questions/35961676/python-google-analytics-oauth-service-account-and-2lo-sub-parameter-and-domai/36093792#36093792)

For reference here, the `create_delegate` method is works only for [domain wide delegation](https://developers.google.com/admin-sdk/directory/v1/guides/delegation). Google Analytics is not an **Google Apps for Work** product, thus you cannot use this method to access another user's Google Analytics Account. @jonparrott feel free to close this issue.

**Comment by dhermes** [comment]
Thanks @mcohoon!
