### ISSUE TITLE
doesn't work on python 3

### ISSUE THREAD

**Issue by coollorenzo** [google/oauth2client#461]
when i trie the example on python 3 I get:

Traceback (most recent call last):
  File "F:/programming/projecten/back-end/zermelo2gcalendar/test.py", line 5, in <module>
    from apiclient import discovery
  File "D:\Python34\lib\site-packages\apiclient\__init__.py", line 18, in <module>
    from googleapiclient import channel
  File "D:\Python34\lib\site-packages\googleapiclient\channel.py", line 63, in <module>
    from googleapiclient import errors
  File "D:\Python34\lib\site-packages\googleapiclient\errors.py", line 26, in <module>
    from oauth2client import util
ImportError: cannot import name 'util'

On python 2 it works just fine

**Comment by jonparrott** [comment]
Can you tell us which versions of oauth2client and google-api-python-client you're using? This should be available via `pip freeze`.

**Comment by coollorenzo** [comment]
My versions are:
oauth2client==2.0.1
google-api-python-client==1.5.0

**Comment by dhermes** [comment]
Maybe you have a bad import getting in the way. Try

```
$ python3.4 -c 'import oauth2client; print(oauth2client)'
<module 'oauth2client' from '/usr/local/lib/python3.4/dist-packages/oauth2client/__init__.py'>
```

**Comment by coollorenzo** [comment]
I'm on windows but when I put:
`import oauth2client; print(oauth2client)
`
into my python console I get: 
`<module 'oauth2client' (namespace)>`

**Comment by dhermes** [comment]
I wonder where the `oauth2client` namespace package comes from. @jonparrott any ideas?

**Comment by jonparrott** [comment]
I can't reproduce this with py3.4 on OS X or Linux, and I don't have a windows machine on hand to test with.

@coollorenzo can you try using virtualenv?

**Comment by coollorenzo** [comment]
@jonparrott It works on virtualenv so there where libaries intervering with the google api libary? Thank btw

**Comment by dhermes** [comment]
Yeah. The namespace object might have `__path__` defined. I'd suggest importing `oauth2client` and just trying to get info directly from that object

**Comment by coollorenzo** [comment]
Oke thanks guys!
