### ISSUE TITLE
oauth2client.tools should not fail silently without argparse

### ISSUE THREAD

**Issue by theacodes** [google/oauth2client#463]
Presently, tools has an import guard against argparse [here](https://github.com/google/oauth2client/blob/master/oauth2client/tools.py#L56) because argparse is optional in py2.6. Instead of silently failing, it should either issue a warning or an exception.

**Comment by dhermes** [comment]
Py2.6 can go to heck

**Comment by jonparrott** [comment]
Considering our only downstream user that needs py2.6 is gsutil, we might as well ignore it in this module anyway.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
