### ISSUE TITLE
contrib.appengine uses its own InvalidClientSecretsError

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#465]

**Comment by pferate** [comment]
I don't see any reason within `oauth2client` to not change it to use `clientsecrets.InvalidClientSecretsError`.

I'm not sure if any major projects are trying to catch it.

I can make a PR for this, and leave it up to you guys on when to merge it in.

The other exception in that module is `InvalidXsrfTokenError(Exception)`, and is not used outside of it.  Should I just leave that as is, or have it extend a local base error for the module?

**Comment by jonparrott** [comment]
originally backwards compatibility, but I'm okay with breaking changes as long as they're in a major release.

**Comment by jonparrott** [comment]
Closed by #533
