### ISSUE TITLE
ImportError: cannot import name SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by saroele** [google/oauth2client#469]
I have a fresh install of oauth2client 2.0.1 on xubuntu 14.04 for python 2.7.  Strangely, when running
`from oauth2client.client import SignedJwtAssertionCredentials` I get the following error:

    ImportError: cannot import name SignedJwtAssertionCredentials

pyopenssl is installed, and when I run:

```
HAS_OPENSSL = False
HAS_CRYPTO = False
try:
    from oauth2client import crypt
    HAS_CRYPTO = True
    if crypt.OpenSSLVerifier is not None:
        HAS_OPENSSL = True
except ImportError:
    pass
```
both `HAS_OPENSSL` and `HAS_CRYPTO` are `True`. 

What seems strange to me is that when I open this file: `/usr/local/lib/python2.7/dist-packages/oauth2client/client.py`, there is no single mention of `SignedJwtAssertionCredentials`.  To me that explains the ImportError.   Do I have a wrong `client.py` ?

**Comment by jonparrott** [comment]
We explicitly removed `SignedJwtAssertionCredentials` in [v2.0.0](https://github.com/google/oauth2client/releases/tag/v2.0.0). The release notes contain information on how to migrate.
