### ISSUE TITLE
Remove multistore file/locked file

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#470]
Multistore file and locked file are designed to fit a very specific use case:

> Safely use a credential across multiple processes.

They unfortunately also represent a great deal of cruft and technical debt in this repository. I would greatly prefer to do one of the following:

1. Remove `locked_file` and use an existing interprocess lock library such as [fasteners](http://fasteners.readthedocs.org/en/latest/examples.html#interprocess-locks). Keep `multistore_file`.
2. Remove both.

If we go route two, downstream users of this file have two options:

1. Pull `multistore_file` and `locked_file` into their own codebase. Considering that these files are now completely separated from core and `oauth2client` has always intended users to write their own storage classes if needed, this doesn't seem like a bad option.
2. We could provide a version of `multistore_file` based on sqlite which has concurrency built-in. However, downstream users would have to take on an additional dependency with a native component. If that is untenable, they could still go with route one.

/cc @thobrla @dhermes @nathanielmanistaatgoogle

**Comment by thobrla** [comment]
Ideally whatever changes we make here should be transparent to users.

Option 1 sounds fine.
Option 2.1 effectively removes support for this use case, so I strongly dislike it.  It's going to be hard for users to maintain forks of those files given how frequently the underlying oauth2client implementation changes.
Option 2.2. sounds fine assuming there are no issues with that component.

**Comment by jonparrott** [comment]
> Option 2.1 effectively removes support for this use case, so I strongly dislike it. It's going to be hard for users to maintain forks of those files given how frequently the underlying oauth2client implementation changes.

Storage doesn't seem likely to change in any major way. I tried and failed to do so. From what I can tell, the only users of this are first-party tools.

**Comment by dhermes** [comment]
@thobrla 

> how frequently the underlying `oauth2client` implementation changes.

This will certainly slow down (hopefully at some point in 2016). The reason for changes lately is because the codebase is in such bad shape, people like @jonparrott, @nathanielmanistaatgoogle and I have been trying to rescue it.

**Comment by jonparrott** [comment]
@thobrla @nathanielmanistaatgoogle

The more I think about it and the more I interact with this code, I'm extremely inclined to remove it. Cloud SDK and gsutil are the biggest public users, but a cursory internal search shows that there are some internal clients that still use it. @nathanielmanistaatgoogle is technically able to add a separate library to provide this functionality for internal users, but external users would still have to absorb the code into their repository.

If you guys feel very strongly that we should keep `multistore_file`, then I will try to switch the implementation to use [fasteners](http://fasteners.readthedocs.org/en/latest/examples.html#interprocess-locks) instead of our `locked_file.py`.

**Comment by thobrla** [comment]
I feel strongly that we need to provide some multi-process compatible solution.  It's a matter of performance for Google Cloud Storage users, and I imagine other APIs would also benefit from (authenticated) clients that support multiple streams.

I'd be willing to port to a new interface, but I don't think we want to hand this problem off to clients.

**Comment by jonparrott** [comment]
If I implement it with fasteners you'd just have to take on a new third-party dependency.

The lack of public use of this disproves your assertion that "other APIs would benefit", this is seemly used exclusively by Google. Probably because we're likely the only ones building client tools with this library, everyone else is using it for server applications where a database is available and a far superior choice.

**Comment by thobrla** [comment]
Taking a new third-party dependency is easy (as long as it works in Python 2 and 3, which fasteners does) compared to assuming the maintenance burden of maintaining multistore_file locally.

I agree that this matters more for client tools.  Does this library intend to support those?

**Comment by jonparrott** [comment]
> I agree that this matters more for client tools. Does this library intend to support those?

We do to the extent that it makes sense. But it seems weird to put this burden on us. We don't currently provide storage classes for every popular database, which would be the equivalent of this in the server application world. We do plan to provide basic support for key-value stores, but nothing above and beyond.

**Comment by thobrla** [comment]
"put this burden on us" makes it sound like a feature request, but client tools were just using the provided features of the library. I agree that it doesn't translate to the server application world, but providing a filesystem-based lock implementation does not require you to provide server application analogs.

If this feature is removed, tools like gsutil must pin to an old oauth2client version until we have time to develop our own solution (or integration testing for a locally-maintained multistore_file).

**Comment by jonparrott** [comment]
> but client tools were just using the provided features of the library.

Given the history of this library, it's likely the origination was the other way around: a client needed it and put it here thinking that others would need it. They probably had good intentions of maintaining it, but as it stands today most of the downstream clients of this library receive more attention than this library.

> providing a filesystem-based lock implementation does not require you to provide server application analogs.

It doesn't; I don't technically have to provide anything (most oauth2 library provide no storage at all). I was trying to illustrate why I don't think this is the responsibility of this library. The library has always been clear that clients should probably implement their own storage if needed. If we accept the maintenance responsibility for this very particular use case, then we have little ground to argue against maintaining storage for a long list of use cases.

> If this feature is removed, tools like gsutil must pin to an old oauth2client version until we have time to develop our own solution (or integration testing for a locally-maintained multistore_file).

That's not unexpected- but bear in mind that you've been using a mostly untested feature of this library for years. We're not solving this problem for you by keeping it here, we're just allowing you not to think about it.

Our choices are clear:

1. Leave the current version here which is difficult to test and probably has bugs.
2. Keep the interface, switch the locking to use fasteners, which will definitely introduce more bugs.
3. Remove it.

**Comment by thobrla** [comment]
From the command-line tools' perspective (gsutil, gcloud), this was an existing feature of the library.  multistore_file was introduced in ~2011; gsutil wasn't using this feature when 2.0 was released in 2012, and gcloud didn't exist at that point.

Agree with your options, though "this will probably have bugs" will be true of wherever the implementation lands.

**Comment by jonparrott** [comment]
I'm going to move forward with (2) near term, but I'm going to hold a grudge against this until the day I can finally remove it.

FWIW, I think that you guys should switch to a far more robust solution such as sqlite, which is designed exactly for this use case. If you were to write a sqlite storage class, I'd be happy to have it here.

**Comment by jonparrott** [comment]
Now that #504 is merged, this is now a tracking bug for removing `multistore_file` and its dependent modules.
