### ISSUE TITLE
Unit test failure when running Python3 in Debian Sid

### ISSUE THREAD

**Issue by thomasgoirand** [google/oauth2client#472]
Hi. I'm the package maintainer for `oauth2client` in Debian. When running the unit tests in Debian Sid (ie: when building the package), I get the below unit test failures:

```python
======================================================================
ERROR: test_token_refresh_store_expires_soon (tests.test_file.OAuth2ClientFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zigo/sources/openstack/mitaka/python-oauth2client/build-area/python-oauth2client-2.0.1/tests/test_file.py", line 165, in test_token_refresh_store_expires_soon
    http.request('https://example.com')
  File "/home/zigo/sources/openstack/mitaka/python-oauth2client/build-area/python-oauth2client-2.0.1/oauth2client/client.py", line 622, in new_request
    redirections, connection_type)
  File "/home/zigo/sources/openstack/mitaka/python-oauth2client/build-area/python-oauth2client-2.0.1/tests/http_mock.py", line 102, in request
    return httplib2.Response(resp), content
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1382, in __init__
    self.status = int(self.get('status', self.status))
ValueError: invalid literal for int() with base 10: 'HTTPStatus.UNAUTHORIZED'

======================================================================
ERROR: test_token_refresh_stream_body (tests.test_file.OAuth2ClientFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zigo/sources/openstack/mitaka/python-oauth2client/build-area/python-oauth2client-2.0.1/tests/test_file.py", line 211, in test_token_refresh_stream_body
    _, content = http.request('https://example.com', body=body)
  File "/home/zigo/sources/openstack/mitaka/python-oauth2client/build-area/python-oauth2client-2.0.1/oauth2client/client.py", line 622, in new_request
    redirections, connection_type)
  File "/home/zigo/sources/openstack/mitaka/python-oauth2client/build-area/python-oauth2client-2.0.1/tests/http_mock.py", line 102, in request
    return httplib2.Response(resp), content
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1382, in __init__
    self.status = int(self.get('status', self.status))
ValueError: invalid literal for int() with base 10: 'HTTPStatus.UNAUTHORIZED'
```

----------------------------------------------------------------------

The environment is Python 3.5 in Sid. Maybe there's an issue with that?

Also, `tests/test_tools.test_ClientRedirectServer` is doing network access, which is forbidden during a package build. Please skip the unit test if we're building the debian package (you can check one of the env vars set (for example `DEB_BUILD_ARCH`)).

**Comment by dhermes** [comment]
@thomasgoirand Thanks for the report. `oauth2client` doesn't officially support 3.5 yet (though it should).

@nathanielmanistaatgoogle It seems the issue reported is related to #410. WDYT?

**Comment by nathanielmanistaatgoogle** [comment]
Wow, that's weird.

@dhermes: I doubt that #410 is itself defective; my suspicion is that some preëxisting defect is being revealed by #410 rather than caused by #410. I also agree that `oauth2client` should move towards supporting 3.5.

@thomasgoirand: are you able to reproduce the defect in any other version of Python? I think it would be very, very strange for something to have changed in 3.5 in such a way as to cause what you observe, but I also think it would be at least a little strange for something to have changed in 3.5 in such a way as to merely reveal what you observed.

**Comment by thomasgoirand** [comment]
The unit tests are passing if using Python 3.4 and Django 1.8 (ie: in Debian Jessie with a backport of Django 1.8). It fails in Sid. That's all I can tell, unless you wish me to investigate further (in which case you have to give me directions).

**Comment by nathanielmanistaatgoogle** [comment]
@thomasgoirand: how about substituting the integer `401` for the value `six.moves.http_client.UNAUTHORIZED` everywhere in the program text, confirming that the tests pass, and then slowly moving back to using `six.moves.http_client.UNAUTHORIZED` place-by-place until the defect is triggered again?

I think that this smells like a problem of some string needing to be "the string representation of a literal integer value" somewhere, and #410 went an changed it to "the string representation of a field that is assigned an integer value". Do you agree? But I can't think of how it would be coming up without something really boneheaded, like use of [`eval`](https://docs.python.org/2/library/functions.html#eval). @dhermes there's no use of `eval` in oauth2client, right? A search shows two results in `.sh` files and none in `.py` files.

**Comment by dhermes** [comment]
RE: `eval`, You're `git grep` guess is as good as mine.

@nathanielmanistaatgoogle Do you not have access to Python 3.5 to test the changes on your machine?

**Comment by txomon** [comment]
In this line of thinking, would it be possible to add TOX_ENV=py35 to travis?

**Comment by jonparrott** [comment]
> In this line of thinking, would it be possible to add TOX_ENV=py35 to travis?

I think that's pretty reasonable.

**Comment by pferate** [comment]
This looks like a difference in `http.client` between 3.4 and 3.5.

### Python 3.4
\>\>\> from six.moves import http_client
\>\>\> http_client
\<module 'http.client' from '/usr/local/lib/python3.4/http/client.py'\>
\>\>\> http_client.BAD_REQUEST
400

### Python 3.5
\>\>\> from six.moves import http_client
\>\>\> http_client
\<module 'http.client' from '/usr/local/lib/python3.5/http/client.py'\>
\>\>\> http_client.BAD_REQUEST
\<HTTPStatus.BAD_REQUEST: 400\>

We can cast the status as an int in the tests, to maintain backwards maintainability.  I have a 3.5 branch and will go through any other problems.

**Comment by pferate** [comment]
After a bit more digging, I found more info.  In 3.5, they added a new class, `http.HTTPStatus`, which gets returned instead of `int`.

https://docs.python.org/3/library/http.html#http.HTTPStatus

Now, we can use `http.HTTPStatus.OK.value` and `http.HTTPStatus.OK.phrase` to get the HTTP status code and phrases, respectively; although this is only 3.5+.

Like I said previously, we can cast it as an int to maintain backwards maintainability, unless someone else would like it handled differently.

**Comment by jonparrott** [comment]
casting to int is fine by me, happy to review the PR.

**Comment by pferate** [comment]
Just about done.  I have some questionable parts that I'll mention in the PR.

**Comment by pferate** [comment]
@thomasgoirand: 3.5 support has recently been added to the master branch.  Can you verify your tests with that?

**Comment by jonparrott** [comment]
This issue has been inactive, so I'm going to close it. If this is still an issue please feel free to comment and I'll happily re-open it.
