### ISSUE TITLE
[Question] Why isn't ServiceAccount._generate_assertion public?

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#489]
Seems like generating a JWT with a service account might become more important in the future. Can we have a first-class method for generating them?

**Comment by jonparrott** [comment]
@dhermes (friendly, low-priority) ping.

**Comment by dhermes** [comment]
It's fine with me, though you can probably achieve what you want without exposing `_generate_assertion`.

I was able to make a [scopeless prototype][1] using the already public `oauth2client.crypt.make_signed_jwt`.

[1]: https://github.com/google/oauth2client/issues/252#issuecomment-188535108

**Comment by jonparrott** [comment]
Oh yeah, it's possible, it's just not pretty. I'm writing a sample for a new product that uses JWTs to authenticate and I'd prefer to do it in one line rather than several. :) 

(I'm lazy).

**Comment by dhermes** [comment]
Are you volunteering to implement #252?

**Comment by jonparrott** [comment]
I'm being pre-empted by a high-priority task until the end of the month, so let's see. I'll close this since we have an open issue for it.

**Comment by dhermes** [comment]
I wasn't suggesting you close it, but if the issue is that you want it for scopeless credentials, then yes we do have an issue for it already.
