### ISSUE TITLE
Release 2.0.2?

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#499]
We just fixed a significant issue with the flask helper as well as hitting 100% coverage and other small things. Can we release 2.0.2?

**Comment by dhermes** [comment]
SGTM. Why do I need to be assigned? What're you blocked on @jonparrott?

**Comment by jonparrott** [comment]
Oh, I've never cut a release of this project.  :3

**Comment by dhermes** [comment]
Gotcher. The release PRs should serve as a nice template. The only extra thing to know is that you need to push a tag (or create a tag in the GitHub interface) so that Travis will push to PyPI.

**Comment by dhermes** [comment]
#341, #404, #423, #449
