### ISSUE TITLE
403 when using DWD in appengine to use admin sdk

### ISSUE THREAD

**Issue by jessicawisesc** [google/oauth2client#502]
Hi guys! Great work, but running into some issues with the new auth flow.

I am going for unattended access- i.e. generating reports- to the admin SDK. I stepped away from the GAPPS API's for the last year, and came back to quite the change! 

Attended flow is super simple, but unattended seems a lot more complex. I have tried: AppAssertionCredentials, ServiceAccount, and even using the flow covered in the admin sdk python quickstart.

Can you clue me in? How is unattended API access supposed to function now? When I try- using a DWD account with it's client ID granted scopes in GApps admin settings- I get a 403.

Appreciate the clarification. Does your team have a slack I can join for this stuff? The documentation is currently nigh useless due to being very  convoluted.

**Comment by jonparrott** [comment]
By unattended, do you mean accessing these APIs as the administrator of a domain?

> The documentation is currently nigh useless due to being very convoluted.

Please gratuitously use the "send feedback" button on the docs - feedback is collected internally as bugs.

**Comment by jessicawisesc** [comment]
Thanks- yeah, I just continue to run into different and conflicting data.
I believe yes, that is what I need. The goal is to be able to have my application run API calls on a scheduled basis, without needing a user to manually accept the consent screen.
This is running in GAE fyi.

`credentials = ServiceAccountCredentials.from_json_keyfile_name(
            SERVICE_ACCT_JSON, scopes=SCOPES)
credentials.create_delegated(sub=USER_EMAIL)
self.service = build('groupssettings', 'v1',credentials=credentials)
self.admin_service = build('admin', 'directory_v1',credentials=credentials)`

**Comment by jonparrott** [comment]
Your code is missing just one critical piece. `credentials.create_delegated` returns a *new* set of credentials and doesn't modify the original object. So try this:

```python
credentials = ServiceAccountCredentials.from_json_keyfile_name(
    SERVICE_ACCT_JSON, scopes=SCOPES)

delegated_credentials = credentials.create_delegated(sub=USER_EMAIL)

self.service = build('groupssettings', 'v1', credentials=delegated_credentials)
self.admin_service = build('admin', 'directory_v1', credentials=delegated_credentials)
```

**Comment by jessicawisesc** [comment]
Thanks! Still getting a 403, but that is progress- 'user email' - would that be a actual user, or would it be the service account email?

**Comment by jonparrott** [comment]
For the directory API, as far as I know it needs to be the email of an
actual admin in the domain. I'm not 100% sure on that. (We maintain the
client library, not the APIs themselves)

**Comment by jonparrott** [comment]
I'm closing this issue as you haven't responded in several days. If you still have questions, feel free to reply and we'll re-open the issue if needed.
