### ISSUE TITLE
GoogleCredentials from_json() should accept json generated files from dashboard

### ISSUE THREAD

**Issue by txomon** [google/oauth2client#505]
How to load credentials in the official recommended way (JSON file) is not documented. 

One would expect that `from_json()` and `default_credentials()` would work on the same files, but it looks like from_json() only works on an internal json export (??). Instead, To load that json, one needs to call `ServiceAccountCredentials.from_json_keyfile_name()`.

In a nutshell, loading a json file generated from the [dashboard](https://console.cloud.google.com/iam-admin/serviceaccounts/project) is not intuitive and not documented.

**Comment by dhermes** [comment]
Yes the `from_json()` and `to_json` public names are a bit confounding, since they are meant to be internal serialization/deserialization helpers. On the other hand the `ServiceAccountCredentials.from_json_keyfile_name()` is what you're meant to use.

When you say "not documented", did you check out http://oauth2client.readthedocs.io/en/latest/source/oauth2client.service_account.html? (Though it'd be nice to have narrative docs for each module, like in http://oauth2client.readthedocs.io/en/latest/source/oauth2client.contrib.flask_util.html)

**Comment by txomon** [comment]
@dhermes Sorry, just realized I hadn't answered. 

Yes, I am using `ServiceAccountCredentials.from_json_keyfile_dict()`.

When I meant not documented, I meant not documented use cases like for `default_credentials()` in the google cloud docs. I really miss having a how to use like the one in https://cloud.google.com/compute/docs/tutorials/python-guide#google-api-client-for-python

At the end, documenting the interface doesn't really help if you don't have a guide.

Also, a reference on the different json formats the library supports would be super helpful!

**Comment by jonparrott** [comment]
@txomon excuse me if I'm being obtuse, but what sort of documentation would you like to see to help resolve this?

**Comment by dhermes** [comment]
@txomon Yes, those methods (`to_json` and `from_json`) aren't intended for use in general code, just for use in serialization.

**Comment by txomon** [comment]
@jonparrott I was thinking on something like http://docs.python-requests.org/en/master/user/quickstart/#make-a-request where you have not only the API reference, but also a guide on how to use it.

An example would be to explain how to set up default_credentials, which environment variables are checked, how to load from file those credentials, how to use those credentials in the different situations, etc.

The idea is that with a one page text anyone that needs to use this library should be able to do >90% of the things that needs to.

Please tell me if you need more details.

**Comment by dhermes** [comment]
OK great, so we're talking about `from_json_keyfile_name()` and similar, rather than `from_json()`. @jonparrott we've done a fair bit to document the process in http://gcloud-python.readthedocs.io/en/latest/gcloud-auth.html

**Comment by txomon** [comment]
@dhermes uau! that is exactly what I meant!

**Comment by txomon** [comment]
@dhermes so this library should have a part like that? or maybe a link to gcloud? Although I don't like mixing concerns...

**Comment by jonparrott** [comment]
@txomon does this documentation also satisfy your needs? https://developers.google.com/identity/protocols/application-default-credentials

**Comment by txomon** [comment]
@jonparrott no, that is what I used. That only explains one of the multiple possible usages of the library, but doesn't mention loading from file manually, or from an in memory json/dict.

The one @dhermes shared is more on the way I was thinking, but would still require to be completed with how to load from memory json-dicts (if you look at the code you realize it is done through the function I mentioned, but isn't really a documented example)

Documentation of the API classes-methods is great, but the problem is that without examples you end up reading the code.
