### ISSUE TITLE
Getting 404 errors with Google API since SignedJwtAssertionCredentials replaced

### ISSUE THREAD

**Issue by pcolmer** [google/oauth2client#507]
I have a script written in python that adds events to a company calendar on Google.

I've followed the comments in https://github.com/google/oauth2client/issues/401 and implemented the steps provided by dhermes to use a PEM file with the new code to authenticate. So:

    credentials = SignedJwtAssertionCredentials(service_account_email, key, scope='https://www.googleapis.com/auth/calendar', sub="creator@example.com")

has been replaced with:

    with open(pem_file_path, 'rb') as fh:
        pem_contents = fh.read()
    signer = crypt.Signer.from_string(pem_contents)
    credentials = ServiceAccountCredentials(service_account_email, signer, scopes=['https://www.googleapis.com/auth/calendar'])
    credentials._private_key_pkcs8_pem = pem_contents

So far, so good, except that I don't know what to do with "creator@example.com". https://developers.google.com/identity/protocols/OAuth2ServiceAccount mentions:

    delegated_credentials = credentials.create_delegated('user@example.org')

but I don't know what to do then with "delegated_credentials".

Furthermore, and more seriously, when I actually try to create the calendar event, I get a 404 error. The bit of the script that creates the calendar event is:

    created_event = service.events().insert(calendarId=CALENDAR, body=event).execute()

and this hasn't changed. If I use Google's API tester and copy/paste the same calendar ID and the JSON that my script generates, the API works ... which suggests that I've got something wrong with the authentication side of things, although I would expect a 401 error (unauthorised) rather than a 404 error (not found).

I've **only** changed the authentication code in my script in order to cope with the change in oauth2client, so that does seem to be where I've got the problem but I don't know what to do to fix it.

**Comment by dhermes** [comment]
You've left out a crucial bit: how is the `service` created? Since you say

> I don't know what to do then with `delegated_credentials`

it seems that may be the missing piece of the puzzle. The `delegated_credentials` should be used in the create of the `service`.

**Comment by pcolmer** [comment]
@dhermes 

Sorry - a bit of a copy/paste newbie, really :)

Here is where I create the service:

    http = httplib2.Http()
    http = credentials.authorize(http)

    service = build("calendar", "v3", http=http)

**Comment by dhermes** [comment]
Change to

```python
http = delegated_credentials.authorize(http)
```

and it **should** resolve the problem (fingers crossed). I'm surprised the error was a 404 instead of a 403 though.

**Comment by dhermes** [comment]
If this doesn't work, can you provide a stacktrace showing what causes the 404's to occur?

**Comment by pcolmer** [comment]
Hi @dhermes 

Can you please let me know how to provide a stacktrace, just in case I need to do that? I'll make the suggested change to the code tomorrow morning.

Thank you.

**Comment by pcolmer** [comment]
Thanks, @dhermes - adding the delegated credentials did fix it. Thanks for the help.
