### ISSUE TITLE
cannot use AppAssertionCredentials with DwD

### ISSUE THREAD

**Issue by jonoberheide** [google/oauth2client#511]
I'm attempting use GApps Admin SDK + the built-in GAE service account + Domain-wide Delegation (DwD) + AppAssertionCredentials.

However, unlike ServiceAccountCredentials, AppAssertionCredentials does not have a create_delegated method, nor any way to specify a sub that I can find.

Am I missing something or is this a known limitation? If the latter, is it feasible to resolve in oauth2client? I'd be happy to put in some work if pointed in the right direction.

**Comment by jonparrott** [comment]
This is a limitation of AppAssertionCredentials. 

Unlike the token API used by the service account credentials to acquire an access token, the App Engine identity API does not provide any way to specify additional claims (it only supports the scopes argument).
