### ISSUE TITLE
ServiceAccountCredentials.from_json_keyfile_name() ignores token_uri setting in JSON.

### ISSUE THREAD

**Issue by BrandonY** [google/oauth2client#513]
Steps to reproduce:

1. Generate a service_account.json file.
2. Add a line to JSON file like so:
```
"token_uri": "https://some-other-auth-uri.website.com/o/oauth2/token",
```
3. Run this program:

```
from oauth2client.service_account import ServiceAccountCredentials

def main():
  creds = ServiceAccountCredentials.from_json_keyfile_name('service_account.json')
  print creds.token_uri    # Prints "https://www.googleapis.com/etc"
```

**Comment by jonparrott** [comment]
@thobrla related to your stuff?

**Comment by thobrla** [comment]
Yes, https://github.com/google/oauth2client/pull/510 should fix this.

**Comment by jonparrott** [comment]
Thanks. :)

**Comment by thobrla** [comment]
Actually, the pull request will need to be amended to support this specific case (where we get the token_uri from the file).  I'll work on that.
