### ISSUE TITLE
Usage with App Engine

### ISSUE THREAD

**Issue by demoneaux** [google/oauth2client#515]
Hi, I'm not very good with Python, so what I'm asking might not be very smart.

I'd like to use the client with App Engine. I'd like to ask if it's possible for the App Engine OAuth2Decorator to be set up in say `utils/decorator`, and then it be imported and used in several different files to mark out `@decorator.oauth_required`. I'm not too familiar with Python yet, and the thread handling in App Engine, so I would appreciate some help.

Additionally, if the above is possible, should I only export the following once?:
```python
app = webapp2.WSGIApplication([
    (decorator.callback_path, decorator.callback_handler())
], debug=True)
```

**Comment by jonparrott** [comment]
Hi there, we have a complete working sample of using the OAuth2 decorator on Google App Engine to access bigquery, but of course you can adapt it to use any scopes/api you want: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/bigquery/main.py

Let me know if that helps or if there's anything I can do to further clarify.
