### ISSUE TITLE
AppAssertionCredentials not respecting access token expiration

### ISSUE THREAD

**Issue by ericbuehl** [google/oauth2client#518]
Note: The issue I'm running into *may* be in conjunction to this issue: https://github.com/google/oauth2client/issues/343

The symptom I am seeing is that the GCE metadata service-supplied access token works for a while but once it expires, oauth2client fails to refresh from the metadata service.

I took a stab at a fix here.  If this looks respectable I'll go ahead and open it as a PR
https://github.com/ericbuehl/oauth2client/commit/2ee53ff30377fa1368faf3987fbc6c4364ce469f

**Comment by jonparrott** [comment]
It seems like #473 will fix this.

**Comment by ericbuehl** [comment]
Yup!  That appears to be a dupe just updated today :)
