### ISSUE TITLE
Docs for doc gen

### ISSUE THREAD

**Issue by elibixby** [google/oauth2client#521]
The process for generating docs isn't documented anywhere in `CONTRIBUTING.md`

**Comment by elibixby** [comment]
Just saw the requirements.txt file >_< still the `CONTRIBUTING.md` lies when it says "Docs will be generated for you" as the docs env in travis fails if there is any difference between the generated docs and the docs on your fork.

**Comment by dhermes** [comment]
The `requirements.txt` is only there so readthedocs.org can build with the deps. `tox -e docs` will set you free
