### ISSUE TITLE
Document apitools.tokens cache and how to disable it

### ISSUE THREAD

**Issue by studgeek** [google/oauth2client#525]
It seems that credentials are being silently stored in ~/.apitools.token by the underlying apitools library. That file seems to include refresh tokens and everything else needed to call APIs as the user or service account who first did the oauth flow.

That should be clearly documented. And there should be an option to turn it off.

**Comment by jonparrott** [comment]
This library doesn't decide where tokens are stored. This seems like it would be more appropriate to file over at https://github.com/google/apitools ?
