### ISSUE TITLE
oauth2client: django_orm.Storage locked_put should try a get/update first

### ISSUE THREAD

**Issue by wizravi** [google/oauth2client#528]
This issue was originally reported at : https://github.com/bradleybossard/google-api-python-client/issues/278, But which look to be oauth2client issue.

Issue:
------------
As described in the above link, 
I also faced the problem where refresh was throws an IntegrityError
due to violation of the unique constrain in model.
Following change worked for me:
In oauth2client/client.py, inside "def _do_refresh_request", I changed the line self.store.locked_put(self) (in line#937) to self.store.locked_put(self, overwrite=True).
Can anyone comment if it is safe fix.

**Comment by jonparrott** [comment]
@waprin can you take a look at this?

**Comment by waprin** [comment]
yes

**Comment by waprin** [comment]
@wizravi I am literally in the middle of rewriting that whole class so this is good information to be aware of. I have a rough sketch here: https://github.com/waprin/oauth2client/pull/4/files though I don't think I address the issue you're describing. If you don't mind, I can put you on the review when I submit a PR ot the main repo sometime soon (next week-ish).

**Comment by letsmakesense** [comment]
+1 for changing to overwrite=True

Everyone following the docs will have the same issue because if user is the primary key for the credentials model you can't insert two credentials for the same user. 

To me it seems that 'get_or_create()' (the overwrite=True case) is always the right choice in this scenario.

**Comment by waprin** [comment]
Agreed, I am finishing up a PR for this, just fixing tests etc. Will mention you on it.
