### ISSUE TITLE
Improve run_flow so it can be used from inside test suites

### ISSUE THREAD

**Issue by martinjungblut** [google/oauth2client#534]
The run_flow() function from the 'tools' module should be usable from inside test suites. It would be handy for the test suites themselves to call the run_flow() function only if needed, that is, if the previous credentials had expired or if no credentials were set.

Currently this is not possible because there is an issue with argparse, since run_flow() expects to be called as a command.

```
Traceback (most recent call last):
  File "/flex/run/tests/integration_tests/googleplus_tests.py", line 14, in test_run_flow
    credentials, ran_flow = helper.run_flow()
  File "/flex/run/tests/helpers/googleplus.py", line 44, in run_flow
    http=httplib2.Http()), True)
  File "/home/hotspot/python/virtualenvs/flex/lib/python3.4/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/hotspot/python/virtualenvs/flex/lib/python3.4/site-packages/oauth2client/tools.py", line 168, in run_flow
    flags = argparser.parse_args()
  File "/usr/lib/python3.4/argparse.py", line 1733, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.4/argparse.py", line 2388, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.4/argparse.py", line 2375, in exit
    _sys.exit(status)
```

That test suite was executed with the following command: python -m unittest tests.integration_tests.googleplus_tests

**Comment by jonparrott** [comment]
How could we improve the function? Are you willing to draft a PR?

**Comment by martinjungblut** [comment]
Yeah, I'm willing to do it and submit a PR if you guys think it's a good idea. I can see the improvement being useful to me personally, and hopefully it could benefit others as well.

**Comment by jonparrott** [comment]
I'm happy to review any PRs, and making things more testable is a welcome addition.

**Comment by martinjungblut** [comment]
All right, I'll submit a pull request as soon as it's ready.

**Comment by jonparrott** [comment]
@martinjungblut friendly ping on this. are you still planning on working on a PR? If not, can you give us some hints on how you're using this?

**Comment by martinjungblut** [comment]
@jonparrott Hey, yes, I'm planning on dedicating quite some hours to this over this next weekend.
At the moment I have a helper class that establishes new credentials every 4 hours for my test suite to run, since that's when the credentials expire. My test suite then uses this helper class, calling its get_credentials() method. If the credentials have expired, the get_credentials() method returns None, my test suite raises a ValueError and I'm off to using the helper class as a script manually, every time. What I plan on doing is improving run_flow() so you can call it directly from inside your test suite when your test credentials have expired. The browser would then pop normally as usual, ask you for your permissions, establish the credentials and the test suite would go on running, using the newly acquired credentials.
You can check this gist for the helper class https://gist.github.com/martinjungblut/1da2f7915ec4242f4584859994996f94

**Comment by jonparrott** [comment]
@martinjungblut hmm, it seems your use case is rather exceptional. Usually for testing I see people either use a service account (which does not need to be refreshed) or use a set of credentials with a refresh token - that can be refreshed indefinitely. Thus, there's no need for run_flow to be executed in tests.

**Comment by martinjungblut** [comment]
@jonparrott Hmm, I had no idea that could be done. I'll try that, and if my problem is solved I don't see the need for this issue to remain open.

**Comment by jonparrott** [comment]
Let me know if there's anything we can do to help further.

**Comment by martinjungblut** [comment]
Thank you for your attention!
