### ISSUE TITLE
Use context manager for assertRaises

### ISSUE THREAD

**Issue by pferate** [google/oauth2client#536]
In the unit tests, update the assertRaises calls to use the context manager.
```python
self.assertRaises(SomeException, do_something, arg1)
```
change to:
```python
with self.assertRaises(SomeException):
    do_something(arg1)
```

**Comment by pferate** [comment]
According to the [Python docs](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaises), this was added in 2.7.

There are some tests that are already using this syntax, so I'm curious to see what's going on there that doesn't have them fail in `py26`.  I will look into this later.

If this is incompatible with 2.6, then this may need to wait until 2.6 support is dropped in September.

**Comment by jonparrott** [comment]
unittest2 probably fixes compatibility.

**Comment by pferate** [comment]
Ahhh, that looks like it.  Thanks.  It will probably be next week before I
could work on it.
