### ISSUE TITLE
Update string formatter syntax

### ISSUE THREAD

**Issue by pferate** [google/oauth2client#541]
Update the old style string formatters to the new style.

Currently there is a mix of usage throughout the code-base, so we should migrate to a consistent style.

[pyformat.info](https://pyformat.info/) has more information.

**Comment by pferate** [comment]
I will work on this next week.  This is for open discussion, but mainly so I don't forget it. :)

**Comment by jonparrott** [comment]
Sounds good, thank you for doing this. In general I prerfer `format`, though @nathanielmanistaatgoogle might have a strong opinion and his opinion wins over mine.

**Comment by dhermes** [comment]
The "old" percent formatting is not entirely "extinguishable" since libraries like `logging` have it built into as sugar for methods

**Comment by nathanielmanistaatgoogle** [comment]
I find the consistency argument persuasive; proceed with this cleanup and thank you for it.

I've forgotten the particular victories won by the new form, but it's new for a reason, right?

**Comment by jonparrott** [comment]
> it's new for a reason, right?

#googlelogic. ;)

**Comment by nathanielmanistaatgoogle** [comment]
Wait, are we not doing this?

**Comment by jonparrott** [comment]
It's been done, the PR just didn't auto-close the issue. :)
