### ISSUE TITLE
oauth2client.tools should not fail when passing unexpected args

### ISSUE THREAD

**Issue by banDedo** [google/oauth2client#544]
An exception is thrown when I use this tool inside of another python program I have written that also uses the argparser.  Should you be using `parse_known_args` rather than `parse_args`?

**Comment by jonparrott** [comment]
Usually I've seen people just use the tools argparser as the parent for their app's parser. Does this solve your use case?

**Comment by banDedo** [comment]
@jonparrott - this solves my use case, but seems dirty from an architectural perspective.  Taking this approach would couple my application to the internals of this package.  Just seems less intrusive with minimal overhead to use the approach I suggested.  I will proceed with your suggestion, but would appreciate consideration of my suggestion in future releases.  Thanks for the timely response, btw!

**Comment by jonparrott** [comment]
I'm happy to review any PR to make it work both ways, if you're willing to contribute?

(I'm closing this for now, but feel free to reference it if you send a PR)

**Comment by banDedo** [comment]
Sounds great, will do :)
