### ISSUE TITLE
`docs` test is failing

### ISSUE THREAD

**Issue by pferate** [google/oauth2client#548]
I noticed that the `docs` test started failing recently for some reason.  It fails during `make html` when it is working on the `contrib.flask_util` part.  

I reran the test in a case that it previously passed, but it failed this time.  This makes me think that the problem is external to `oauth2client`.  On PyPI, `Flask` was last updated on 2016-06-07.

The last tests that passed are from 3 days ago (July 12).

Here is the output I get when running it.

> sphinx-build -b html -d _build/doctrees  -W . _build/html
> Running Sphinx v1.4.5
> making output directory...
> loading pickled environment... not yet created
> building [mo]: targets for 0 po files that are out of date
> building [html]: targets for 29 source files that are out of date
> updating environment: 29 added, 0 changed, 0 removed
> reading sources... [  3%] index
> reading sources... [  6%] source/oauth2client
> reading sources... [ 10%] source/oauth2client.client
> reading sources... [ 13%] source/oauth2client.clientsecrets
> reading sources... [ 17%] source/oauth2client.contrib
> reading sources... [ 20%] source/oauth2client.contrib.appengine
> reading sources... [ 24%] source/oauth2client.contrib.devshell
> reading sources... [ 27%] source/oauth2client.contrib.dictionary_storage
> reading sources... [ 31%] source/oauth2client.contrib.django_orm
> reading sources... [ 34%] source/oauth2client.contrib.django_util
> reading sources... [ 37%] source/oauth2client.contrib.django_util.apps
> reading sources... [ 41%] source/oauth2client.contrib.django_util.decorators
> reading sources... [ 44%] source/oauth2client.contrib.django_util.signals
> reading sources... [ 48%] source/oauth2client.contrib.django_util.site
> reading sources... [ 51%] source/oauth2client.contrib.django_util.storage
> reading sources... [ 55%] source/oauth2client.contrib.django_util.views
> reading sources... [ 58%] source/oauth2client.contrib.flask_util
> 
> Exception occurred:
>   File "/home/pferate/Projects/oauth2client/.tox/docs/local/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
>     raise RuntimeError(_app_ctx_err_msg)
> RuntimeError: Working outside of application context.
> 
> This typically means that you attempted to use functionality that needed
> to interface with the current application object in a way.  To solve
> this set up an application context with app.app_context().  See the
> documentation for more information.
> The full traceback has been saved in /tmp/sphinx-err-6Wkj68.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:53: recipe for target 'html' failed
> make: *** [html] Error 1

**Comment by jonparrott** [comment]
Fixed by #551.
