### ISSUE TITLE
Plan to Implement: oauth2client.transport module

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#554]
FYI @nathanielmanistaatgoogle @jonparrott @waprin I am going to factor out all of the usage of `httplib2` into a standalone module so we can have a clean break when the time comes to use a better maintained library.

I plan to start soon to please weigh in ASAP with any comments or concerns or requests for API surface area.

Also see #128 for a more "detailed" (but old) plan.

**Comment by nathanielmanistaatgoogle** [comment]
No concerns. I think I've heard rumblings about this for a while.

**Comment by txomon** [comment]
Does this mean we will be able to use our own http clients? I am mostly interested on using aiohttp to do async requests.

This sounds like having the functionality of the oauth2 steps separated from the implementation of the transport, but I don't know if it supports the use case I just mentioned.

**Comment by jonparrott** [comment]
@txomon I'm not sure about async transports, but this will certainly make something like that a lot more feasible in the future.

**Comment by txomon** [comment]
Some difficulties I have found until now is that the docs say that
implementing request function is enough but doesn't give a signature nor
clear signature.

Making that a little more flexible is highly appreciated =) Thanks!

**Comment by jonparrott** [comment]
That's the goal. Ultimately we want to support urllib3/requests as the primary transport and deprecate httplib2. To do that, we more or less have to enable users to bring their own http client. Two birds, one stone.

**Comment by dhermes** [comment]
@txomon There are a few more details in #128. The goal is to define an interface that a BYO transport implementation needs to comply with and then just support that. We'll probably have to support the BYO stuff side-by-side with the default `httplib2` stuff for a generation or two.

**Comment by dhermes** [comment]
Calling this complete and moving discussion back to #128
