### ISSUE TITLE
oauth2client method to obtain default credentials does not match order specified in official documentation

### ISSUE THREAD

**Issue by pfritzsche** [google/oauth2client#555]
Code: [https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1359-L1387][1]
Documentation: https://developers.google.com/identity/protocols/application-default-credentials#howtheywork

The documentation at developers.google.com indicates that default credentials will be obtained in the following order:

1. GOOGLE_APPLICATION_CREDENTIALS environment variable
1. gcloud auth settings
1. app engine service account
1. compute engine service account
1. (error)

However, the code works in the following order (per docs on lines 1363-1368 in the link above):

1. app engine service account
1. GOOGLE_APPLICATION_CREDENTIALS environment variable
1. gcloud auth settings
1. compute engine service account
1. (error)

[1]: https://github.com/google/oauth2client/blob/ceafaa7f32df85c3bf967d58886f50806fb5483e/oauth2client/client.py#L1359-L1387

**Comment by jonparrott** [comment]
@anthmgoogle @nathanielmanistaatgoogle @dhermes any qualms about switching the order?

**Comment by jonparrott** [comment]
Bump, if we're going to change it we might as well change it before 3.0.0?

**Comment by anthmgoogle** [comment]
Please do go ahead and switch the order. It is important that this is consistent across languages.
