### ISSUE TITLE
Refactor imports to follow Google's Style Guide

### ISSUE THREAD

**Issue by pferate** [google/oauth2client#556]
There are many import statements throughout the code base that don't follow the [Google Style Guide](https://google.github.io/styleguide/pyguide.html#Imports), in particular `Use imports for packages and modules only`.

One example is in [tests/test_client.py](https://github.com/google/oauth2client/blob/a7cddf20a668be0369f797d9093629fb3dc0c270/tests/test_client.py#L37-L84)

It should be refactored into 
```python
import oauth2client
from oauth2client import _helpers
from oauth2client import client
from oauth2client import clientsecrets
from oauth2client import service_account
from oauth2client import util
```

By adding the module names, we may need to split some of the lines, but it would adhere to the Style Guide.

Also, what is everyone's thoughts on possibly changing the line lengths from 80 to 100 or 120 in the style guide?  I know there are many projects that follow PEP8 with the exception of line length.

**Comment by dhermes** [comment]
:+1: to everything except line length.

**Comment by pferate** [comment]
Question:  When making a line longer than 80 characters, at what point should we go from option 1 (breaking within the parameters) to option 2 (breaking at the open parenthesis)?

For example:
```python
# Original
        flow_from_clientsecrets(filename, None, cache=cache, message=message)
# Option 1: Break within parameters
        client.flow_from_clientsecrets(filename, None, cache=cache,
                                       message=message)
# Option 2: Break at open parenthesis 
        client.flow_from_clientsecrets(
            filename, None, cache=cache, message=message)
```

**Comment by dhermes** [comment]
I don't have very strong feelings on this but @jonparrott and @nathanielmanistaatgoogle do somewhat. It's tough to enforce style like that if it isn't encoded in tooling.

**Comment by nathanielmanistaatgoogle** [comment]
I've gone over to using option 2 exclusively and am very happy with it and would recommend it in all line-wrapping cases.

**Comment by pferate** [comment]
Will do.

What about in this something like this?
```python
            return service_account.ServiceAccountCredentials.from_json_keyfile_name(
                filename, scopes=scopes, token_uri=token_uri,
                revoke_uri=revoke_uri)
```
Should I assign `service_account.ServiceAccountCredentials` to a temporary variable and use that or do you have another suggestion?

**Comment by nathanielmanistaatgoogle** [comment]
What's wrong with the way you've written that? It looks like `return <call expression>` with the call expression appropriately wrapped? Definitely don't introduce a local field.

_Sometimes_ I make a personal decision and choose to separate the positional arguments and the keyword arguments on different lines, but that's when I'm feeling extreme.

**Comment by pferate** [comment]
The `name(` part is over 80 characters.

According to the [style guide](https://google.github.io/styleguide/pyguide.html?showone=Line_length#Line_length), there are 2 exceptions where it is okay to go over 80, and this isn't one of them.

> Exceptions:
> 
> * Long import statements.
> * URLs in comments.

**Comment by nathanielmanistaatgoogle** [comment]
Oh, that. Another reason to never use `@classmethod` and `@staticmethod`. :-P

I'm actually not sure what the most-right solution is, but parentheses and then wrapping after one of the dots should work?

**Comment by pferate** [comment]
Unfortunately, putting a parentheses before or after one of the dots comes up with a syntax error.  In one case, I was able to put a parentheses wrap after the equal sign and had enough room to keep it under 80, but in another case, it was still too long.

I see a few ways to refactor it, but it may be beyond the scope of this PR.

One is to move to function-based fixture, for creating and deleting the temporary file.  This would allow us to remove the try/finally parts, but would still need to be combined with a starting parenthesis to have enough room.

Another way would be to refactor `ServiceAccountCredentials`, but that may be a change for a major release.  `service_account.ServiceAccountCredentials` can probably be changed to `service_account.Credentials`.  Jack Diederich has a good talk on this called [Name Things Once](https://www.youtube.com/watch?v=hZ7hgYKKnF0)

Looking at `from_json_keyfile_name` and `from_json_keyfile_dict`, they may be able to be refactored into `from_json_keyfile` with required keywords of `filename` or `keyfile_dict`.

**Comment by jonparrott** [comment]
Import have been updated, can we close this?

**Comment by pferate** [comment]
@jonparrott, I think so.
