### ISSUE TITLE
Coveralls report not being used

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#558]
As a result coverage has dropped below 100% and sadness for me since #212 was so hard.

See an [example fail][1] when trying to upload the coverage report to coveralls.io:

```
  File "/home/travis/build/google/oauth2client/.tox/coveralls/lib/python2.7/site-packages/nosegae.py", line 91, in configure
    import dev_appserver
ImportError: No module named dev_appserver
```

[1]: https://travis-ci.org/google/oauth2client/jobs/146207674

**Comment by dhermes** [comment]
@jonparrott Do you know if `/home/travis/.cache/google_appengine` needs to be populated in each of the environments? i.e. why does `gae` work just fine but `py27` fails on the coverage report.

Could we "fix" this with a simple cheat of moving the coverage report into `gae` from `py27`?

**Comment by dhermes** [comment]
OK as can be seen in #560 this does fix the import issue and brings back the `coveralls` report.

As seen in the report https://coveralls.io/builds/7092809 we have 97.06% coverage in `oauth2client.contrib.sqlalchemy and 99.37% in `oauth2client.contrib.appengine`.

It looks like there's a branch mass in `contrib.appengine` in the 807-809, 806->807 range and some other missed in `contrib.sqlalchemy` around 150, 144->150, 146->148, 162->165.

**Comment by jonparrott** [comment]
Well the good news is we're not significantly below 100%.

**Comment by dhermes** [comment]
Indeed. Any idea who the owners should be to get back to 100%?

**Comment by jonparrott** [comment]
I can probably handle it sometime in the next month.

**Comment by pferate** [comment]
One of those was me in #533.  I just wrote a test to get the `appengine` part covered.  Haven't looked at the `sqlalchemy` part yet.

I'll look at that after I finish working on my other PR.
