### ISSUE TITLE
Refactor Credentials

### ISSUE THREAD

**Issue by pferate** [google/oauth2client#564]
This started out as a thought to refactoring `oauth2client.service_account.ServiceAccountCredentials` into `oauth2client.service_account.Credentials`.  Now I'm thinking that it may be better to refactor all of the built-in credentials and get all of the `contrib` Credentials in the same format, but I wanted to see what everyone thought of this.

With PR #556 cleaning up the internal namespace, there will now be a smaller chance for name collisions.

A brief look at Credentials currently: (cleaning up output a bit)
```bash
~/Projects/oauth2client$ git grep "^class " oauth2client | grep Credentials
oauth2client/client.py:class Credentials(object):
oauth2client/client.py:class OAuth2Credentials(Credentials):
oauth2client/client.py:class AccessTokenCredentials(OAuth2Credentials):
oauth2client/client.py:class GoogleCredentials(OAuth2Credentials):
oauth2client/client.py:class AssertionCredentials(GoogleCredentials):
oauth2client/service_account.py:class ServiceAccountCredentials(client.AssertionCredentials):
oauth2client/service_account.py:class _JWTAccessCredentials(ServiceAccountCredentials):

oauth2client/contrib/appengine.py:class AppAssertionCredentials(client.AssertionCredentials):
oauth2client/contrib/devshell.py:class DevshellCredentials(client.GoogleCredentials):
oauth2client/contrib/gce.py:class AppAssertionCredentials(client.AssertionCredentials):
```

I propose that we move all of the built-in Credential classes into a `credentials` module like:
```
oauth2client/credentials.py:class Base(object):
oauth2client/credentials.py:class OAuth2(Base):
oauth2client/credentials.py:class AccessToken(OAuth2):
oauth2client/credentials.py:class Google(OAuth2):
oauth2client/credentials.py:class Assertion(Google):
oauth2client/credentials.py:class ServiceAccount(Assertion):
oauth2client/credentials.py:class _JWTAccess(ServiceAccount):
```

And have all contrib Credentials are named `Credentials` and inherit from their appropriate base credential class.
```
oauth2client/contrib/appengine.py:class Credentials(credentials.Assertion):
oauth2client/contrib/devshell.py:class Credentials(credentials.Google):
oauth2client/contrib/gce.py:class Credentials(credentials.Assertion):
```

Obviously, this would be a major change, but I wanted to get your thoughts on this.

To maintain the current external interfaces, we can define the following in `oauth2client/client.py`:
```python
Credentials = credentials.Base
OAuth2Credentials = credentials.OAuth2
AccessTokenCredentials = credentials.AccessToken
GoogleCredentials = credentials.Google
AssertionCredentials = credentials.Assertion
```

**Comment by jonparrott** [comment]
Personally, I'm only okay with really breaking bones in the `contrib` section for now. Once the dust settles, I want to propose a more complete refactor into a new package named `google.auth`.

**Comment by nathanielmanistaatgoogle** [comment]
[I would not be okay with a clean-up that is that dramatic but that retains use of implementation inheritance (especially among library-public classes).](https://www.youtube.com/watch?v=3MNVP9-hglc) I think we should (1) go big or go home and (2) not go home.

Under "I propose" you describe a six-level inheritance hierarchy of public classes (not counting `object`)? That inheritance hierarchy is [too tall](https://www.youtube.com/watch?v=LW4jsfqx7fE).

**Comment by jonparrott** [comment]
I'm going to close this for now. Once the dust settles around 4.0.0, I'd like to discuss a refactor that splits 2lo from 3lo, restructuring the project into `google.auth` (for 2lo) and `google.oauth2` (for 3lo).
