### ISSUE TITLE
How to workaround "token used too late"?

### ISSUE THREAD

**Issue by TheChuckster** [google/oauth2client#568]
Every time one of my users logs in using Google into my Google Android application, I receive the following exception from oauth2client (I censored some of the fields containing the user's sensitive information):
`Jul 25 17:16:24 logger:  Invalid token. Token used too late, 1469492184 > 1469491676: {u'picture': u'', u'aud': u'', u'family_name': u'', u'iss': u'', u'email_verified': True, u'name': u'', u'locale': u'en', u'given_name': u'', u'exp': 1469491376, u'azp': u'', u'iat': 1469487776, u'email': u'', u'sub': u''} `

Here is the relevant snippet (more or less the sample code for oauthclient2 Google auth):
```
try:
    idinfo = client.verify_id_token(token, client_id)

    if idinfo['aud'] not in GOOGLE_CLIENT_ID_LIST:
        raise crypt.AppIdentityError("Unrecognized client: " + idinfo['aud'])
    if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
        raise crypt.AppIdentityError("Wrong issuer: " + idinfo['iss'])
except crypt.AppIdentityError as e:
    logging.error('Invalid token. ' + str(e))
```

If she restarts the app and tries again, the error still occurs but with different timestamps. She has tried at least 10 times.

I am passing the token from my Android application to my backend for verification.

I'm using a fairly standard piece of client-side code that simply grabs the id token from the GoogleSignInAccount from the result (also more or less the sample code for Android Google auth):
```
private void handleSignInResult(GoogleSignInResult result) {
    if (result.isSuccess()) {
        GoogleSignInAccount acct = result.getSignInAccount();
        String login_message = "token=" + acct.getIdToken() + "&platform=android";
        AsyncHttpURLConnection httpConnection = new AsyncHttpURLConnection("POST", BASE_MATCHMAKING_API_URL + GOOG_LOGIN_ENDPOINT, login_message, http_login_events);
        httpConnection.setContentType("application/x-www-form-urlencoded");
        httpConnection.send();
    } else {
        showLoginError(); // Signed out, show unauthenticated UI.
    }
}
```

What could be causing the token to be "used too late" if the API call is getting called almost immediately after I get the sign in result from the Google Android API? I haven't been able to reproduce the problem locally.

I don't think I'm doing anything too crazy -- most of my code comes directly off the API documentation/sample code from Google listed here for Python:
https://developers.google.com/identity/sign-in/android/backend-auth

My backend server is using UTC time, but the users' Android phones could be using other local timezones.

Example calls from this user:
```
Token used too late, 1469492184 > 1469491676 
Token used too late, 1469492208 > 1469491676 
Token used too late, 1469492247 > 1469491676 
Token used too late, 1469492292 > 1469491676 
Token used too late, 1469492342 > 1469491676 
Token used too late, 1469492396 > 1469491676 
Token used too late, 1469492440 > 1469491676 
Token used too late, 1469492464 > 1469491676 
Token used too late, 1469492481 > 1469491676 
Token used too late, 1469492594 > 1469491676 
Token used too late, 1469492654 > 1469491676 
Token used too late, 1469492852 > 1469491676 
Token used too late, 1469493035 > 1469491676 
Token used too late, 1469493581 > 1469491676 
Token used too late, 1469493756 > 1469491676 
Token used too late, 1469494014 > 1469491676 
Token used too late, 1469494133 > 1469491676 
Token used too late, 1469494141 > 1469491676 
Token used too late, 1469494275 > 1469491676
```

It looks like this token just isn't getting refreshed on the client?

**Comment by dhermes** [comment]
Are you using UTC time on the Android client?

**Comment by jonparrott** [comment]
(Side note: since this is more android and oauth2 service related than directly related to the client, you may have more luck asking this on StackOverflow)

**Comment by jonparrott** [comment]
> Hopefully some Googlers from service land inhabit it.

Our support engineers monitor stackoverflow, whereas here it's just a handful of maintainers. :)

**Comment by TheChuckster** [comment]
@dhermes Thanks for the tip. Without too much familiarity with oauth2 and Google's Java Android client, I'm not seeing any way of passing in a timestamp, so I am assuming the `GoogleApiClient` uses UTC time "under the hood" (yeah, I know the saying...)?

I'm not doing anything crazy in my Android app's code to override the timezone or anything in _my_ application, so _hopefully_ the `GoogleApiClient` internals do the sane thing and use UTC time.

**Comment by dhermes** [comment]
Yes my previous comment was before I realized you were using that library. It's possible that the local time on the device is out of sync (or on the server verifying the token). Can you check that they are correct?
