### ISSUE TITLE
oauth2client/client.py pwd '~' does not work in GoogleAppEngine

### ISSUE THREAD

**Issue by vit0r** [google/oauth2client#587]
Error “ImportError: No module named pwd”

line 1392 -> default_config_dir = os.path.join(os.path.expanduser('~'),'.config',_CLOUDSDK_CONFIG_DIRECTORY) 

change:

os.path.expanduser('~') to os.environ['HOME']

**Comment by jonparrott** [comment]
This is a duplicate of #578. There are details and workarounds in that issue. Please comment there if your isn't isn't resolved.

**Comment by vit0r** [comment]
Ok tank's .
