### ISSUE TITLE
Middleware check fails with Django 1.10

### ISSUE THREAD

**Issue by huwshimi** [google/oauth2client#593]
In Django 1.10 the middleware setting has been changed from `MIDDLEWARE_CLASSES` to `MIDDLEWARE` however, in django_util the check to see if `SessionMiddleware` is included in the middleware only checks the old `MIDDLEWARE_CLASSES`. See:

https://github.com/google/oauth2client/blob/cd825cc561170be36509d32f5fc23fcbeb4c0f12/oauth2client/contrib/django_util/__init__.py#L342

For details of the update see: https://docs.djangoproject.com/en/1.10/topics/http/middleware/#middleware

**Comment by waprin** [comment]
Ah thanks for the report, will fix today.

**Comment by waprin** [comment]
@huwshimi please re-open if #623 does not fix the issue and thanks again for report.

**Comment by huwshimi** [comment]
@waprin no worries, thanks for fixing it so quickly!
