### ISSUE TITLE
PyPy tests fail after first run

### ISSUE THREAD

**Issue by pferate** [google/oauth2client#596]
Looks like this was introduced in #590.

Travis was configured to cache the `.pyenv` directory between builds and cloning the repo fails if the directory is not empty.

We have a few options on how to proceed:

1. Not cache the directory between builds (the previous behavior)
2. Only clone the `pyev` repo if the directory doesn't exist (similar to App Engine SDK)

**Comment by jonparrott** [comment]
Fixed by #595.

**Comment by pferate** [comment]
@jonparrott Looks like Travis creates the cached directories if they don't exists, so the check in #595 didn't work for me.  Created #630.
