### ISSUE TITLE
Should we use a more generic transport for _detect_gce_environment()

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#599]
The current [source][1] uses the core `httplib` / `http.client` machinery to get the info.

1.  The original reason we used the low-level library is because the timeout in `httplib2` was taking too long. This may no longer be an issue, i.e. if the GCE check is the last one
1.  It should probably use `oauth2client.contrib._metadata` utils

I'm filing this because after #586 all requests (except for this one) are "guaranteed" to pass through the `transport.request` method

[1]: https://github.com/google/oauth2client/blob/b1a17432731344d2e44b1ef78ab52f2202bee703/oauth2client/client.py#L995-L1022

**Comment by jonparrott** [comment]
Yes. Let's.
