### ISSUE TITLE
Deprecate allowing http OR http.request in transport.request

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#601]
We [allow](https://github.com/google/oauth2client/blob/b1a17432731344d2e44b1ef78ab52f2202bee703/oauth2client/transport.py#L278) `http` OR `http.request` as the first argument to `transport.request` to support callers of non-public methods (e.g. `_refresh` or `_revoke`) that passed `http.request` instead of `http` (from `httplib.Http` objects).

This should be more restrictive but we should support both to avoid breakage.

**Comment by dhermes** [comment]
FYI I created this to reference it from #602

**Comment by jonparrott** [comment]
I'd say let's rip the band-aid off and remove the argument all together. But @nathanielmanistaatgoogle might disagree.

**Comment by nathanielmanistaatgoogle** [comment]
No disagreement... but I don't yet entirely understand how removing the argument altogether would work?

**Comment by jonparrott** [comment]
Since the transport library can handle all of the http stuff itself, there's no need to pass http objects into `refresh()`, etc.

**Comment by dhermes** [comment]
I don't see how the world @jonparrott keeps talking about could work, but I'm not closed off to the idea.

**Comment by jonparrott** [comment]
Haha. Okay, yeah, let me think of a better way to explain this.

**Comment by jonparrott** [comment]
We can move this discussion to #128 if needed, but what I'm getting at is this:

Presently, several methods on `Credentials` takes `http` as parameter:

* `authorize()`
* `get_access_token()`
* `refresh()`
* `retrieve_scopes()`
* `revoke()`

I'm proposing we go ahead and remove the `http` parameter from everything but authorize. The necessary methods should just call `transport.request(uri, method, ...)`. Transport should handle getting an appropriate http object to make the request.

`authorize()`'s http argument should eventually be changed to support other http libraries, but can just work with httplib2 for now.

**Comment by dhermes** [comment]
Let's discuss on #128. I don't think that will make people happy, unless they can toggle a switch on `oauth2client.transport` to make it use their desired transport under the covers.

**Comment by jonparrott** [comment]
Raising this from the dead, I'm gonna remove the ability to pass `httplib2.Http.request` instead of just and `httplib2.Http`. Might as well do it since it's a major version change.

**Comment by jonparrott** [comment]
(Also it allows me to restrict and solidify the interface)

**Comment by jonparrott** [comment]
On second thought this may just be an implementation detail of the httplib2 transport. I'll revisit later.

**Comment by dhermes** [comment]
> implementation detail of the httplib2 transport

Indeed. I left it in there to avoid breaking people who had used the private methods and passed `http.request`. As far as the public interface, no one should be passing `http.request` instead of `http`.

**Comment by jonparrott** [comment]
@dhermes so right now the only times this occurs that I can tell is when the transport itself passes `orig_request` in during the replacement `request` function.

I'm leaning towards the "http object" being completely opaque to all of oauth2client except for the transport. So in the case of httplib2 transport there's two valid http objects, but for urllib3 that might not be the case. :)

**Comment by dhermes** [comment]
> so right now the only times this occurs that I can tell is when the transport itself passes `orig_request` in during the replacement `request` function.

Yes. I really wanted to eliminate that in the unit tests but couldn't find a good way, though I toyed around with making a `__call__`-able class for those wrapped `http.request` values.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
