### ISSUE TITLE
Drop support for Python 3.3

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#603]
gcloud-python, django, and many libraries have both dropped support for 3.3. Is there anything preventing us from doing the same?

@thobrla ?

**Comment by nathanielmanistaatgoogle** [comment]
I'm not aware of anything binding us to it and 3.3 almost four years old.

**Comment by thobrla** [comment]
No complaints from gsutil, we don't support Python 3 at all yet, and will likely support a later version once we do.

**Comment by pferate** [comment]
Good timing, I guess.  Two days ago, I started seeing problems related to the 3.3 tests not skipping the Django tests, but it was limited to just my fork (it passed on the main repo).  Then today, @bjmc started seeing the same problems bleeding into the main repo.
