### ISSUE TITLE
Does py.test have branch coverage

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#611]
@pferate Can you chime in here? It seems the `sqlalchemy` branch miss has been fixed without being fixed and I don't see anything in the coverage report about branches.

**Comment by pferate** [comment]
From my initial poking around, I don't see any mention of branch coverage.  I'll keep digging.

**Comment by dhermes** [comment]
Thanks. That's a big downgrade in terms of measuring code coverage.

**Comment by pferate** [comment]
Nevermind, I found something.

**Comment by dhermes** [comment]
Hooray! :tada:
