### ISSUE TITLE
flake8 should only inspect files in the repository

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#613]
/cc @pferate

**Comment by jonparrott** [comment]
I'm not sure if there's a good way to do this. flake8 doesn't seem to have an 'include' option.

**Comment by dhermes** [comment]
Same with `pep8`. I just wrote a wrapper by hand for `gcloud-python`

**Comment by pferate** [comment]
I suppose you could use a pre-commit hook.

**Comment by dhermes** [comment]
That won't change the set of files that `flake8` sees

**Comment by jonparrott** [comment]
Link to your wrapper? 

The more complicated `tox.init` gets the more inclined I am to replace it with `nox`.

**Comment by dhermes** [comment]
https://github.com/GoogleCloudPlatform/gcloud-python/blob/a99f269f5571fad28d9272b84698745d3e472fac/scripts/pycodestyle_on_repo.py

**Comment by pferate** [comment]
@jonparrott You just want to use `nox` since you wrote it, huh?  :smirk:

**Comment by jonparrott** [comment]
@pferate I wrote nox because of my burning hatred for tox - once app engine or tricky environments get thrown into the mix tox just falls apart.

**Comment by jonparrott** [comment]
@dhermes thanks - we could do that with a nox session pretty easily. I'm going to think on whether I want to switch this project over. In the meantime I'm going to just continue adding ignore stuff to the flake8 config... (ugh).

**Comment by pferate** [comment]
haha, I just went to the docs for `nox` (`nox dox`?) to learn more about it and I saw your name at the bottom, then I confirmed it at GitHub.

**Comment by jonparrott** [comment]
> nox dox

I still want to change the woodcut from alice to a fox so it can be the nox docs fox.

**Comment by pferate** [comment]
That would rox, I mean rock.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
