### ISSUE TITLE
Remove __author__ from all files

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#626]
Might be worth putting a section in `CONTRIBUTING` giving a shout to all the author's over time?

**Comment by jonparrott** [comment]
Please just add a [CONTRIBUTORS.txt](https://github.com/shazow/urllib3/blob/master/CONTRIBUTORS.txt).

**Comment by dhermes** [comment]
Whoever fixes this issue totes should :grinning:

**Comment by jonparrott** [comment]
I can be the baddie that does this.

![arewethebaddies](https://cloud.githubusercontent.com/assets/250995/17603791/9de3b708-5fc7-11e6-8e64-c80f5d759b3d.gif)
