### ISSUE TITLE
Pycrypto breaks oauth2client 2.2.0

### ISSUE THREAD

**Issue by pgcd** [google/oauth2client#638]
When pycrypto (2.6.1) is installed, `oauth2client.crypt.make_signed_jwt` ends up causing:

`AttributeError: _RSAobj object has no '_randfunc' attribute`

Removing pycrypto fixes the problem, but it's not feasible in some cases (mine, for instance).

**Comment by dhermes** [comment]
@pgcd I just tried to reproduce and can't.

```python
>>> import os
>>>
>>> import Crypto
>>> import oauth2client
>>> import oauth2client._helpers
>>> import oauth2client.crypt
>>> from oauth2client.service_account import ServiceAccountCredentials
>>>
>>> print(oauth2client.__version__)
3.0.0
>>> print(Crypto.__version__)
2.6.1
>>> oauth2client.crypt.Signer = oauth2client.crypt.PyCryptoSigner
>>> oauth2client.crypt.Verifier = oauth2client.crypt.PyCryptoVerifier
>>>
>>> key_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
>>> credentials = ServiceAccountCredentials.from_json_keyfile_name(key_path)
>>> signed_jwt = oauth2client.crypt.make_signed_jwt(
...     credentials._signer, {'foo': 'bar'})
>>>
>>> header, body, _ = signed_jwt.split('.')
>>> oauth2client._helpers._urlsafe_b64decode(header)
'{"alg":"RS256","typ":"JWT"}'
>>> oauth2client._helpers._urlsafe_b64decode(body)
'{"foo":"bar"}'
```

**Comment by pgcd** [comment]
I confirm that your code works on my system too, but mine is still breaking - here's the full traceback:

> Traceback (most recent call last):
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "./spaces/views.py", line 953, in dispatch
>     return super(AttachCalendarView, self).dispatch(request, *args, **kwargs)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
>     return handler(request, *args, **kwargs)
>   File "./spaces/views.py", line 980, in post
>     success = calendar.update_events()
>   File "./spaces/models.py", line 1286, in update_events
>     timeMin=timezone.now().isoformat()).execute()
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/googleapiclient/http.py", line 833, in execute
>     method=str(self.method), body=self.body, headers=self.headers)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/googleapiclient/http.py", line 160, in _retry_request
>     resp, content = http.request(uri, method, *args, **kwargs)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/client.py", line 616, in new_request
>     self._refresh(request_orig)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/client.py", line 885, in _refresh
>     self._do_refresh_request(http_request)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/client.py", line 900, in _do_refresh_request
>     body = self._generate_refresh_request_body()
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/client.py", line 1611, in _generate_refresh_request_body
>     assertion = self._generate_assertion()
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/service_account.py", line 396, in _generate_assertion
>     key_id=self._private_key_id)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
>     signature = signer.sign(signing_input)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/oauth2client/_pycrypto_crypt.py", line 101, in sign
>     return PKCS1_v1_5.new(self._key).sign(SHA256.new(message))
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/Crypto/Signature/PKCS1_v1_5.py", line 112, in sign
>     m = self._key.decrypt(em)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 174, in decrypt
>     return pubkey.pubkey.decrypt(self, ciphertext)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/Crypto/PublicKey/pubkey.py", line 93, in decrypt
>     plaintext=self._decrypt(ciphertext)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 235, in _decrypt
>     r = getRandomRange(1, self.key.n-1, randfunc=self._randfunc)
>   File "/home/ubuntu/project/local/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 126, in __getattr__
>     raise AttributeError("%s object has no %r attribute" % (self.__class__.__name__, attrname,))
> AttributeError: _RSAobj object has no '_randfunc' attribute

The non-library line of code is:
```
                event_list_data = service.events().list(calendarId=self.source_id,
                                                        timeMin=timezone.now().isoformat()).execute()

```
where `service` consists of:
```
    http_auth = credentials.authorize(Http())
    return build("calendar", "v3", http=http_auth)

```
(using the object's stored credentials).

I have been trying to figure out if the problem has something to do with the actual credentials being stored (I had some trouble with older pickle()d credentials causing exceptions after the update from 1.x to 2,2), to no avail.

**Comment by dhermes** [comment]
ISTM that the `pickle()` or other serialization is changing your key. The `_RSAobj` comes from the signer

```python
>>> credentials._signer
<oauth2client._pycrypto_crypt.PyCryptoSigner at 0x7fa3424d68d0>
>>> rsa_obj = credentials._signer._key
>>> rsa_obj
<_RSAobj @0x7fa342518fc8 n(2048),e,d,p,q,u,private>
>>> isinstance(rsa_obj, Crypto.PublicKey.RSA._RSAobj)
True
```

You should dig down in the object and compare the values when deserialized vs. when running the snippet I provided

```python
>>> rsa_obj.__dict__
{'_randfunc': <bound method RNGFile.read of <Crypto.Random._UserFriendlyRNG.RNGFile object at 0x7fa340134c50>>,
 'implementation': <Crypto.PublicKey.RSA.RSAImplementation at 0x7fa345d6bb90>,
 'key': <rsaKey at 0x7fa340130030>}
>>> rsa_obj.implementation.__dict__
{'_current_randfunc': None,
 '_default_randfunc': None,
 '_math': <module 'Crypto.PublicKey._fastmath' from '/usr/local/lib/python2.7/dist-packages/Crypto/PublicKey/_fastmath.so'>,
 'error': _fastmath.error}
>>> rsa_obj._randfunc.__self__
<Crypto.Random._UserFriendlyRNG.RNGFile at 0x7fa340134c50>
```

**Comment by pgcd** [comment]
After some debugging, it looks like the culprit is actually `oauth2client.contrib.django_orm.CredentialsField` (I am using 2.2.0, but the code is identical to 3.0.0 as far as the `to_python()` method is concerned). 
As far as I can tell, the `pickle.loads()` method used there does not restore `_RSAobj._randfunc` (that is normally added during the `__init__()`) - subclassing the CredentialsField to forcibly add it prevents the errors, but it looks way too much of a hack for me to believe it can be an accepted solution.
Anyway, I guess this issue is no longer correct as it is - I can edit the title to address the real culprit (ie. the unpickling in CredentialsField) but maybe it's saner to close it and create a different one - especially since using pickle leads to other problems, like the errors due to packages moving around...

**Comment by jonparrott** [comment]
Are private key-based credentials supposed to be picklable? Is this another form of the copy issue?

**Comment by dhermes** [comment]
Appending on the end of my example above, it's clear that the `_randfunc` doesn't survive pickling:

```python
>>> import base64
>>> import pickle
>>>
>>> from django.utils import encoding
>>>
>>> creds_pickled = encoding.smart_text(
...     base64.b64encode(pickle.dumps(credentials)))
>>> creds_unpickled = pickle.loads(
...     base64.b64decode(encoding.smart_bytes(creds_pickled)))
>>> rsa_obj_unpickled = creds_unpickled._signer._key
>>> rsa_obj_unpickled.__dict__
{'implementation': <Crypto.PublicKey.RSA.RSAImplementation at 0x7f94dc0d51d0>,
 'key': <rsaKey at 0x7f94dbf85e30>}
```

**Comment by dhermes** [comment]
I take it back, the key issue is that the pickle helper [`__setstate__` in 2.6.1][1] forgets to [add back the `_randfunc`][2].

[1]: https://github.com/dlitz/pycrypto/blob/v2.6.1/lib/Crypto/PublicKey/RSA.py#L277-L294
[2]: https://github.com/dlitz/pycrypto/blob/7acba5f3a6ff10f1424c309d0d34d2b713233019/lib/Crypto/PublicKey/RSA.py#L302-L303

**Comment by dhermes** [comment]
UPDATE: This was [fixed][1] in 2012 and even made it in the 2.7a1 release but not into 2.6.1.

[1]: https://github.com/dlitz/pycrypto/commit/db52ac71e804e85ace3edd772d2e78055972ac2c

**Comment by pgcd** [comment]
Since it seems confirmed that `pycrypto` is responsible (and 2.7a1 has been committed 3 years ago with no sign of release anytime soon), I think the best way to deal with this would be to allow us to not use `pycrypto` even when it's installed.
Anyway, if anybody stumbles here, what I've decided to do so that I can keep my app running until there's a real fix (btw - installing `PyOpenSSL` makes it apparently worse, since its objects can't be pickled at all) is this:

```
class RobustCredentialsField(CredentialsField):
    def to_python(self, value):
        try:
            credentials = super(RobustCredentialsField, self).to_python(value)
            try:  # Pycrypto 2.6.1 unpickler forgets this, so...
                credentials._signer._key._randfunc
            except AttributeError:
                credentials._signer._key._randfunc = random.Random.new().read
            return credentials
        except:  # Deal with *other* unpickling problems, like obsolete references etc.
            return None
```
It's a very very ugly hack, but I couldn't find any other way of a) preventing errors due to credentials created with 1.x from crashing entirely when unpickled with 2.x, and b) preventing errors with missing _randfunc.

**Comment by dhermes** [comment]
@pgcd There are [3 signers][1]: PyCrypto, PyOpenSSL, pure-Python RSA (in order of precedence). You can use neither and just use the pure-Python implementation:

```python
oauth2client.crypt.Signer = oauth2client.crypt.RsaSigner
oauth2client.crypt.Verifier = oauth2client.crypt.RsaVerifier
```

As for removing PyCrypto support, that isn't likely to happen / necessary. I recommend you don't use pickle for serialization. Each credentials class has a `to_json()` / `from_json()` for serialization.

[1]: https://github.com/google/oauth2client/blob/9f0618d53481a3afe2d0cf232131ba21dcf583de/oauth2client/crypt.py#L63-L71

**Comment by pgcd** [comment]
Thanks for the hint regarding how to change the signer/verifier.
On the other hand, using pickle is not a choice I made: https://github.com/google/oauth2client/blob/master/oauth2client/contrib/django_util/models.py uses pickle, and I don't really feel safe changing the whole implementation & tests with the time budget I am currently working with.

**Comment by dhermes** [comment]
D'oh! My bad. LMK how using the RSA signer/verifier goes.

**Comment by jonparrott** [comment]
@pgcd I'm curious as to why you're storage private-key based credentials? You shouldn't need to store them as all you need is the private key file to re-create them.

**Comment by pgcd** [comment]
@jonparrott I am using the same model to store both public and private calendars, so I added a `get_own_service()` method that picks the credentials and returns the service. I could do without storing the service account credentials, I guess, but it doesn't actually hurt to store them, does it?
Also, the unpickling problems would be there (have actually been there) for the private ones, so...

**Comment by jonparrott** [comment]
>  but it doesn't actually hurt to store them, does it?

I think this issue is proof that it does hurt a little. :) 

I was actually thinking once we refactor I would make these kind of credentials explicitly unserializable, but I haven't made up my mind.

**Comment by pgcd** [comment]
> I think this issue is proof that it does hurt a little. :)

@jonparrott well yes, it does because it's another failing point, but the broken unpickling seems to be there for private credentials too, and I don't really see how I can operate on my users' calendars if I can't store them - if there's an alternative to serialization that allows offline access, I'd be very happy to know more.

**Comment by jonparrott** [comment]
We should definitely fix the unpickling for access token credentials.

**Comment by jonparrott** [comment]
@pgcd do you have any code that can reproduce the pickling error for non-private key credentials? If so, I can make it a test and try to fix it.

**Comment by pgcd** [comment]
@jonparrott As far as I can tell, there are two types of errors caused by pickling:
- When a module's name or path changes between versions, retrieving credentials created with the previous version raises `AttributeError`. For instance, going from 1.x to 2.x made credentials unreadable with `AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'` - in my case this happens both to private and non-private credentials but it may well be just an implementation artifact.
- For non-private credentials (which, as you point out, I could do without serializing), the problem is what @dhermes describes in https://github.com/google/oauth2client/issues/638#issuecomment-243583719

Unfortunately I don't know pickle's internals well enough to craft a working example of the first case; to write my own test I had to dump a failing DB row and use it to prepare the broken credentials, and I'm not entirely comfortable sharing that on GitHub. 
For the second case, I used @dhermes' code for my own test, so no actual code I can provide there either.

Sorry I can't be any more help.

**Comment by jonparrott** [comment]
there's probably nothing non-hacky we can do about (1), other than eventually just move away from pickling. (2) seems isolated to just private-key based credentials.

**Comment by jonparrott** [comment]
@dhermes what do you think we should do with this issue? :/

**Comment by dhermes** [comment]
Close it and leave it as a resource the PyCrypto has a bug in `__setstate__` in the latest released version on PyPI.

**Comment by jonparrott** [comment]
SGTM.
