### ISSUE TITLE
return_url might be None

### ISSUE THREAD

**Issue by letsmakesense** [google/oauth2client#640]
Hi, 

in .contrib.django_util.views.py on line 182 the variable 'return_url' is None if no GET value is given for 'return_url, which will cause a type error. 

A default for return_url is provided later in line 187. Would it be possible to move this default to line 172?

`
return_url = request.GET.get('return_url', request.META.get('HTTP_REFERER', '/'))
`

Regards,
Peter

**Comment by jonparrott** [comment]
@waprin will take a look at this once he gets back from vacation. :)

**Comment by pferate** [comment]
@jonparrott: Looks like this was resolved in #651

**Comment by jonparrott** [comment]
Great. :)
