### ISSUE TITLE
Loading from P12 broken on Python 3

### ISSUE THREAD

**Issue by msaniscalchi** [google/oauth2client#657]
Loading credentials from a P12 file via `oauth2client.service_account.ServiceAccountCredentials.from_p12_keyfile` is broken in Python 3. The relevant portion of the stacktrace is:

```
...
  File "/usr/local/lib/python3.4/dist-packages/oauth2client-3.0.0-py3.4.egg/oauth2client/service_account.py", line 334, in from_p12_keyfile
    token_uri=token_uri, revoke_uri=revoke_uri)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client-3.0.0-py3.4.egg/oauth2client/service_account.py", line 291, in _from_p12_keyfile_contents
    private_key_password)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client-3.0.0-py3.4.egg/oauth2client/_openssl_crypt.py", line 119, in from_string
    pkey = crypto.load_pkcs12(key, password).get_privatekey()
TypeError: must be str, not bytes
```

I've followed the stacktrace to `_openssl_crypt.py's OpenSSLSigner.from_string` method and noticed that the [password defaults to bytes](https://github.com/google/oauth2client/blob/master/oauth2client/_openssl_crypt.py#L100) and is also [converted to bytes](https://github.com/google/oauth2client/blob/master/oauth2client/_openssl_crypt.py#L118) (if it isn't already). This results in the TypeError when it is passed along to [get the private key](https://github.com/google/oauth2client/blob/master/oauth2client/_openssl_crypt.py#L119).

The issue appears to be resolved if we don't force the password to be bytes, e.g.:

```
    @staticmethod
    def from_string(key, password='notasecret'):
        key = _helpers._to_bytes(key)
        parsed_pem_key = _helpers._parse_pem_key(key)
        if parsed_pem_key:
            pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)
        else:
            pkey = crypto.load_pkcs12(key, password).get_privatekey()
        return OpenSSLSigner(pkey)
```

I've verified that this works in Python 3, and doesn't seem to introduce any issues to Python 2.

**Comment by dhermes** [comment]
This is a surprise, since this project has system tests which check if a P12 key works that run on every checkout.

**Comment by dhermes** [comment]
@msaniscalchi ASIDE: Why are you still using PKCS12/P12 keys? Google hasn't endorsed / supported them for years and JSON keys have much more information in them.

**Comment by msaniscalchi** [comment]
Because I own the [Google Ads Python Client Library](https://github.com/googleads/googleads-python-lib), which is only now in the process of transitioning from 1.4.12 to the latest version due to... reasons. :-)

While we will recommend JSON key files going forward, we plan to support both for the time being.

**Comment by dhermes** [comment]
Gotcha. Well P12 support has not been DERP-recated yet in this library so hopefully someone can help sort it out.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
