### ISSUE TITLE
question about Storage and its (over)writing properties

### ISSUE THREAD

**Issue by romunov** [google/oauth2client#658]
My model `UserAddress` holds user address fields as well as `credentials` where token from social authentication is stored. I noticed when the token is refreshed

``` python
storage = Storage(UserAddress, 'id', request.user, 'credentials')
storage.put(credential)
```

it blanks all other fields and a fresh token is written. Is this intended? If so, what would be the recommended way of storing user credentials for social authentication? Into a separate table?

**Comment by jonparrott** [comment]
@romunov which storage are you using? There are several.

**Comment by romunov** [comment]
Sorry, this is my import statement:

```from oauth2client.contrib.django_orm import Storage```

**Comment by jonparrott** [comment]
Thanks for clarifying, @romunov.

@waprin any ideas on this?

**Comment by waprin** [comment]
@romunov missed this message ,do you still have this issue? this was a known issue that should now be fixed. Closing this, but if you still have this problem please re-open and  @ mention me.
