### ISSUE TITLE
question concerning django_util

### ISSUE THREAD

**Issue by rjschwei** [google/oauth2client#661]
Hi,

I am trying to get the tests to work in a package build in OBS (openSUSE Build Servive) but am running out of ideas about whats going on.

The message I get is as follows:
ERROR: Failure: ImproperlyConfigured (Requested setting GOOGLE_OAUTH2_SCOPES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.)
....
Followed by a traceback

It appears that this is triggered by the following code snippets in contrib/django_util/__init__.py

        self.scopes = getattr(settings_instance, 'GOOGLE_OAUTH2_SCOPES',
                              GOOGLE_OAUTH2_DEFAULT_SCOPES)
        self.request_prefix = getattr(settings_instance,
                                      'GOOGLE_OAUTH2_REQUEST_ATTRIBUTE',
                                      GOOGLE_OAUTH2_REQUEST_ATTRIBUTE)

these are in the __init__method for the OAuth2Settings() class, which in turn is instantiated by

oauth2_settings = OAuth2Settings(django.conf.settings)

on line 352.

This happens with Django 1.9.9 and I take it that at some point an incompatibility was introduced in Django that triggers this issue.

If I go in and turn the instantiation into

oauth2_settings = OAuth2Settings(django.conf.settings.configure())

which should appease django, and apparently it does I end up with the following new message:

ERROR: Failure: ImproperlyConfigured (Must specify either GOOGLE_OAUTH2_CLIENT_SECRETS_JSON, or both GOOGLE_OAUTH2_CLIENT_ID and GOOGLE_OAUTH2_CLIENT_SECRET in settings.py)

Which appears to stem from _get_oauth2_client_id_and_secret() in contrib/django_util/__init__.py. So this would appear to indicate that during testing a "settings.py" file is used that does not have the proper configuration?

A couple of questions:
Is the change to the instantiation of OAuth2Settings() the proper approach?
How do the tests pick up a settings.py file to make Django happy?

**Comment by rjschwei** [comment]
And one more thing, even if I remove tests/contrib/django_util, i.e. do no django testing I get a failure that is django related:

======================================================================
 ERROR: Failure: ImproperlyConfigured (Must specify either GOOGLE_OAUTH2_CLIENT_SECRETS_JSON, or both GOOGLE_OAUTH2_CLIENT_ID and GOOGLE_OAUTH2_CLIENT_SECRET in settings.py)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
     addr.filename, addr.module)
   File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
     return self.importFromDir(dir_path, fqname)
   File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
     mod = load_module(part_fqname, fh, filename, desc)
   File "/home/abuild/rpmbuild/BUILD/oauth2client-3.0.0/oauth2client/contrib/django_util/__init__.py", line 351, in <module>
     oauth2_settings = OAuth2Settings(django.conf.settings.configure())
   File "/home/abuild/rpmbuild/BUILD/oauth2client-3.0.0/oauth2client/contrib/django_util/__init__.py", line 339, in __init__
     _get_oauth2_client_id_and_secret(settings_instance)


Thus it appears that some other test is pulling in django related functionality. Unfortunately I was unable to pin point this, other ideas?

I am executing the tests with "nosetests"

**Comment by jonparrott** [comment]
@rjschwei you can't just run nosetests, you'll need to use `tox` instead - tox handles installing test dependencies and setting up appropriate environment variables for the tests.

**Comment by rjschwei** [comment]
Thanks
