### ISSUE TITLE
question concerning transition to multiprocess_file_storage

### ISSUE THREAD

**Issue by rjschwei** [google/oauth2client#664]
Hi,

Dealing with code that uses multistore_file and I am trying to convert it to use multiprocess_file_storage. It appears that some of the utility functions did not make it across the transition?

In this case I am trying to figure out how to handle:

get_all_credential_keys(filename)

Is there any documentation that I missed that details the transition from multistore_file to multiprocess_file_storage?

Thanks

**Comment by jonparrott** [comment]
@rjschwei it was intentionally not included. If you have a strong use case for it, we can consider adding it back.

**Comment by rjschwei** [comment]
@jonparrott well google-cloud-sdk uses this function and I have no idea how I would otherwise get there. It would appear to me to be reasonable to have this functionality carried forward to allow client code to iterate over all keys in the store.

**Comment by jonparrott** [comment]
@rjschwei what does the cloud SDK use it for? The credentials file is just a JSON file, so you can always manually read it.

Barring that, I'm open to reviewing a PR to add it.

**Comment by rjschwei** [comment]
@jonparrott, Well to a certain degree I get the "it's just a json file" argument. On the other hand one could then argue that the abstraction of the file into MultiprocessFileStorage is not really necessary at all. However, since the abstraction deals with locking etc. it is IMHO very useful. It just appears, and I am new to the code base, that there was a fundamental shift in the basic abstraction. The new storage class does not abstract the file itself, as _MultiStore() did, but rather the new approach is to abstract the credential since the new implementation requires the credential key for initialization.

So I am not certain how to bridge the gap between the different abstraction levels, and no being familiar with the code base I am wondering if I am missing something fundamentally that should possibly obvious but I am just being stupid about the problem.

**Comment by jonparrott** [comment]
Yes, the new module is fundamentally different on purpose.

What problem are you trying to solve by getting all of the keys?

**Comment by rjschwei** [comment]
Others did the porting thus this question has kind of obsoleted itself by me being busy with other things. 

Thanks.
