### ISSUE TITLE
django_sample issue

### ISSUE THREAD

**Issue by jayanth1991** [google/oauth2client#671]
Tried following the django sample, upon logging in, django automatically redirects to `accounts/profile/` following this line:
https://github.com/google/oauth2client/blob/master/samples/django/django_user/myoauth/urls.py#L28

The sample won't work as expected.

**Comment by jonparrott** [comment]
@waprin any thoughts?

**Comment by waprin** [comment]
Thanks for report, can I see your settings.py config, models you're using, and version of Python and Django?

**Comment by waprin** [comment]
For settings.py, just the parts relevant to the oauth2 config.

**Comment by jayanth1991** [comment]
I just downloaded the current master branch and ran the sample code, so its the same as what is available in the repo. Here are the steps to replicate it the issue:

Django Version: 1.10

1)
```sh
$ pip install -r requirements.txt
$ python manage.py migrate
$ python mange.py createsuperuser // Create a user 
$ python manage.py runserver
```
2) Once you start the server, go to `http://<server>:8000/login`
3) Login with the user we just created

This should replicate the issue.

**Comment by waprin** [comment]
Very sorry for delay, was traveling ,will investigate today.

**Comment by waprin** [comment]
@jayanth1991 sorry again for delay - what did you expect to have happen? I guess I could make the sample redirect the login page to index by default, but really the point of the sample is to demonstrate the oauth decorator. Logging in directly and handling the views after that is not what the sample  are trying to demonstrate. If you look at the views, you see there are ones that are protected by oauth_decorators and which should kick off both the oauth and login flows. What happens after that flow is after you.

http://stackoverflow.com/questions/29082682/django-redirect-after-successful-login

Let me know if I'm misunderstanding your problem and we can re-open the issue, or feel free to ask any more questions.
