### ISSUE TITLE
Unpickle problems when upgrading from Python 2.7 to 3.5

### ISSUE THREAD

**Issue by chripede** [google/oauth2client#672]
I've been using the Django contrib CredentialsField to store authentications in my database. This all happened in Python 2.7

I'm trying to upgrade to 3.5, but the pickled CredentialsField is giving me some problems. It seems impossible to unpickle an Python 2.7 object in Python 3 that contains both strings and a datetime. See http://bugs.python.org/issue22005

Is there any "best practice" way to do this, or will I need to convert everything to JSON and the pickle it again?

**Comment by jonparrott** [comment]
Unfortunately I don't know if there's anything we can do to solve the cross-major-version datetime pickle problem in this library. If I had to recommend anything, it would be to use json to convert.

**Comment by chripede** [comment]
@jonparrott how would you feel about a pull request that replaces pickle with jsonpickle? I see the views.py in the django contrib started using it.

In that case all that's needed is loading and re-saving every object to get them converted and future proofed.

**Comment by jonparrott** [comment]
I'd prefer not to change anything major like that at the moment. Though, @bjwatson might disagree.

**Comment by bjwatson** [comment]
I second what @jonparrott says. I'd prefer to do major changes to https://github.com/GoogleCloudPlatform/google-auth-library-python instead, unless something is really broken in this repo.

**Comment by chripede** [comment]
I'd argue that this isn't a major change.

1. It's in the django contrib module only
2. It will still work with pickled models
3. If jsonpickle is not installed it can just fall back to pickle, it could even be a config switch.

**Comment by jonparrott** [comment]
If the change only applies to contrib.django I'm okay with it.

**Comment by bjwatson** [comment]
I defer to your judgement @jonparrott.

**Comment by waprin** [comment]
I already made jsonpickle a dependency of the module so I am in favor of this change, thanks for the issue and kicking off the PR.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
