### ISSUE TITLE
file_cache is unavailable when using oauth2client >= 4.0.0

### ISSUE THREAD

**Issue by renatosamperio** [google/oauth2client#673]
Hi,

I had installed version 4.0.0 (SHA 92e4ad332992b91d4674335f3d83a7181e38967d) from repository and I had received this message:
`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
`

The exception appears when I use the package googleapiclient (SHA [f19307d](https://github.com/google/google-api-python-client/commit/f19307d2079e3c3854cac887f059655a66c49896)). I have very little idea of how both packages work in their insides. 

Any feedback is very welcome. 

Regards,

Renato

**Comment by jonparrott** [comment]
Typicallly this is a warning and not an error. Is it causing your application to halt? If so, can we see a complete traceback?

**Comment by renatosamperio** [comment]
Thanks for your reply.

Indeed it is a warning and it seems is not breaking anything.

Regards,

Renato.
