### ISSUE TITLE
clientsecrets.py, line 121, in _loadfile     with open(filename, 'r') as fp: TypeError: coercing to Unicode: need string or buffer, dict found

### ISSUE THREAD

**Issue by suyashgithub** [google/oauth2client#675]
I am using django 1.10 with python 2.7 , my setting files is GOOGLE_OAUTH2_CLIENT_SECRETS_JSON ={
    'secret_key': '<secret_code>',
    'client_id': '<client_id>',
    'client_secret': '<client_secret>',
    'scope' : '<scope>',
    'redirect_uri': '<redirect_uri'>'
}
CredentialsModel is :
from django.contrib.auth.models import User
from django.db import models
from oauth2client.contrib.django_util.models import CredentialsField
class CredentialsModel(models.Model):
  id = models.ForeignKey(User, primary_key=True)
  credential = CredentialsField()

when i am creating the migration  then getting this error

  File "/Users/suyash/virtualenvs/sr/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Users/suyash/virtualenvs/sr/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
TypeError: coercing to Unicode: need string or buffer, dict found

**Comment by shoemakerdr** [comment]
[According to the source](https://github.com/google/oauth2client/blob/9f0618d53481a3afe2d0cf232131ba21dcf583de/oauth2client/contrib/django_util/__init__.py#L59), GOOGLE_OAUTH2_CLIENT_SECRETS_JSON is meant for storing the filepath, not the actual credentials.

You can directly store the client_id and client_secret fields though, like so:

``` python
GOOGLE_OAUTH2_CLIENT_ID=client_id_field
GOOGLE_OAUTH2_CLIENT_SECRET=client_secret_field
```

This is really old issue, so you probably figured this out already, but I figured I'd throw it out there anyways, so this issue could be closed.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
