### ISSUE TITLE
Restrict access to a specified domain with flask_util.

### ISSUE THREAD

**Issue by rfinck** [google/oauth2client#677]
I am using oauth2client.contrib.flask_util for an application whose access I want to restrict to accounts at a specified Google Apps domain. To do this, I've edited the callback view to check the 'hd' field of the credential's id_token just before saving the credentials to storage. The particular domain is given as a kwarg to init_app, which means that it gets passed to client.OAuth2WebServerFlow, which already recognizes it and adds a helpful message to the log-in page indicating that an email address at that domain is expected. (It appears, however, that that argument is not enough to restrict access, hence the changes to the callback view, although if there is already a built-in way to restrict I'd be happy to use that instead.)

If this is something that'd be generally useful, I can make a pull request.

**Comment by jonparrott** [comment]
@rfinck interesting. Does the [`authorize_callback`](https://github.com/google/oauth2client/blob/master/oauth2client/contrib/flask_util.py#L251) not cover this use case without needing to override the callback view?

**Comment by rfinck** [comment]
I had initially used an authorize_callback for this purpose, but didn't like that I was storing the credentials for a user who was not actually authorized. Once they're stored, you'd need to delete them in the authorize_callback otherwise oauth2.required will be able to fetch them and allow access. I believe it's cleaner and safer to  prevent the credentials from being stored rather than storing then deleting them for unauthorized users. Perhaps the [storage.put and the authorize_callback](https://github.com/google/oauth2client/blob/master/oauth2client/contrib/flask_util.py#L426) could swap their order and that'd solve this? I haven't checked if that'd cause other problems.

I also tried a wrapper around oauth2.required to check the domain, but had a problem when using that with redirect loops that I *thought* this approach fixed, but right now I'm seeing a similar problem again so it may be unrelated. It might actually be an issue with a session token being updated but not saved -- but I digress, although it may be another issue in a few minutes.

**Comment by jonparrott** [comment]
Interesting. The reason I ask is because I'd rather figure out how to make `flask_util` flexible enough to handle this case without hardcoding it. Do you think if we made it where if `authorize_callback` returns False it aborts?

**Comment by rfinck** [comment]
I think it could work if `authorize_callback` returns False *and* it is called before the credentials are stored. Most existing usages of `authorize_callback` probably return None, however they could possibly return False which would then make this a breaking change. But if the `authorize_callback` redirects to, say, an application's logged out page, would that be sufficient without the callback view needing to evaluate its return value?

I see your point about flexibility, and the above approach may be better, but if it's not I wouldn't consider using a kwarg that is already recognized by OAuth2WebServerFlow to be 'harcoding' something in. The entire change I made to the callback view was

```
domain = flow_kwargs.get('hd', False)
if domain and credentials.id_token.get('hd') != domain:
    return ('Unauthorized: you must sign in with an account belonging '
            'to the {0} domain.'.format(domain), httplib.FORBIDDEN)

```

I've looked around and seen a few other questions where people want to restrict to a domain -- not necessarily with flask, but I do think it's a common enough requirement that some optional behavior based on domain isn't obscure.

**Comment by cslamar** [comment]
Any resolution on this?  I'm trying to do the same in Django and am coming up short without overriding the callback.

**Comment by rfinck** [comment]
I've been using the above patch successfully. If you end up with a different Django solution I'd be interested to see it.

**Comment by clayheaton** [comment]
@rfinck I agree that the ability to restrict to a domain would be useful, especially for people working under G Suite accounts that don't want to go with a complicated SAML SSO solution. Did you fork this library to integrate your patch or just override the `callback_view()` method? I'm trying to determine the most simple way to restrict to a company domain without being hacky.

**Comment by rfinck** [comment]
I had forked it thinking that'd be a temporary fix. 

@jonparrott, what are your current thoughts on this (or another) solution?

**Comment by jonparrott** [comment]
My current thoughts are that it's highly unlikely I'll be adding any new
features to this library.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
