### ISSUE TITLE
Store the original id_token JWT in OAuth2Credentials

### ISSUE THREAD

**Issue by clancychilds** [google/oauth2client#678]
Currently, the credentials that are returned as a JWT in an identity token are extracted and stored in their extracted state, but the JWT itself is not retained. In some flows (like using the [Auth0 Delegation endpoint](https://auth0.com/docs/api/authentication#!#post--delegation)) having the original JWT is required.
I would like to add the full JWT to the id_token dict in OAuth2Credentials. Probably as 'jwt'.

**Comment by jonparrott** [comment]
I'm open to this in general, but we're avoiding making large changes to this library unless totally necessary. Are you willing to send a PR to see what the impact will be?

**Comment by clancychilds** [comment]
Yes. Working on one now.

**Comment by clancychilds** [comment]
As discussed, I have submitted a PR that would address this. 
https://github.com/google/oauth2client/issues/680
