### ISSUE TITLE
Make scope parameter optional on flow.step2_exchange

### ISSUE THREAD

**Issue by TZubiri** [google/oauth2client#692]
I am working on a non-google api (MercadoLibre), and their server will return an error if I pass too many arguments when authenthicating. My proposed solution is to keep the scopes parameter mandatory, but add a check on flow.step2_exchange where, if the scope variable doesn't exist, it doesn't add it to the post request.
This way I can set the scope variable to none before calling step2.
I am aware this is a Naive solution, and if some other code depends on scope, the library might break.  Let me know what you think, I'll link the pull request.
Thanks!

**Comment by TZubiri** [comment]
https://github.com/google/oauth2client/pull/691

**Comment by TZubiri** [comment]
Relevant Blogpost:
http://blog.jonparrott.com/using-googles-oauth2client-to-authenticate-to-salesforce-in-python-2/
Jon Parrott ran into the same problem when trying to use oauth2client to connect to Salesforce API. He solved the problem by monkeyPatching the step2_exchange function not to include the scope parameter.
This is currently my solution too. But since I am trying to publish this as a module to connect to the mercadolibre API.  This change would make the layer on top of oauth2client much thinner.

**Comment by jonparrott** [comment]
@TZubiri While I appreciate the effort, I would just recommend using a different auth library like `requests-oauthlib`.
