### ISSUE TITLE
Google-oauth is not working inside Jupyter Notebook

### ISSUE THREAD

**Issue by snarb** [google/oauth2client#695]
When importing modele with recomended code: 
flags = argparser.parse_args()
credentials = run_flow(flow, storage, flags) inside Jupyter Notebook got exception.

Simple
   from oauth2client.tools import argparser
   argparser.parse_args()

Failing with:

usage: __main__.py [--auth_host_name AUTH_HOST_NAME]
                   [--noauth_local_webserver]
                   [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                       [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
    __main__.py: error: unrecognized arguments: -f /run/user/1000/jupyter/kernel-c9aa5199-fcea-4884-8e5f-a004c66a733e.json

SystemExit                                Traceback (most recent call last)
<ipython-input-3-d141fc7aebe0> in <module>()
----> 1 argparser.parse_args()

/usr/lib/python3.5/argparse.py in parse_args(self, args, namespace)
   1736         if argv:
   1737             msg = _('unrecognized arguments: %s')
-> 1738             self.error(msg % ' '.join(argv))
   1739         return args
   1740 

/usr/lib/python3.5/argparse.py in error(self, message)
   2392         self.print_usage(_sys.stderr)
   2393         args = {'prog': self.prog, 'message': message}
-> 2394         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

/usr/lib/python3.5/argparse.py in exit(self, status, message)
   2379         if message:
   2380             self._print_message(message, _sys.stderr)
-> 2381         _sys.exit(status)
   2382 
   2383     def error(self, message):

SystemExit: 2

**Comment by ncouture** [comment]
@snarb Could you provide more information about what you're trying to do and what the source of the _recommended code_ you're running is?

At first glace it looks like what you tried to do resulted in parsing the Jupyter command line arguments.

**Comment by wmmxk** [comment]
Hi Snarb. Have you worked it to run  argparser.parse_args() in jupyter notebook. I also run into this problem today.

**Comment by craigcitro** [comment]
The issue here is just what @ncouture guessed -- you're not passing any args to `parse_args`, so it's trying to parse `sys.argv`.

Try calling `argparser.parse_args([])`, or add additional arguments there as you'd like.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
