### ISSUE TITLE
oauth2callback endpoint provided by flask extension has an XSS vulnerability.

### ISSUE THREAD

**Issue by jkrukoff** [google/oauth2client#709]
Due to a lack of sanitisation in the error parameter, it is possible for arbitrary code to be reflected on the oauth2callback endpoint (this vulnerability is referenced as OTG-INPVAL-001 in the OWASP Testing Guide). 

Using the default setup of the contrib flask extension:
```oauth2 = oauth2client.contrib.flask_util.UserOAuth2(app)```

The /oauth2callback endpoint then allows for an XSS attack like so:
```
/oauth2callback?error=a%3C!%27/*!%22/*!\%27/*\%22/*--!%3E%3C/Title/%3C/script/%3E%3CInput/Autofocus/%0D*/Onfocus=confirm(document.domain)//%3E%3Csvg%3E
```

We had this reported as a security issue on all our services that make use of oauth2client, requiring an urgent switch to a different authentication method.

**Comment by jonparrott** [comment]
@jkrukoff any recommendations on resolving this? Would it be enough for us to pass it through markupsafe?

In the meantime, you're welcome to subclass UserOAuth2 and override the method used to proecess the response.

**Comment by jkrukoff** [comment]
My understanding is that it'd be sufficient to HTML escape the value there. I haven't investigated thoroughly, just passing along a replicated report upstream.
