### ISSUE TITLE
ServiceAccountCredentials don't work with SMTP XOAUTH2 Mechanism

### ISSUE THREAD

**Issue by genzgd** [google/oauth2client#711]
I'm trying to use XOAUTH2 as described [here](https://developers.google.com/gmail/imap/xoauth2-protocol) in combination with the standard Python 3.4 smtplib and the ServiceAccountCredentials credentials object from a json keyfile.   I get the access token using credentials.get_access_token().  I've tried sending the following combinations to the Google SMTP server, but all have returned an SMTP code 535, "Username and Password not accepted".

ACCESS_TOKEN is the string I get from credentials.get_access_token().access_token] (changes every run because of timestamps)
ACTUAL_GMAIL is the actual address I want to send from (lampostmessage@gmail.com)
SERVICE_EMAIL is the client_email from the service account/json keyfile

user=ACTUAL_GMAIL  access_token=ACCESS_TOKEN
user=SERVICE_EMAIL  access_token=ACCESS_TOKEN
user=ACTUAL_GMAIL  access_token=Base64 encoded ACCESS_TOKEN
user=SERVICE_EMAIL  access_token=Base64 encoded ACCESS_TOKEN

Each time the whole string is again base 64 encoded as described in the above link:  
base64("user=" {User} "^Aauth=Bearer " {Access Token} "^A^A").

The response is always the SMTP error message:  
code 334  Message {"status":"400","schemes":"Bearer","scope":"https://mail.google.com/"}

Additional error info after sending a blank command as documented:  
code 535, Message b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials g73sm7761727ioi.31 - gsmtp'

At a minimum some sample code of how to do this that is newer than 2012 (see [here])(https://developers.google.com/gmail/imap/xoauth2-libraries) would be much appreciated. Do I need some different access token?  How do things need to be encoded/decoded (especially in Python3 where all the strings are Unicode)?.

Yes, I could do this with the Google mail APIs but then I have to have two different email mechanisms depending on the configured email.  (Also, using a password works fine here if I set the account to "allow access to less secure apps")

**Comment by jonparrott** [comment]
@genzgd could you share the code you're using to generate the access token?

**Comment by genzgd** [comment]
Here's the extracted piece:

```
from oauth2client.service_account import ServiceAccountCredentials
scopes = ['https://mail.google.com/']
credentials = ServiceAccountCredentials.from_json_keyfile_name('data/google_api.json', scopes=scopes)
access_token_info = credentials.get_access_token()
access_token = bytes(access_token_info.access_token, 'ascii')
auth_string = b'user=' + bytes(params['sender_email_address'], 'ascii') + b'\1auth=Bearer ' + access_token + b'\1\1'
code, msg = self.server.docmd('AUTH', 'XOAUTH2 ' + (base64.b64encode(auth_string)).decode('ascii'))
log.info("Code {}  Message {}", code, base64.decodebytes(msg))
if code == 235:
    return True
code, msg = self.server.docmd('')
log.info("code {}, Message {}", code, msg)
return False
```

I've had to convert various things to byte strings from standard UTF8 strings to use the b64encode method.  As I mentioned I've tried both the service account email and the actual gmail address for 'user'.

The message base 64 decoded message is always  {"status":"400","schemes":"Bearer","scope":"https://mail.google.com/"}

At this point I'm wondering if the issue is scopes.  I'm using a "project" service account from the developers console, not G Suite service account.

**Comment by jonparrott** [comment]
Since gmail is a user resource API, you need to access gmail as a user. You either need to use user credentials (OAuth2Credentials) or use a service account with gsuite Domain Wide Delegation (and call `credentials = credentials.create_delegated(user_email)`.

**Comment by genzgd** [comment]
I guess that makes sense.  Since I can't seem to do GSuite delegation from https://console.developers.google.com/apis/credentials, I'll have to do three legged OAuth2 to get my initial access and refresh token for this particular user (which is annoying, since I can't do it from my app server without manual interaction).
