### ISSUE TITLE
Is it safe to upgrade from 2.0.1 to 4.1.0?

### ISSUE THREAD

**Issue by john-bonachon** [google/oauth2client#716]
I'm having some issues with refresh tokens, and I wonder if 4.1.0 changes on refresh token code would solve this.

Is it safe to upgrade from 2.0.1 to 4.1.0?

**Comment by jonparrott** [comment]
@john-bonachon there are multiple breaking changes between 2.0.1 and 4.1.0. I'd suggest taking a look at the [release notes](https://github.com/google/oauth2client/blob/master/CHANGELOG.md). Also, keep in mind that if you are using pickle to persist credentials long-term, they likely won't be unpicklable in the new version.
