### ISSUE TITLE
invalid_grant: Bad Request

### ISSUE THREAD

**Issue by Cosbgn** [google/oauth2client#719]
So I just noticed that oauth2client is now deprecated. I'm relying a lot on this library and I would really like to avoid transactioning my whole code to `google-oauth`. Is this invalid_grant: Bad Request problem related to the depreciation? 

When my client logs in into my site, it all works fine, however when I try to update his data via cron jobs I get this invalid grant. I've read that could be related to timestamps but I don't think it's the case as some users get updated fine, and others don't. This is my setup:
```

# /start
def start_google(request):
	"""first step Oauth2 to google analytics and get code"""
	flow = OAuth2WebServerFlow(client_id = settings.GOOGLE_OAUTH2_CLIENT_ID,
						   client_secret = settings.GOOGLE_OAUTH2_CLIENT_SECRET,
						   scope = settings.GOOGLE_SCOPE,
						   redirect_uri = settings.OAUTH_REDIRECT_URI,
   						   access_type='offline', # Does it work? How can I test it?
						   )
	auth_uri = flow.step1_get_authorize_url()
	return HttpResponseRedirect(auth_uri)

# /gconnect
def exchange_code_and_login(request): # can I divide them in 2?
	"""Step 2: connect to google analytics API"""
	flow = OAuth2WebServerFlow(client_id = settings.GOOGLE_OAUTH2_CLIENT_ID,
						   client_secret = settings.GOOGLE_OAUTH2_CLIENT_SECRET,
						   scope = settings.GOOGLE_SCOPE,
						   redirect_uri = settings.OAUTH_REDIRECT_URI,
						   access_type='offline', # Does it work? How can I test it?
						)

	if request.method == 'GET':
		if 'code' in request.GET:
			code = request.GET['code']
			credentials = flow.step2_exchange(code)
			http = httplib2.Http()
			http = credentials.authorize(http)
			service = build('analyticsreporting', 'v4', http=http)
```

When the user clicks goes on the site, he triggers the `start_google` function this works fine and I manage to get/update his data. 

However when I do that offline, via cron jobs with this function:
```

def update_site(request, callback_args): # called via /save/view_id
    VIEW_ID = str(callback_args)
    current_user = GoogleProperty.objects.get(view_id=VIEW_ID).google_email
    credentials = CredentialsModel.objects.get(google_email=current_user).credentials
    http = credentials.authorize(httplib2.Http())
    DISCOVERY_URI = ('https://analyticsreporting.googleapis.com/$discovery/rest')
    analytics = build('analytics', 'v4', http=http, discoveryServiceUrl=DISCOVERY_URI)
    start_date = '20daysAgo'
    end_date = 'today'

    get_sessions(current_user, VIEW_ID, credentials, analytics, start_date, end_date)
```

For some of the users I get `invalid_grant: Bad Request` for others it works fine. What could be the issue?

**Comment by Cosbgn** [comment]
So upon some extra research on the problem I discovered what was causing it, I made a function like this:

```
def update all(request):
    x = GoogleProperty.objects.all()
    for site in x:
        VIEW_ID = str(site.view_id) #why this needs to be a string? 0.o
        current_user = site.google_email
        credentials = CredentialsModel.objects.get(google_email=current_user).credentials

        print(str(current_user)+' has a refresh token: '+str(credentials.refresh_token))
        print('token expires: '+str(credentials.token_expiry))
        # Update all data..

```

I discovered that a refresh_token is created when the user logs in, however after a while, it disappears, which is weird. I thought oAuth2Client would automatically update new tokens using refresh tokens, but maybe I'm wrong. Am I supposed to save the refresh token when the user signs up for the first time and save it somewhere separate and every-time check/get a new token?

Also, the function above printed something like this:
```
user1 has a refresh token: 1/MZtcPN31***********
token expires: 2017-05-28 23:59:42.998677

user2 has a refresh token: 1/_yRPztPXU****************
token expires: 2017-06-11 02:48:24.824183

user3 has a refresh token: 1/72ZU_nC7DE********************
token expires: 2017-06-11 02:53:14.143815
```
Some of the tokens are clearly expired, however is there is something, I'm able to update/get user's data, if the token doesn't exist I can't.

Would it make sense to save to refresh token on a separate model, and then check and do something like:
```
if credentials.refresh_token == 'None':
         credentials.refresh_token = SomeOtherModel.objects.get(user=user).refresh_token
else:
      print('Great the user still has a refresh token, all good')
```

Does this makes sense?
For how long I would be able to use the refresh token without issues, is the refresh token valid forever? 

Thansk

**Comment by jonparrott** [comment]
I really can't explain why the refresh token is disappearing. It could be an issue with how you're storing your credentials (which could implicate this library or something in your application). Another possible explanation is that you're re-prompting the user for another access token and saving those credentials over the existing ones - if you do this without `prompt=consent`, the OAuth 2.0 token endpoint will not give you a refresh token even if it previously issued on to you.

In general, refresh tokens are long-lived. They should work "indefinitely". However, they can be revoked by a user, in which case you'll get a access token refresh error when you try to use the credentials. You should tend obtain a new set of tokens using the flow and `prompt=consent`.

**Comment by Cosbgn** [comment]
Hi @jonparrott thanks for answering even though the depreciation. I discovered few things, the `refresh token` is given **only** when the user agrees to share his data, this means that if I use `prompt=force` I would get it every time but I would also give a terrible experience to my users. 

The token was "disappearing" because I was re-saving it in the database every time the user logs in, the first time it works fine, but as soon as the user becomes a returning user I would "save" an empty token.

I solved this doing the following:

```
			# Save Credentials to DB
			obj, created = CredentialsModel.objects.get_or_create(user_id=current_user.id, defaults={
																									'credentials': credentials,
																									'google_email': google_email,
																									})
			c = CredentialsModel.objects.get(user_id=current_user.id)
			if c.credentials.refresh_token != None:
				# This means that it's a new refresh_token, let's save it!
				c.refresh_token = c.credentials.refresh_token
				print ('New Refresh Token Saved: '+str(c.refresh_token))
				c.save()
			else:
				print ('Not Saved: '+str(c.credentials.refresh_token))
				pass
```
This pretty much checks if the new token is not `none` it would save it, otherwise it won't and I'll keep the old token.

Then when I need to access the info I use:

```

def get_analytics(current_user):
    c = CredentialsModel.objects.get(google_email=current_user)

    if c.credentials.refresh_token != None:
        http = c.credentials.authorize(httplib2.Http())
        DISCOVERY_URI = ('https://analyticsreporting.googleapis.com/$discovery/rest')
        analytics = build('analytics', 'v4', http=http, discoveryServiceUrl=DISCOVERY_URI)
        print(str(current_user)+' - All good, token already there: '+c.credentials.refresh_token)
        return analytics

    else:
        c.credentials.refresh_token = c.refresh_token
        # c.save() - Maybe I don't even need to save and mess around with credentials..
        http = c.credentials.authorize(httplib2.Http())
        DISCOVERY_URI = ('https://analyticsreporting.googleapis.com/$discovery/rest')
        analytics = build('analytics', 'v4', http=http, discoveryServiceUrl=DISCOVERY_URI)
        print(str(current_user)+' - I have added the token: '+ str(c.credentials.refresh_token)+', now evrything should work')
        return analytics
```
Which will check if the token for some reason is Null (it shouldn't be) but if it is it will fetch the token from a different model.

I hope this will help others to deal with refresh tokens without the pain and terrible ux of `prompt=force`. 

I'll close the issue, thanks for the help. However if you see some lack on security or other problems on my approach above please do let me know and add a comment!
