### ISSUE TITLE
DjangoORMStorage: GOOGLE_OAUTH2_CLIENT_ID and GOOGLE_OAUTH2_CLIENT_SECRET empty in settings.py 

### ISSUE THREAD

**Issue by mauroka** [google/oauth2client#730]
Hello, is there a problem in setting GOOGLE_OAUTH2_CLIENT_ID and GOOGLE_OAUTH2_CLIENT_SECRET empty in settings.py like this?
GOOGLE_OAUTH2_CLIENT_ID = ""
GOOGLE_OAUTH2_CLIENT_SECRET = ""

It's because I am trying to use OAuth2WebServerFlow without a JSON file and load the client_id and client_secret from the Database for everyone of my multiple tenants.

And when I store the credentials using DjangoORMStorage it throws a:
Must specify either GOOGLE_OAUTH2_CLIENT_SECRETS_JSON, or either GOOGLE_OAUTH2_CLIENT_SECRETS_JSON, or both GOOGLE_OAUTH2_CLIENT_ID and GOOGLE_OAUTH2_CLIENT_SECRET in settings.py

Thanks a lot for the help.
Cheers.

**Comment by waprin** [comment]
What your doing is not necessarily wrong, just not currently supported by the library. You'd have to modify the code a bit to load it from the database. This library is currently deprecated, so we're not going to add it as a feature, but it should only be a bit of changes to add it yourself. Let me know if you need pointers.

**Comment by mauroka** [comment]
Hi @waprin 
I seted GOOGLE_OAUTH2_CLIENT_ID = "" and GOOGLE_OAUTH2_CLIENT_SECRET = "" and everything works just fine.
I loaded client_id and client_secret for OAuth2WebServerFlow from a Database without a problem.
And storage.get() and storage.put() seems to work just fine.

My question is if there is a problem keeping GOOGLE_OAUTH2_CLIENT_ID = "" and GOOGLE_OAUTH2_CLIENT_SECRET = "" (empties).
I don't know, maybe they are used when the storage.get() or storage.put() methods are called.
Like I said, the code works, but I am not sure if there will be a problem in the future.

Thank you very much for the help.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
