### ISSUE TITLE
ImportError: cannot import name 'urlresolvers'

### ISSUE THREAD

**Issue by Feduch** [google/oauth2client#744]
**Note**: oauth2client is now deprecated. As such, it is unlikely that we will
address or respond to your issue. We recommend you use
[google-auth](https://google-auth.readthedocs.io) and [oauthlib](http://oauthlib.readthedocs.io/).

Hi!

ImportError: cannot import name 'urlresolvers'

oauth2client==4.1.3
Django==2.0.3

**Comment by sduskis** [comment]
@googleapis/yoshi-python, any ideas?

**Comment by theacodes** [comment]
This library is deprecated and this is not a security issue. Closing. I'd recommend moving to google-auth.
