### ISSUE TITLE
OAuth2 Revokie URI no longer working

### ISSUE THREAD

**Issue by jay0lee** [google/oauth2client#750]
#743 seems to break revoking OAuth tokens via the refresh token:

$ gamd oauth revoke
This OAuth token will self-destruct in 3...2...1...boom!
connect: (oauth2.googleapis.com, 443)
send: 'GET /revoke?token=NNNNNREMOVEDNNNNNNN HTTP/1.1\r\nHost: oauth2.googleapis.com\r\naccept-encoding: gzip, deflate\r\nuser-agent: Python-httplib2/0.12.1 (gzip)\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Fri, 15 Feb 2019 18:35:39 GMT
header: Content-Type: text/html; charset=UTF-8
header: Server: ESF
header: Content-Length: 1621
header: X-XSS-Protection: 1; mode=block
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: Alt-Svc: quic=":443"; ma=2592000; v="44,43,39"

ERROR: Invalid response 404.

**Comment by theacodes** [comment]
Hi, this project is deprecated. Please move to google-auth.
