### ISSUE TITLE
OSError when OS doesn't support file operation

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#91]
multistore.py uses LockedFile for managing the credential store.  However, if the operating system doesn't support the necessary open+lock file operation https://github.com/google/oauth2client/blob/master/oauth2client/locked_file.py#L338 that's used by the opener class, it will raise this exception (usually an OSError) and likely kill its caller.

At a minimum, multistore_file should probably just return that a credential couldn't be loaded from the store in this case.

**Comment by jonparrott** [comment]
Superseded by #470
